### ISSUE TITLE
Feature request: Add option for TR2 cancel swimming animation

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1004]
Requested by RetroRaider279 on discord.

**Comment by lahm86** [comment]
The cancellation is achieved by having three additional state changes in the swimming animation to cover more frame windows. These link to intermediate glide animations that don't normally exist in TR1. So lots to inject.

Just noting this here for reference.

![image](https://github.com/LostArtefacts/Tomb1Main/assets/33758420/c5880a32-3794-4d89-abd0-216b3a45dfae)
![image](https://github.com/LostArtefacts/Tomb1Main/assets/33758420/611b4885-222f-4fbd-8a05-ba950662ea35)
