### ISSUE TITLE
Enhancement: Rotate Qualopec's scion 3D pickup to face logical direction

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1007]
| Level name       | Item # | Type  | Room | Rotate |
|------------------|--------|-------|------|--------|
| Tomb of Qualopec | 20     | Scion | 5    | 270    |

(The original post is archived below the margin.)
__________________________

Suggested by @walkawayy and a few others on discord.

Related to #914

**Comment by Richard-L** [comment]
This would be the most sensical orientation if you ask me:
![SLUS-00152_2023-09-28_16-58-26](https://github.com/LostArtefacts/TR1X/assets/4934209/2856a7ee-f93e-45bc-afb0-d9ed6117278f)

**Comment by aredfan** [comment]
@Richard-L to clarify, you'd like to see the front of the scion facing the camera/Qualopec, and the back of the scion to face the main entrance?

**Comment by Richard-L** [comment]
Good question, but yes, simply because like this it seems truest to the origin.
