### ISSUE TITLE
TR1X bug: Oversized inventory objects after death by Midas

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1009]
After Lara turns to gold from jumping onto the hand of Midas, the passport that appears is oversized:

![20230926_125846_Palace_Midas](https://github.com/LostArtefacts/Tomb1Main/assets/94776985/e810fee8-ab86-4f20-924b-9d891c33564c)

This is how the passport normally looks:

![20230926_130426_Palace_Midas](https://github.com/LostArtefacts/Tomb1Main/assets/94776985/b122b0b3-30e6-454c-bd7f-a2361a2cb164)

Also here's a screenshot of my internal graphic settings, if it helps:

![20230926_130123_Title](https://github.com/LostArtefacts/Tomb1Main/assets/94776985/747ba943-a695-402f-8f8c-76c3c6fc8c7f)

**Comment by walkawayy** [comment]
It's due to `g_Camera.type = CAM_CINEMATIC;` during the special gold animation. Guessing TombATI also has this bug?

**Comment by aredfan** [comment]
Wasn't 100% sure so I checked again, am sure now that TombATI doesn't have this bug.

TombATI after the gold animation:

![2](https://github.com/LostArtefacts/TR1X/assets/94776985/d1699919-0d1b-40e2-900c-3315a48fac8b)

TombATI when accessing the passport normally:

![1](https://github.com/LostArtefacts/TR1X/assets/94776985/9ab53a3c-0313-410b-bfc0-c9f57065687c)
