### ISSUE TITLE
Enhancement: 3d pickup animation for gold bars

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1010]
In my current playthrough, I noticed that when Lara collects the gold bars from the hand of Midas, there is no 3d pickup animation displayed.  Am unsure whether this is a bug or something else.  Related to #987.

**Edit:** I just checked TombATI and there isn't a sprite displayed in the corner so it's not a bug.

**Comment by Richard-L** [comment]
Hmm tricky one.

Strictly speaking it's not a pick up, it's changing an item you already have. 

Think it's okay to stay without an extra animation. I like the moment of checking the inventory, and noticing they've turned gold. But that's personal preference.
