### ISSUE TITLE
Lara will never step back down 1 click with her right foot

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#1014]
Wrong frame numbers in `Lara_Col_Back` prevents Lara from using `LA_BACK_STEP_DOWN_RIGHT` animation `62`. Confirmed the bug exists in TombATI.

https://github.com/LostArtefacts/TR1X/assets/81546780/a1610e9c-9876-41a9-8d13-bfa08c256b76

**Comment by aredfan** [comment]
Checked on TR2-5 and all of these have the bug too.  GL with fixing it.
