### ISSUE TITLE
TR1X bug: Visual glitch if 3D pickups are enabled

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1015]
I came across this bug when collecting any of the four obelisk keys.

If 3D pickups are enabled:
![1](https://github.com/LostArtefacts/TR1X/assets/94776985/322f9f35-3fb2-408d-89b6-e90149f18b2f)
If 3D pickups are disabled:
![2](https://github.com/LostArtefacts/TR1X/assets/94776985/619bfac4-a8da-4b64-84dd-8986e6c84ded)

**Comment by aredfan** [comment]
Second sighting of the visual glitch, this time in Atlantean Stronghold:
![1](https://github.com/LostArtefacts/TR1X/assets/94776985/d3edb1ac-17ba-4c86-ac47-2882623a1773)
Room 5 - Trigger type: Pickup - # 92

**Comment by rr-** [comment]
Hi, this has to do with disabling the Z Buffer tests for the sake of rendering the 3D pickups in front of the rest of the game. Could I get a save file where ideally it only takes to press the Action button upon loading to trigger this behavior? Thanks.

**Comment by aredfan** [comment]
Hey, of course!

[Saves.zip](https://github.com/LostArtefacts/TR1X/files/12840384/Saves.zip)

Wait a couple of seconds after loading because the z-buffer issue is not visible immediately.
