### ISSUE TITLE
Feature Request: option to disable/mute fan patched soundtrack in Unfinished Business

### ISSUE THREAD

**Issue by RetroRaider279** [LostArtefacts/TRX#1019]
While Tomb Raider 1's OST is legendary, The way fans have tried to implement the OST into Unfinished Business can sometimes be unfitting or distracting. Since we have no way of knowing how the developers would have wanted the OST to be implemented, I think it would be a good idea to include an option to disable/mute the fan patched OST altogether for those who would prefer a more stock experience.

**Comment by Richard-L** [comment]
You will achieve this by replacing the TombATI UB level files with the retail PC release (which I think is typically what you'll find online when searching for standalone UB).

I agree though it would be nice to have an option for this to avoid having to data meddle.

**Comment by RetroRaider279** [comment]
> You will achieve this by replacing the TombATI UB level files with the retail PC release (which I think is typically what you'll find online when searching for standalone UB).
> 
> I agree though it would be nice to have an option for this to avoid having to data meddle.

Yes but my understanding is that the original level files have a bug that prevents them from being completed. That and also  the convenience factor is why I suggested this.

**Comment by EternalCosmos92** [comment]
Bug fixes for levels come in form of injections. Those injections will also go into level files without music triggers

**Comment by Richard-L** [comment]
Whatever way the devs should find suitable.

@RetroRaider279 the level issue was recently fixed 👌 https://github.com/LostArtefacts/TR1X/issues/227

**Comment by aredfan** [comment]
IMO a better approach is to allow the user to pick between vanilla and fan-modified TRUB files via the installer.

**Comment by RetroRaider279** [comment]
> IMO a better approach is to allow the user to pick between vanilla and fan-modified TRUB files via the installer.

Yes, that's exactly what I was going to say. Thank you.

**Comment by aredfan** [comment]
Just to add, I think it's worth ensuring the following 2 files are included with both variants of TRUB:

- `CRED0.PCX` - The TRUB credit screen. This is already included with the music version btw.
- `TITLEH.PCX` - The TRUB main menu backdrop.  I would suggest renaming this file to `TITLEH_UB.PCX` to avoid a clash with the TR1 version.  We already have the installer extract all the .PCX files from TR1, thus it would be nice to have the vanilla TRUB backdrop included to complete the collection.

**Comment by RetroRaider279** [comment]
> Just to add, I think it's worth ensuring the following 2 files are included with both variants of TRUB:
> 
> * `CRED0.PCX` - The TRUB credit screen. This is already included with the music version btw.
> * `TITLEH.PCX` - The TRUB main menu backdrop.  I would suggest renaming this file to `TITLEH_UB.PCX` to avoid a clash with the TR1 version.  We already have the installer extract all the .PCX files from TR1, thus it would be nice to have the vanilla TRUB backdrop included to complete the collection.

Thank you for bringing up the fact that the original credit and title screens for Unfinished Business. I was thinking about making a request about it.

**Comment by rr-** [comment]
Hey, could I get zipfiles with both variants of UB, complete (eg including the graphic files mentioned above) and as small as possible (eg not containing anything that's not needed)?

It's OK to post it here as UB is freeware.

I agree that there should be an option to choose the variant in the installer and that's how we should go about it.

**Comment by aredfan** [comment]
Of course, and thank you!

[TRUB vanilla.zip](https://github.com/LostArtefacts/TR1X/files/12839944/TRUB.vanilla.zip)
[TRUB music.zip](https://github.com/LostArtefacts/TR1X/files/12839945/TRUB.music.zip)

@Richard-L can I ask you to inspect these to make sure everything is present and correct, thank you.

**Comment by Richard-L** [comment]
Yep, your `TRUB.vanilla.zip` matches the EU release of UB.

FWIW the [US release](https://secretsrunner.web.fc2.com/image/TR1/us/TR1GOLD_Trapezoid_Box.jpg) has two differing level files for `CAT.PHD` and `EGYPT.PHD`:  
[TRUB-vanilla_US-unique-files.zip](https://github.com/LostArtefacts/TR1X/files/12841097/TRUB-vanilla_US-unique-files.zip)

I didn't check your music variant because you probably just copy/pasted that from TombATI so should be fine 👌
