### ISSUE TITLE
TR1X bug: Look at Item function is less rigid

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1026]
**Update:** This bug occurs when `Look while Running` is enabled.

___________________________________

First discovered in Temple of the Cat.  Basically have Lara stand in this spot and face the pyramid, then start tapping left and stop the moment the camera locks onto item.

TR1X:
![1 2 TR1X](https://github.com/LostArtefacts/TR1X/assets/94776985/e1a1ab66-41ec-483c-8896-c0cd1dd8bf41)

TombATI, with the same steps repeated.  Notice the circled boulder - that is what the camera should lock on, but it's not visible in the above screenshot:
![1 1 TombATI](https://github.com/LostArtefacts/TR1X/assets/94776985/d0ca284f-1287-4172-9320-4c27879e07ae)

TR1X, if I have Lara turn the other way by tapping right until the camera locks onto item:
![2 2 TR1X](https://github.com/LostArtefacts/TR1X/assets/94776985/5277bf00-7a1f-42ce-a091-beb0cb32e8c8)

TombATI, with the same steps repeated as above.  Once again the circled boulder is out of view in the prior screenshot:
![2 1 TombATI](https://github.com/LostArtefacts/TR1X/assets/94776985/e6d4368b-da2e-4b0c-aa3f-94e1f91671c0)

After this, I investigated Caves and can confirm the bug happens there as well.  When you reach the area with the opening, have Lara face away, then start tapping left until the camera locks onto item.

TR1X:
![3 2 TR1X](https://github.com/LostArtefacts/TR1X/assets/94776985/50722461-3ad6-460f-82ac-92af5b5371ed)

TombATI, same spot:
![3 1 TombATI](https://github.com/LostArtefacts/TR1X/assets/94776985/a3e06495-1e46-415a-bf2c-363e476a313c)

So my conclusion is the Look at Item function is less rigid in TR1X than in TombATI.

**Comment by Richard-L** [comment]
Could this at all be a combination of different draw distance, FOV, etc ...that TR1X allows to configure?

If you have a setup for the Caves case, I could try it on PS1 perhaps.

**Comment by aredfan** [comment]
Sure thing, here's my setup.  Not sure if there's any other setting that might be relevant.

Config:
Field of view: 65
Vertical FOV: Enabled
Aspect ratio: 16:9

Gameflow:
"draw_distance_fade": 72.0,
"draw_distance_max": 80.0,

**Update:** I also checked the DOS version.  The camera position here matches TombATI.
![1](https://github.com/LostArtefacts/TR1X/assets/94776985/fac18581-7c1b-4c6b-8108-7a1edfb97688)

**Comment by walkawayy** [comment]
Do you have `Look while Running` enabled? If I disable it, I think they match:

![image](https://github.com/LostArtefacts/TR1X/assets/81546780/9825ed87-52af-4ae2-83c5-343609fd46d7)

**Comment by aredfan** [comment]
> Do you have `Look while Running` enabled? If I disable it, I think they match:

Yep I did have that setting enabled.  Disabling the setting fixed the issue in both Caves and Temple of the Cat.

**Comment by walkawayy** [comment]
> > Do you have `Look while Running` enabled? If I disable it, I think they match:
> 
> Yep I did have that setting enabled. Disabling the setting fixed the issue in both Caves and Temple of the Cat.

Ok cool. We will have to investigate if the original looking can be maintained if the player also wants look while running.

**Comment by aredfan** [comment]
That'd be grand.  Thank you.

**Comment by rr-** [comment]
We're currently in the process of decompiling TR2 for TR2X. I expect that we should have the relevant Lara state functions ready sometime next week.
