### ISSUE TITLE
Enable Game Modes function does not work

### ISSUE THREAD

**Issue by Opaque79** [LostArtefacts/TRX#1027]
Game mode selection remains enabled regardless of this option. Even forcing it does not disable it. What's going on?

**Comment by Richard-L** [comment]
I believe I've had the same outcome. Wasn't sure if it was just me misconfiguring the option though.

**Comment by Richard-L** [comment]
I believe I've had the same outcome. Wasn't sure if it was just me misconfiguring the option though.

**Comment by Opaque79** [comment]
Yea, not sure what's going on. Even forcing disabled in the gameflow cfg file does not disable the game mode options

**Comment by walkawayy** [comment]
Make sure `"force_disable_game_modes": false,` is set in the gameflow.json5 for TR1 and Unfinished Business.

Then you can use the config tool to set `Enable game modes` how you like it.

Setting `"force_disable_game_modes": true,` should always disable the game modes. As far as I know this should be working.

**Comment by Opaque79** [comment]
The problem is, it's never disabled for me. Even if I force them disabled, it is still enabled regardless

**Comment by EternalCosmos92** [comment]
"new_game_plus_unlock" in the Tomb1Main.json file needs to be set to false. It changes to true automatically once the last level is beaten. It is pretty far down the list.

**Comment by walkawayy** [comment]
Oh I forgot. Now once you have completed the game at least once, the NG+ menu shows. Yes @EternalCosmos92 is right.

**Comment by Opaque79** [comment]
That works and it makes sense. Disabling it after each playthrough would be more hassle than just leaving it enabled.

This is now solved

**Comment by Richard-L** [comment]
So the game knows if it's been completed once before, regardless of what playthrough you load?

And if it's been completed, that means it unlocks NG+, JP NG _and_ JP NG+, even if the enable game modes setting is disabled?

**Comment by Opaque79** [comment]
> So the game knows if it's been completed once before, regardless of what playthrough you load?
> 
> And if it's been completed, that means it unlocks NG+, JP NG _and_ JP NG+, even if the enable game modes setting is disabled?

It seems that way. Once a playthrough is completed, the game modes are always enabled regardless of setting until you disable new game plus unlock in the cfg

**Comment by walkawayy** [comment]
> So the game knows if it's been completed once before, regardless of what playthrough you load?
> 
> And if it's been completed, that means it unlocks NG+, JP NG _and_ JP NG+, even if the enable game modes setting is disabled?

Yes. In the original game, once you beat the game, the new game option always started a new game plus save. If you exited the game and reopened in the future though, the game would only ever start with a normal new game. We changed it so the new game plus menu can be enabled / disabled on first playthrough, but once you beat the game, you have the option to use NG+ or not which is how modern games act.

**Comment by Richard-L** [comment]
Okay, I think that makes sense. Was just asking to understand the behaviour.

Perhaps the wording of the enable game modes option might want to receive a small addition along the lines of "if the game has not yet been completed, then ..."?

**Comment by walkawayy** [comment]
> Okay, I think that makes sense. Was just asking to understand the behaviour.
> 
> Perhaps the wording of the enable game modes option might want to receive a small addition along the lines of "if the game has not yet been completed, then ..."?

This is now the wording in the new `GAMEFLOW.MD`

`Forces game mode selection to be disabled if true so the user can't select NG+ modes until a playthrough is completed. Overrides the config option enable_game_modes.`

**Comment by rr-** [comment]
Hey, I think the issue can be closed? Or is there anything we may improve (short of changing the behavior back)?

**Comment by Richard-L** [comment]
Could be considered maybe that when "Enable Game Modes" is set to `false`, NG+ is never possible, and any playthrough is just a NG.

**Comment by walkawayy** [comment]
I don't think that's necessary. The way it behaves now allows the user to choose once they've beaten the game instead of the odd behavior in the OG game.
