### ISSUE TITLE
Tihocan closed door blocks shimmy 

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1063]
![](https://media.discordapp.net/attachments/1075372522377322516/1169756552467583067/2023-11-02_22-52-10.mp4)

Sadly video embed doesn't seem to work: https://media.discordapp.net/attachments/1075372522377322516/1169756552467583067/2023-11-02_22-52-10.mp4

@lahm86 Maybe you already saw this being addressed on Discord, but if not, dash explained that the closed door acts like an invisible wall: https://discord.com/channels/1071085441077481544/1075372522377322516/1169984124694577242

I recently came across this shimmy situation in a playthrough, and thought I had lost progress because I hadn't saved in a while. Thankfully then remembered you can land on the left (if you have enough health after the two gorillas in this area).

Do you think there would be a good way to improve this and allow the player to stand in front of the door? I reckon that way they might even look through the door and spot the key inside the room as an indicator for level progression.

Thanks for any thoughts.

**Comment by lahm86** [comment]
Good find. Yes, this should be an easy data fix 👍
