### ISSUE TITLE
Implement PS1 save crystal model and texture

### ISSUE THREAD

**Issue by VGMFR** [LostArtefacts/TRX#1069]
Having the option to play with the PS1 crystal is one of the best options in my humble opinion, a dream that became true.

However, here is how crystals look on PS1:

![image](https://github.com/LostArtefacts/TR1X/assets/12150692/db2bf232-692f-46f6-ade2-41aa8e4721de)

A beautiful blue with a nice reflection effect.

Here is how they currently look on TRX:
![image](https://github.com/LostArtefacts/TR1X/assets/12150692/11f67b9f-f955-4155-8d6f-c8c39ef811c3)
![image](https://github.com/LostArtefacts/TR1X/assets/12150692/4593b971-9d9d-4d29-a135-2b192567bc7c)

Note quite as beautiful. So it would be incredible to have the original model back, if possible with reflection. But for reflection another issue already exists: https://github.com/LostArtefacts/TR1X/issues/154
I also found this source of information regarding the subject:
https://www.tombraiderforums.com/showthread.php?t=226585

**Comment by tommapar97** [comment]
A note that could help for future reference when reviewing this. 

Apparently the reflections on the crystal- as well as the rolling blades in the first level of TR2 where the output of one of PS1's buffers that just was the the output of THE SCREEN ITSELF, on real time, on a pixel basis, then projected onto the UV of the crystal, and then it was just multiplied by a shade of blue, while for the rolling blade it was just inverted IIRC. 

It's literally the simplest SSR technique available. My 2 cents as a game designer, and from what OpenLara did: adding a glue blow (blue glow) to it would be also nice, adding point lights would make them easier to see and no one would complain. PS1 era coloured lighting is amazing. Just look at how big a change it made when switching from TR2 to TR3.

**Comment by walkawayy** [comment]
Yes we would love to implement this reflection effect hence the issue already existing. I think unfortunately at the moment, none of the devs have a good 3D graphics background to implement it. We welcome contributions if anyone is able to help!

**Comment by VGMFR** [comment]
Yes I noticed the open issue regarding reflection (and linked it in the original message as well), but this issue was more to restore the blue color / texture of the original crystal, which can be done independently from reflection, as well as the 3D model if it's not exactly the same (look quite similar thought, but I did not push the comparison further).

To be more precise, the color for the original save crystal is [#4040FF](https://color-hex.com/color/4040FF) according to the thread linked above, when the current one in TR1X seems to be [#93adac](https://www.color-hex.com/color/93adac).

For the 3D model, more comparisons and possibly investigation would be needed, but it is less noticeable than the color anyway.

**Comment by VGMFR** [comment]
Quick update for this issue if anyone else was wondering: the crystal color of TR1X seems in fact to be the one of the Saturn version of TR1, a version that released before it was finished. So it could maybe be nice for some people to have the option to chose the Saturn crystals color [#93adac](https://www.color-hex.com/color/93adac)) or the PS1 crystal color ([#4040FF](https://color-hex.com/color/4040FF)), but not to replace the Saturn by the PS1 (even if PS1 really looks better in my humble opinion :')).

**Comment by pas-de-2** [comment]
I was messing around with Sabatu's TR1 wads + textures pack in Tomb Editor and noticed he has a pretty nice looking save crystal, could maybe inject something like this as a stopgap:

![20231220_224149_Caves](https://github.com/LostArtefacts/TR1X/assets/116680301/711a9c66-c89e-44d5-8d50-641f6f209cf8)

**Comment by pas-de-2** [comment]
I was messing around with Sabatu's TR1 wads + textures pack in Tomb Editor and noticed he has a pretty nice looking save crystal, could maybe inject something like this as a stopgap:

![20231220_224149_Caves](https://github.com/LostArtefacts/TR1X/assets/116680301/40d8bd3f-7222-46b1-b66c-33db5cb60794)

**Comment by VGMFR** [comment]
> I was messing around with Sabatu's TR1 wads + textures pack in Tomb Editor and noticed he has a pretty nice looking save crystal, could maybe inject something like this as a stopgap:
> 
> ![20231220_224149_Caves](https://private-user-images.githubusercontent.com/116680301/292089243-40d8bd3f-7222-46b1-b66c-33db5cb60794.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjUwNzQsIm5iZiI6MTcwMzI2NDc3NCwicGF0aCI6Ii8xMTY2ODAzMDEvMjkyMDg5MjQzLTQwZDhiZDNmLTcyMjItNDZiMS1iNjZjLTMzZGI1Y2I2MDc5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQxNzA2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGRhNTI4MGE2NWU2MWJjYmQ4N2I3NDBiYmY3NjJkY2UyZTgxNTFjYzc2MTlmMGI0ZTFiMzE2M2ExNmMzMTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xDt6RCgVdoBlUqaQQiPO1bmtN99vwboTHqp3mZhNP3w)

Very nice indeed! Very close to the original PS1 one.

**Comment by rr-** [comment]
Thanks for the comments. This will be tackled as part of #154 efforts.
