### ISSUE TITLE
Lara's push block grunt no longer changing

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1070]
First seen on the new v3.0:

https://github.com/LostArtefacts/TR1X/assets/4934209/f274b3a4-6720-4d11-bcf8-c5094914df7a

**Comment by rr-** [comment]
@Richard-L are you sure it's not just a giant coincidence? I can't really reproduce this

**Comment by Richard-L** [comment]
I can try again, but I doubt it. Even before I recorded it was always just these two sound samples, which made me suspicious.

Hadn't something about blocks been renamed internally recently?

Otherwise is there anything about my user settings that could inflict this?

**Comment by Richard-L** [comment]
Could try again now and loaded the save, and the problem is gone. So strange?

**Comment by aredfan** [comment]
@Richard-L try opening and closing the inventory before pushing/pulling the block.  I suspect this is the trigger for the bug as well as the one in #1074.

**Comment by walkawayy** [comment]
> @Richard-L try opening and closing the inventory before pushing/pulling the block. I suspect this is the trigger for the bug as well as the one in #1074.

Yep same cause I confirmed.

**Comment by Richard-L** [comment]
Thanks guys, thought I was going crazy for a second hah
