### ISSUE TITLE
Waterfall Splash effect not playing, remains static (TR1X 3.0)

### ISSUE THREAD

**Issue by annlyt** [LostArtefacts/TRX#1074]
I am playing Sabatu's TR1 with TR1X 3.0 (transferred level strings over myself), and noticed an issue with the waterfall splash effect texture remaining frozen and not playing as it should: 

Video:
https://github.com/LostArtefacts/TR1X/assets/13076939/7c75de65-215d-4851-ab6c-e52c7bb77389

**Comment by aredfan** [comment]
~~This seem to happen when `Save additional game information` is disabled.~~

**Update:** Ah I got it wrong, it happens regardless of the setting.

https://github.com/LostArtefacts/TR1X/assets/94776985/64afa14a-49da-4855-96c0-31cd953f4899

**Update 2:** Bubbles and lightning are also affected.
