### ISSUE TITLE
Death counter statistics never displays on the first level you play

### ISSUE THREAD

**Issue by VGMFR** [LostArtefacts/TRX#1077]
I noticed that death counter statistics is not working properly. Actually it seems to work only after finishing one level, and never in the first level you play.

Reproduction:

Activate death counter statistics in the options:
![image](https://github.com/LostArtefacts/TR1X/assets/12150692/009fdc4f-63f3-4a5a-aedc-6af437faab25)

Then launch the game and load any level, then check your compass: no death counter is displayed.
![image](https://github.com/LostArtefacts/TR1X/assets/12150692/55133bd8-5734-4a50-a91f-a871c989fbfe)

Same when you finish the level, in the level stats. However, after finishing this first level, the next one you will play (for example Vilcabamba if you finished the caves) will have the proper death count stats.

**Comment by walkawayy** [comment]
It seems to be working for me? New Game Caves:

![image](https://github.com/LostArtefacts/TR1X/assets/81546780/51f35fbf-b2a7-47fd-8036-56c4e998d5a9)

**Comment by VGMFR** [comment]
So I just checked, and "new game" indeed works. Then if you load any level it will work too. But if you just launch the game and load a save, then it won't.
If needed I can provide my config and saves but I doubt it will be related.

**Comment by walkawayy** [comment]
> So I just checked, and "new game" indeed works. Then if you load any level it will work too. But if you just launch the game and load a save, then it won't. If needed I can provide my config and saves but I doubt it will be related.

I still can't reproduce this. Are you trying to load a legacy save? That's the only case a save won't have the death counter from what I can tell. Can you use the right arrow key on the save in question and see if you can select a level or if the game says that it's a legacy save?

![image](https://github.com/LostArtefacts/TR1X/assets/81546780/f1394853-dc04-43d3-bab3-7808655f0eec)

**Comment by VGMFR** [comment]
Strange. I just check and I have the levels selection.

Please find attached a full zip of my folder, therefore including saves as well as configuration, in case it is configuration-related for whatever reason.
https://drive.google.com/file/d/1b1j62TLuT-b0cxd88k8LTaJuttaZ_J36/view?usp=sharing
You can just launch the game and load the last save (The Great Pyramid) to notice the issue. Will work with any other save too though.

Worth noting these saves were all made with the crystal save option activated, if this could be related in any way?
(The option is currently disabled because I'm playing UB now, but I played the whole original game with the option activated)

Also worth noting that only the display is missing, on the final stats screen after game completion, the death count seemed rather correct.

Finally worth noting that I'm playing on [Release 2.16](https://github.com/LostArtefacts/TR1X/releases/tag/2.16). I started to play with this version so the saves come from this version. I did not try it with the recent 3.0 but I did not see any related issue in the patch note either.

**Comment by walkawayy** [comment]
Thanks for the upload. I tried your folder and did notice the death counter not appearing. However, when I use that same save with the latest version 3.0.3, the death counter appears as normal in the compass. So, I think this bug can be considered solved. Luckily it still works out fine for your final stats.

**Comment by walkawayy** [comment]
Is this ok to close @VGMFR ?

**Comment by VGMFR** [comment]
Thank you for your answer. I did not get the time to upgrade and test with 3.0.3 since last week, but I'll do it this week for sure and I'll keep you updated on the result, just to be sure!
(For the record it did not work for my final stats for UB so I was wrong for final stats too, it just worked for the main game because I did the 2 last levels in a row, now that I remember).

**Comment by VGMFR** [comment]
Alright just updated to latest 3.0.5 and it is fixed for both the main game and UB, as well as for final stats. Nice! I'll close the issue.
