### ISSUE TITLE
TR1X bug: faulty underwater effects

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#1081]
On the left is TR1X 3.0.2, and on the right is Tomb1Main 2.16. This is another side effect of `Random_GetDraw` not progressing the RNG.

https://github.com/LostArtefacts/TR1X/assets/33758420/f3c687a3-46fe-4114-9635-02d26eeb3fe0

**Comment by Richard-L** [comment]
Oh nice Lahm. Was confused why the caustics felt faster again.

**Comment by lahm86** [comment]
> Oh nice Lahm. Was confused why the caustics felt faster again.

Yes, I figured my eyes were just playing tricks on me until I gave it a bit more thought.
