### ISSUE TITLE
Language switch option possible?

### ISSUE THREAD

**Issue by StenApp** [LostArtefacts/TRX#1083]
Is there an option to switch the language of the game to e.g. German?

**Comment by Richard-L** [comment]
I don't think so. But there are issues related to localisations, eg subtitles, dubs, etc.

**Comment by StenApp** [comment]
I see,

if i change strings in
cfg\TR1X_gameflow.json5 or
cfg\TR1X_gameflow_ub.json5
Menu is translateable.

**Comment by StenApp** [comment]
Closed as duplicate of https://github.com/LostArtefacts/TR1X/issues/715
