### ISSUE TITLE
Water effects look odd

### ISSUE THREAD

**Issue by Switch123456789** [LostArtefacts/TRX#1084]
I checked all settings but the underwater effects look odd for me. Are they supposed to look like that? [drive.google.com](https://drive.google.com/file/d/1GW5JIOrSoU1bqBn522Mn0UV_Z8WsLt0I)

**Comment by lahm86** [comment]
Yes, this is being handled under #1081.

**Comment by Switch123456789** [comment]
I searched for "water" and couldn't find anything 🙈 my apologies.

**Comment by lahm86** [comment]
> I searched for "water" and couldn't find anything 🙈 my apologies.

It's not a problem, thank you for raising the issue. It's odd that GitHub doesn't match "water" with "underwater" :smile: The fix is in place, so will be in the next release 👍
