### ISSUE TITLE
TR1X bug: command to give shotgun shells adds a shotgun instead

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1096]
The developer console's command `give shotgun shells` adds a shotgun instead.

This bug can be reproduced when starting a New Game, or starting Natla's Mines.

**Comment by walkawayy** [comment]
Looks like only `shotgun ammo` or `sg ammo` are supported right now. We should add `shotgun shell(s)` and `sg shell(s)` since that is their official name in the inventory and `clip(s)` are supported for the other guns.
