### ISSUE TITLE
TR1X Bug: Lara's push animation can break 

### ISSUE THREAD

**Issue by Oplexitie** [LostArtefacts/TRX#1101]
**Build :**
Release 3.0.3

**Description :**
In the latest release, you can break Lara's pushing animation by interacting with pushable blocks in a specific way, allowing Lara to freely walk around while the block moves forward on its own. This can lead to other issues as seen in the video.

https://github.com/LostArtefacts/TR1X/assets/72892666/c21d974c-858d-40ea-b7d6-4a7d05c8b472

I've only tried this in City of Vilcabamba 2, so I'm only guessing that this can happen with any pushable block.
I'm also guessing this is a TR1X Bug, since I couldn't find any info about it online.

**Steps to replicate :**
1- Get in front of a pushable block.
2- Grab and let go of it while trying to move forward. If you don't clip through the block, then repeat this step.
3- And voilà.

**Comment by aredfan** [comment]
This is not an easy bug to reproduce. In my case I was able make it happen by quickly and repeatedly tapping action, immediately followed by holding down forward.

**Comment by Oplexitie** [comment]
Just tried it, and yeah, you can trigger the bug way more consistently by doing it like that.

**Comment by walkawayy** [comment]
@aredfan do you know if this is a TR1X or OG bug? I am assuming TR1X bug.

**Comment by aredfan** [comment]
@walkawayy yes it's a TR1X bug.  I can't reproduce the same bug on TombATI.

**Comment by lahm86** [comment]
Just adding this for reference - as long as you're holding action and forwards/backwards during the "release" animation, the bug will occur.

https://github.com/LostArtefacts/TR1X/assets/33758420/57b3e17b-cb18-43c6-a97e-aa0e0bec362d
