### ISSUE TITLE
Save crystal mode and Unfinished Business

### ISSUE THREAD

**Issue by pas-de-2** [LostArtefacts/TRX#1102]
Ran into a couple issues:

- Unfinished Business doesn't have save crystals, so it doesn't really make sense for the config option to prevent saving when launching the game with `-gold`.

- This led me to try disabling `enable_save_crystals` and only enabling `force_enable_save_crystals` in `TR1X_gameflow.json5`. Problem with this method is that `force_enable_save_crystals` actually overwrites your config's `enable_save_crystals` value, so if you play base TR and then later launch UB, save crystal mode will be enabled again.

I suppose another possibility would be to import the save crystal locations from b122251's PSX port of UB.

**Comment by walkawayy** [comment]
The gameflow option `force_enable_save_crystals` is meant for custom level gameflows so the creator can control whether they want their levels to be experienced with save crystals or not.

Yes, vanilla UB doesn't have save crystals. All you should need to do is uncheck save crystal mode in the config tool when you want to play it.

**Comment by pas-de-2** [comment]
Yes, but there's currently no way to maintain separate shortcuts to TR and UB without having to remember to go through the config tool every time and toggle on/off save crystals. If there was some command line option to control this variable, or if `enable_save_crystals` was ignored if the game was launched with `-gold`, or if the `force_enable_save_crystals` override didn't overwrite your actual config file, this wouldn't be a problem.
