### ISSUE TITLE
Additional controller binds for menu back and menu confirm

### ISSUE THREAD

**Issue by pas-de-2** [LostArtefacts/TRX#1104]
Currently, the only way to exit a menu like the passport or sound options with a gamepad is to press the Inventory button (Share on a DS4), which is strange and unintuitive. This might be a regression from 2.12, when custom keybinding support was added, since [previously](https://github.com/walkawayy/TR1X/blob/bc2bd9cb864e4b7374923abe796952c8f1cda0aa/src/specific/s_input.c#L569C19-L569C19
) you could press Roll or Start or Touchpad to exit menus as well.

Suggestion: make both the Roll and Weapon Draw buttons trigger `menu_back`, to cover people used to modern gamepad controls (where Roll/Circle = deselect) and people used to PlayStation TR2-5 controls (where Draw/Triangle = deselect).

**Comment by walkawayy** [comment]
Ya I hope this can be implemented. We have issue #692 for it, so I am going to close this and we can move discussion there.
