### ISSUE TITLE
OG bug: flames are not always drawn when Lara is on fire

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#1106]
If Lara catches fire and then enters a room other than the one where the flames originated, the flames are no longer drawn. They re-appear if she enters the original room, or when she is simply facing that room. Ultimately, the flame FX remain tied to the original room so are only drawn when that room is drawn.

https://github.com/LostArtefacts/TR1X/assets/33758420/92293928-02b2-4bb4-bb14-0cf40340c216

**Comment by aredfan** [comment]
Nice find!  Interestingly on TombATI, when Lara enters a different room while on fire, the game crashes.
