### ISSUE TITLE
Feature request/Enhancement: Have a way to control FMV volume.

### ISSUE THREAD

**Issue by Oplexitie** [LostArtefacts/TRX#1110]
Currently, in TR1X there is no way to control the volume for FMV cutscenes, and the game defaults to playing the FMV volume at SDL_MIX_MAXVOLUME. Which isn't ideal.

---

**Possible solutions:**

- Tie the FMV audio to one the pre-existing sliders (this is what I personally did in my build of the game).
- Create a new volume slider specifically for FMV's.

**Comment by rr-** [comment]
>Tie the FMV audio to one the pre-existing sliders (this is what I personally did in my build of the game).

Can you please share the patch?

**Comment by Oplexitie** [comment]
Sure thing ! I'll make a pull request in a bit.
