### ISSUE TITLE
Hide the scion's blood effect

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1121]
Initially discussed on discord.  Hiding the scion's blood effect could perhaps be done as part of the  `Fix texture issues` option.

![1](https://github.com/LostArtefacts/TR1X/assets/94776985/0b04c0c7-8636-4bdb-b96f-33fbae07b7ce)

**Comment by walkawayy** [comment]
Should we just add a `spawn_blood` bool argument or something to `Gun_HitTarget`? @rr-

**Comment by rr-** [comment]
I'd rather check if the target is a scion object and spawn a ricochet instead.
