### ISSUE TITLE
Spanish config tool has wrong field name for skipping Eidos logo

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#1151]
```
    "enable_eidos": {
      "Title": "Habilitar el logo de EIDOS",
      "Description": "Habilita el logo de EIDOS al comienzo del juego."
    },
```

should be

    "enable_eidos_logo": {
      "Title": "Habilitar el logo de EIDOS",
      "Description": "Habilita el logo de EIDOS al comienzo del juego."
    },

**Comment by ajtudela** [comment]
> ```
>     "enable_eidos": {
>       "Title": "Habilitar el logo de EIDOS",
>       "Description": "Habilita el logo de EIDOS al comienzo del juego."
>     },
> ```
> 
> should be
> 
>     "enable_eidos_logo": {
>       "Title": "Habilitar el logo de EIDOS",
>       "Description": "Habilita el logo de EIDOS al comienzo del juego."
>     },

On it!
