### ISSUE TITLE
TR1X.pdb

### ISSUE THREAD

**Issue by sunbeam906** [LostArtefacts/TRX#1159]
Hi Marcin. Could you kindly share a matching pair of TR1X.exe and TR1X.pdb? I require it for live debugging. Thanks! --Dan

**Comment by rr-** [comment]
We currently do not offer official support for Visual Studio. Our toolchain is based on MinGW, and it appears that creating .pdb files may not be straightforward with this setup: https://stackoverflow.com/a/28627790. I recommend giving it a try to create debug builds on your own with the official Docker builds – especially considering that our official releases are optimized and may not contain all the symbol data.
