### ISSUE TITLE
Feature request: Allow ambience and music tracks to play at the same time

### ISSUE THREAD

**Issue by rondeeno** [LostArtefacts/TRX#1161]
Similar to #17 and #762, it would be nice if background ambience would continue to play when music is triggered, rather than being abruptly cut off until the music finishes.

**Comment by Richard-L** [comment]
I recall this had been the case in Croftengine before, more or less by accident afaik, and it sounded very weird. Think of the alligator noises in a level like cistern, with music playing on top of it. It was then changed back to OG behaviour (only one track playing at a time).

I would advise against this.

**Comment by rr-** [comment]
I think posix has a valid point about this feature being too out of the ordinary for now. As a result, I don't believe we should support it. I'm closing this, but we can revisit if there's more interest (for example from level builders).
