### ISSUE TITLE
Ammo stucked inside the walls

### ISSUE THREAD

**Issue by NaBu1908** [LostArtefacts/TRX#1169]
I am surprised that nobody has mention that already but there are ammo pick-ups that are placed inside the wall by the original game developers and it's not fixed, while the bat enemy in Colloseum has been fixed. At least ammo in Atlantis wall is well known issue among the community since years. 

- Atlantis (uzi clip) inside the walls
- Temple of the Cat (TR1 Gold, 2nd level) inside the walls parrarel to secret nr 1,
![image](https://github.com/LostArtefacts/TR1X/assets/113198520/b2668fb5-64ed-4474-90a6-2730b51ffa2e)
 magnums clips

**Comment by walkawayy** [comment]
Hi! We actually subtract unobtainable pickups from the level counts. For example, Atlantis has 3 pickups in the level we mark [here](https://github.com/LostArtefacts/TR1X/blob/4a79f0efb6af674dbf78e82fa79eb7eca380c5c8/bin/cfg/TR1X_gameflow.json5#L398). And for Temple of the Cat [here](https://github.com/LostArtefacts/TR1X/blob/4a79f0efb6af674dbf78e82fa79eb7eca380c5c8/bin/cfg/TR1X_gameflow_ub.json5#L66). We do the same for some of the kills in UB. They are technically still in the level and can be picked up with cheats, but they don't count against total level stats.
