### ISSUE TITLE
Fixed-camera shift in 60fps mode

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1186]
In some fixed-camera positions, there's a subtle shift in the first 2 frames that isn't present in 30fps mode.

I'd suggest opening these screenshots in separate tabs to help compare them better.

**Tomb of Qualopec (trigger, room 23):**

![1 1](https://github.com/LostArtefacts/TR1X/assets/94776985/dd5ca12c-e7b0-4746-91cd-a1516cee0633)
![1 2](https://github.com/LostArtefacts/TR1X/assets/94776985/16b7e2d1-1997-45bd-940c-62393ca69fca)

**Tomb of Qualopec (switch, room 28):**

This camera shift occurs when the door is opening but not when it's closing.

![2 1](https://github.com/LostArtefacts/TR1X/assets/94776985/1eafb015-fc0f-4808-99a3-aae767391eae)
![2 2](https://github.com/LostArtefacts/TR1X/assets/94776985/3f2cfcbc-1919-4af3-873d-f69151392e8e)

**Colosseum (switch, room 52):**

Opening:
![3 1](https://github.com/LostArtefacts/TR1X/assets/94776985/9af43e2c-55bd-4b2d-a449-f5ddadf77373)
![3 2](https://github.com/LostArtefacts/TR1X/assets/94776985/3513a3f6-1c43-4ca9-9741-788d49e22a8f)

Closing:
![3 3](https://github.com/LostArtefacts/TR1X/assets/94776985/9b40d940-ed45-447d-8a05-8cbacb584491)
![3 4](https://github.com/LostArtefacts/TR1X/assets/94776985/769228b4-b164-42eb-9955-26dd024e7fcb)

**Comment by rr-** [comment]
I don't think it's possible for us to fix it given the nature of the implementation where we lag behind by one frame every other frame and interpolate the woul-be game state. Please correct me if I'm mistaken.

**Comment by aredfan** [comment]
@rr- should I reopen this issue because it has 3.2 milestone attached to it?

**Comment by rr-** [comment]
No, I added it by mistake.
