### ISSUE TITLE
Height issue with some 3D pickups

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1189]
**Left is 3.1.1 | Right is 60FPS_v2**

![1](https://github.com/LostArtefacts/TR1X/assets/94776985/43bac4c3-7901-4643-9204-83b033e307cb)
![2](https://github.com/LostArtefacts/TR1X/assets/94776985/a8ebab6c-c6ea-4a75-a525-4d83492f0737)
![3](https://github.com/LostArtefacts/TR1X/assets/94776985/632ebdaf-4a0f-4612-8098-c4f6f8340523)
![4](https://github.com/LostArtefacts/TR1X/assets/94776985/9d22de1a-5ad9-44d9-ac84-5be81a337ef4)

**Update:**
![5](https://github.com/LostArtefacts/TR1X/assets/94776985/609d4f3f-0592-40c8-ab07-6f4b5ab1d237)

#1177

**Comment by rr-** [comment]
Should be fixed in the newest 60 fps branch.
https://nebula.wind.garden/serve/pub/TR1X%203.1.1-88-gd227490-Windows.zip

**Comment by aredfan** [comment]
I've confirmed the pickup height issue is fixed in all 5 instances.  Thank you. 👍
