### ISSUE TITLE
Roll animation flickers in 60 FPS

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#1193]
Video recorded at 480p so it was small enough to upload.
https://github.com/LostArtefacts/TR1X/assets/81546780/d06ab1ee-1608-4ac3-88eb-f67229a68cc3

#1177

**Comment by rr-** [comment]
Specifically there's a single frame which renders Lara at an angle that seems to be off by 90° in the XZ plane:

![shot-issue mp4-00:00:01 250](https://github.com/LostArtefacts/TR1X/assets/1045476/7ed2af39-34c5-4852-9d9d-aedaa672ce7a)

**Comment by rr-** [comment]
Should be fixed here: https://nebula.wind.garden/serve/pub/TR1X%203.1.1-89-g0109dd8-Windows.zip

**Comment by walkawayy** [comment]
Seems fixed to me. @aredfan @Richard-L

**Comment by Richard-L** [comment]
It looked good to me too! It's still quite surreal to see this animation in 60fps, so I didn't feel confident enough to comment.
