### ISSUE TITLE
Inventory exit black fade-out slightly faster on 60fps

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1200]
It seemed more when I first tried 60fps, but it's really not by much, borderline negligible. Fwiw I did notice it:

After these frames respectively is when the black fade is gone.

30fps:
![2024-03-26 22-46-49 mp4_20240326_225145 002](https://github.com/LostArtefacts/TR1X/assets/4934209/4dc0742c-d402-4264-bc12-eddedcc7b9fe)

60fps
![2024-03-26 22-46-26 mp4_20240326_225146 554](https://github.com/LostArtefacts/TR1X/assets/4934209/6506f721-fc26-449f-9301-b35f11f8828a)

**Comment by rr-** [comment]
Merging with #1202 as the fix is going to be the same
