### ISSUE TITLE
Fades are twice as fast in 60FPS

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1202]
#1177 

I noticed that fades are faster in 60 FPS when comparing to 30FPS for the following:

- Edios (you may have to compare this with 3.1.1)
- Main Menu
- Exit to Title
- End of level stats
- Loading screens
- Credits

It seems the fades are always fast when starting Lara's Home and the subsequent loading screen, regardless of 30/60 fps settings.

**Comment by Richard-L** [comment]
Was just about to post this :)

Latest release:

https://github.com/LostArtefacts/TR1X/assets/4934209/67987f8b-8f5d-4406-8a31-279f29ec0650

60fps:

https://github.com/LostArtefacts/TR1X/assets/4934209/62c6ad89-5640-494c-a114-690c2c6a2465

**Comment by rr-** [comment]
Can you check if this is working? https://nebula.wind.garden/serve/pub/TR1X%203.1.1-90-g2d86519-Windows.zip

I don't have the means to compare side-by-side, but the end of level stats screen looked fishy in this build.

**Comment by rr-** [comment]
Another report on fades from posix (#1200):

> It seemed more when I first tried 60fps, but it's really not by much, borderline negligible. Fwiw I did notice it:
> 
> After these frames respectively is when the black fade is gone.
> 
> 30fps: ![2024-03-26 22-46-49 mp4_20240326_225145 002](https://private-user-images.githubusercontent.com/4934209/317052140-4dc0742c-d402-4264-bc12-eddedcc7b9fe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0OTM1MzksIm5iZiI6MTcxMTQ5MzIzOSwicGF0aCI6Ii80OTM0MjA5LzMxNzA1MjE0MC00ZGMwNzQyYy1kNDAyLTQyNjQtYmMxMi1lZGRlZGNjN2I5ZmUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMjI0NzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVlNTk3ODU3NGI1MjFkNzdjMjNlMDNjMWUwOTdkZDMwMjAwZmEyMzcwZjgzODU1YzZlM2QzMjQxYWM5NzQ5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OfKg5QrJwaF9fCCJYukbYHyTZ8B3uz_KUqxOt4o1ILE)
> 
> 60fps ![2024-03-26 22-46-26 mp4_20240326_225146 554](https://private-user-images.githubusercontent.com/4934209/317052165-6506f721-fc26-449f-9301-b35f11f8828a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0OTM1MzksIm5iZiI6MTcxMTQ5MzIzOSwicGF0aCI6Ii80OTM0MjA5LzMxNzA1MjE2NS02NTA2ZjcyMS1mYzI2LTQ0OWYtOTMwMS1iMzVmMTFmODgyOGEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMjI0NzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmJjYTljYTU0YzMzZTFmZmJlMWUxNmIxOTA2YWM3Zjg4NzBiYTBmOWM3YzU5OGViNWVjODY3YzY1N2JjZGJlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ww9fr5OSviz_c3pGpGGTOUVvwnVIR_K0vjqlGtUW334)

**Comment by aredfan** [comment]
**Testing:**

- Edios - LGTM
- End of level stats - LGTM
- Main Menu - Fade-in missing
- There's a flicker when transitioning between credit screens.
- There's a flicker when transitioning between Main Menu and Loading Screens
- Exit to Title - Can't be sure without the Main Menu fade-in getting fixed first.

**Edit:** Animated textures seem to be broken in this build.

**Edit 2:** The Main Menu fade-out is still fast, and subsequent loading screens fade-out fast as-well when loading from the Main Menu.  But loading screen fade-out seem normal when transitioning between levels.

(I'll double check all of these tomorrow.)

**Comment by aredfan** [comment]
The "flicker" I was referring to when transitioning from Main Menu to Loading Screen, and transitioning between credit images.

**Frame 1:**
![Frame 1](https://github.com/LostArtefacts/TR1X/assets/94776985/f52a27d0-d1f1-40d1-9170-be4d548d57ee)
**Frame 2:**
![Frame 2](https://github.com/LostArtefacts/TR1X/assets/94776985/2892023e-bd57-46aa-bfbe-beda59ca538c)
**Frame 3:**
![Frame 3](https://github.com/LostArtefacts/TR1X/assets/94776985/c794663f-5d7d-434e-90b7-04aa28bea118)

**Comment by rr-** [comment]
@aredfan can you please check this build?
https://nebula.wind.garden/serve/pub/TR1X%203.1.1-94-g6c66170-Windows.zip

**Comment by aredfan** [comment]
The flicker between graphic images is gone. 👍 

**Testing 60 FPS:**

- Edios - LGTM
- Main Menu - LGTM
- Exit to Title - LGTM
- End of level stats - LGTM 
- Loading Screens - LGTM for the most part.  Loading screens that appear after the Main Menu still have faster fades.
- Credits - LGTM

**Testing 30 FPS:**

- Edios - LGTM
- Main Menu - LGTM
- Exit to Title - LGTM
- End of level stats - LGTM
- Loading Screens - LGTM for the most part.  Loading screens that appear after the Main Menu still have faster fades.
- Credits - LGTM

Although I'm mostly relying on my memory and eyes, I could do with help from a fresh pair of eyes @Richard-L and @walkawayy

**Comment by rr-** [comment]
Newest build - https://nebula.wind.garden/serve/pub/TR1X%203.1.1-100-g68e9f6c-Windows.zip

but unfortunately since the bug was significant, it requires re-testing of all of the above.

**Comment by aredfan** [comment]
**Testing 60 FPS:**

- Edios - LGTM
- Main Menu - LGTM
- Exit to Title - **Fades too fast to black**
- End of level stats - LGTM
- Loading Screens - LGTM
- Credits -LGTM

**Testing 30 FPS:**

- Edios - **There's a flicker between the Edios and Main Menu screens.  See images 1-3.**
- Main Menu -LGTM
- Exit to Title - **Fades too fast to black**
- End of level stats - LGTM
- Loading Screens - LGTM
- Credits - **There's a flicker between some credit screens but it's very subtle.  See images 4-6**

__________________

**Frame 1:**
![1 1](https://github.com/LostArtefacts/TR1X/assets/94776985/359985f9-7e30-4e16-a121-de20f58a3e43)
**Frames 2-3:**
![1 2](https://github.com/LostArtefacts/TR1X/assets/94776985/826e41d1-65b1-4382-830c-3ed900c01310)
**Frame 4:**
![1 3](https://github.com/LostArtefacts/TR1X/assets/94776985/83121e11-1d5b-4377-a3dc-3d2822bdfdb3)

____________________

**Frame 1:**
![2 1](https://github.com/LostArtefacts/TR1X/assets/94776985/7e91e923-ef89-4355-914d-f44f39ead15f)
**Frames 2-3:**
![2 2](https://github.com/LostArtefacts/TR1X/assets/94776985/e55f073d-b6b9-420d-a1ed-96da2b1d05fa)
**Frame 4:**
![2 3](https://github.com/LostArtefacts/TR1X/assets/94776985/7343e74c-10ab-49d8-9c7c-de4da84aef01)

**Comment by rr-** [comment]
@aredfan the last two issues should be now fixed:
https://nebula.wind.garden/serve/pub/TR1X%203.1.1-102-g8b94d76-Windows.zip

**Comment by aredfan** [comment]
@rr- I tested this build and both remaining issues are resolved.  Thank you and well done. 👍
