### ISSUE TITLE
New loading screens are only recorded/streamed during fades in 60fps

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1203]
https://github.com/LostArtefacts/TR1X/assets/4934209/ae5ede02-d756-496f-926d-23b59366dcd5

**Comment by rr-** [comment]
Can you check develop?
I think it's the same as #1199 and has to do with your streaming setup. Could you please try fiddling with your GPU settings to see if this helps with anything?

**Comment by Richard-L** [comment]
Okay I noticed the issue only occurs with this setting:

![image](https://github.com/LostArtefacts/TR1X/assets/4934209/183958ec-0d3d-42f6-967c-1086a9b6efa5)

When it's set to "framebuffer" it works fine.

It is indeed the same issue like you say.

**Comment by rr-** [comment]
Closing with the intention to merge this with #1199 – please leave a comment or edit the initial comment there with this new observation. Thanks
