### ISSUE TITLE
Demo exit misses black fade-in

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1205]
This is unrelated to the 60fps build. It also happens in the latest release.

TR1X

https://github.com/LostArtefacts/TR1X/assets/4934209/bd481f7d-487e-4e88-bf4e-28107b4daf2b

PS1

https://github.com/LostArtefacts/TR1X/assets/4934209/045d66ec-0ff8-43d0-8436-a1d63252b9a7

Any chance this would be a regression of one of more recent releases? I don't recall the fade missing in TR1X here.

**Comment by Richard-L** [comment]
Seeing the videos side by side, did TR1X never have a "DEMO MODE" indicator and blinking "Press any button to exit"? 🤔

**Comment by rr-** [comment]
DEMO MODE text seems to be gone in the 60 FPS branch. Let's split this into two tickets.
