### ISSUE TITLE
DEMO MODE text missing in 60fps build

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1207]
As mentioned here https://github.com/LostArtefacts/TR1X/issues/1205#issuecomment-2021608688

Did TR1X also have the blinking "Press any button to exit"? Struggling to remember.

**Comment by rr-** [comment]
@aredfan can you confirm if this is working in the latest develop? Thanks

**Comment by aredfan** [comment]
@rr-  Tested on 30/60 FPS.  LGTM.
