### ISSUE TITLE
Stone centaur issue for 30/60 FPS

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1209]
#1177

**Tomb of Tihocan, room 90:**

- When playing 30FPS, the stone centaur pose in incorrect.
- When playing in 60FPS, the stone centaur is in two poses at once.

**3.1.1:**
![3 1 1](https://github.com/LostArtefacts/TR1X/assets/94776985/fc437dbd-04e6-4a6d-9d9f-3ead53b0ca41)
**30FPS:**
![30FPS](https://github.com/LostArtefacts/TR1X/assets/94776985/ca8ce57a-5629-49a0-b080-911d34a27989)
**60FPS: (but you see 2 poses at once, I'm unable to take a screenshot of this)**
![60FPS](https://github.com/LostArtefacts/TR1X/assets/94776985/95dee10f-2a41-4f92-893f-75c8a7bbef57)

**Comment by rr-** [comment]
I'm pretty sure the cause is the same as in #1197.

**Comment by aredfan** [comment]
@rr- I tested this build: https://nebula.wind.garden/serve/pub/TR1X%203.1.1-98-g1bc8115-Windows.zip

LGTM for this issue and #1197.
