### ISSUE TITLE
End of level stats - text doesn't disappear before fading out

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1211]
In 3.1.1, the end of level stats disappear before fading out.

In the Dev build, the stats remain onscreen during fade out.

![20240327_121559_City_of_Vilcabamba](https://github.com/LostArtefacts/TR1X/assets/94776985/074314dc-fc1c-459e-8f74-1be568fb9df0)

#1177

**Comment by walkawayy** [comment]
I think this looks fixed @aredfan

**Comment by aredfan** [comment]
@walkawayy doesn't look like it in this build: https://nebula.wind.garden/serve/pub/TR1X%203.1.1-105-g00e75d2-Windows.zip

I'm also okay with this just being a changelog entry that Dash suggested.
