### ISSUE TITLE
Cutscene 4 glitches when Lara grabs the scion - 60 FPS

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1212]
Atlantis, room 50.

The cutscene itself looks glitched in a similar way to #1197 and #1209.  

#1177

**Comment by rr-** [comment]
Hi, I can't quite reproduce this with the newest build (https://nebula.wind.garden/serve/pub/TR1X%203.1.1-102-g8b94d76-Windows.zip).

**Comment by rr-** [comment]
Should be fixed here:
https://nebula.wind.garden/serve/pub/TR1X%203.1.1-103-g45a5cf8-Windows.zip

**Comment by aredfan** [comment]
@rr- LGTM.
