### ISSUE TITLE
Qualopec boulder flicker

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1214]
After you pick up the Scion piece and make your way to the end of the level:

https://github.com/LostArtefacts/TR1X/assets/4934209/2a0e6804-388d-4e22-8d5f-1b0128041506

![image](https://github.com/LostArtefacts/TR1X/assets/4934209/04dff524-8b6f-4b9a-a791-caf3ac032af1)

**Comment by walkawayy** [comment]
Is it worth only interpolating active items? (this may be a super dumb idea lmao, idk how it's really working)

**Comment by rr-** [comment]
I'm already trying to avoid interpolating inactive items – but sometimes this fails. I'm not sure if the boulder here is even considered inactive – just like with Lara's twitching against the wall, it may just run an endless collision repositioning every frame.

**Comment by rr-** [comment]
OK this should be fixed here: https://nebula.wind.garden/serve/pub/TR1X%203.1.1-110-g3721734-Windows.zip
However it's an ugly fix.

**Comment by aredfan** [comment]
Tested in the boulder room in The Hive level.  LGTM 👍
