### ISSUE TITLE
Health/Air bars flashing twice as fast on 60 FPS

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1222]
The flashing happens when the Health/Air bars are 20% or below.

#1177

**Comment by rr-** [comment]
Good catch!

**Comment by rr-** [comment]
@aredfan latest 60 FPS build that should have this fixed: https://nebula.wind.garden/serve/pub/TR1X%203.1.1-105-g2b743ed-Windows.zip

**Comment by aredfan** [comment]
@rr- The Health/Air bars are now flashing normally in 30/60 FPS.  LGTM.
