### ISSUE TITLE
Loading Screens Fade-out hanging when Action+Direction pressed

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1228]
![image](https://github.com/LostArtefacts/TR1X/assets/4934209/02ac631c-1710-413c-9d0a-c1b818241d5f)

If you hold a direction and action whilst the loading screens fade out, you can make the fade out hang like this:

https://github.com/LostArtefacts/TR1X/assets/4934209/db4294d2-b9c6-46a2-bcfa-985bf96121af

EDIT: It can also be done by holding down action once the fade-out has set in.

**Comment by aredfan** [comment]
Fades skipping behaviour.  I'll create a separate issue for this if needed.

**3.1.1:**

- Edios - Fades can be skipped
- End of Level - **Fade-in is skippable.  Fade-out isn't skippable.**
- Credits - Fades can be skipped
- Final stats - **Fades cannot be skipped**

**Dev build:**

- Edios - Fades can be skipped
- End of Level - **Fades can be skipped**
- Credits - Fades can be skipped
- Final stats - **Fades can be skipped**

**Comment by rr-** [comment]
Fixed in latest develop.
