### ISSUE TITLE
Falling blocks fall at 30fps when in 60fps mode

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1229]
![image](https://github.com/LostArtefacts/TR1X/assets/4934209/c458a7e0-e4da-40d1-b973-4762afd9477c)

https://github.com/LostArtefacts/TR1X/assets/4934209/7120b9f1-e573-4b34-96fc-a32341556873

(Also can we note how amazing the Thor hammer looks now that you see more of it falling thanks to the 60fps 🙂)

**Comment by rr-** [comment]
Confirmed by @Richard-L that this is now working in the latest 60 FPS branch.
