### ISSUE TITLE
Music track is queued again on load despite having played in playthrough before

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1237]
[save_tr1_06.zip](https://github.com/LostArtefacts/TR1X/files/14817205/save_tr1_06.zip)

Happens in latest release v3.1.1 and recent develop builds.

I saved this just after picking up the Neptune key and having come out of the water. Upon load it repeats the "Calm I" (sometimes also called "Mysterious") track (03/57).

It should instead play the wind ambiance.

There's also a mild audio hitch at the very beginning upon load.

If it should at all be relevant - I remember Lahm (thankfully) edited the trigger for this track https://github.com/LostArtefacts/TR1X/issues/865

**Comment by walkawayy** [comment]
Was it an existing savegame? There was a change to music timestamps that's in the [Development snapshot](https://github.com/LostArtefacts/TR1X/releases/tag/latest) build. `changed the way music timestamps are internally handled – resets music position in existing saves`

**Comment by Richard-L** [comment]
No this was a new save game

**Comment by walkawayy** [comment]
@rr- this was definitely working in #1163. For even brand new saves, the music track restarts on every load game. Idk what's going on now. Every timestamp is getting saved as `-1.0` because `if (m_StreamSounds[sound_id].is_playing) {` is failing in `S_Audio_StreamGetTimestamp`. I can't figure out why it's happening though.

Example from St Francis Folly Neptune room:
```
../../src/game/music.c 78 Music_Play track: 3
../../src/specific/s_audio_stream.c 412 S_Audio_StreamSoundClose closing sound_id: 0
../../src/specific/s_audio_stream.c 290 S_Audio_StreamSoundClear stream->is_playing = false; 0
../../src/specific/s_audio_stream.c 250 S_Audio_StreamSoundInitialiseFromPath sound_id: 0, stream->is_playing = true; 1
../../src/game/music.c 98 Music_Play m_AudioStreamID: 0
../../src/game/phase/phase.c 53 Phase_SetUnconditionally 6
../../src/specific/s_audio_stream.c 552 S_Audio_StreamGetTimestamp sound_id: 0; is_playing: 0
../../src/game/music.c 245 Music_GetTimestamp Get 0 timestamp -1.000000
../../src/specific/s_audio_stream.c 552 S_Audio_StreamGetTimestamp sound_id: 0; is_playing: 0
../../src/config.c 200 Config_Write Saving user settings
```

**Comment by walkawayy** [comment]
Ah wait I figured it out! It only breaks if `Enable game sounds in inventory` is disabled.

`S_Audio_StreamSoundPause` sets `m_StreamSounds[sound_id].is_playing = false;` which is why `if (m_StreamSounds[sound_id].is_playing) {` is false in `S_Audio_StreamGetTimestamp`. I'm not sure how to fix that without breaking something else.

**Comment by rr-** [comment]
How about this?
```diff
diff --git a/src/specific/s_audio_stream.c b/src/specific/s_audio_stream.c
index 7281c54d..23a20a0c 100644
--- a/src/specific/s_audio_stream.c
+++ b/src/specific/s_audio_stream.c
@@ -540,18 +540,19 @@ double S_Audio_StreamGetTimestamp(int sound_id)
 {
     if (!g_AudioDeviceID || sound_id < 0
         || sound_id >= AUDIO_MAX_ACTIVE_STREAMS) {
-        return -1;
+        return -1.0;
     }
 
     if (m_StreamSounds[sound_id].is_playing) {
         SDL_LockAudioDevice(g_AudioDeviceID);
         AUDIO_STREAM_SOUND *stream = &m_StreamSounds[sound_id];
-        double timestamp = stream->timestamp;
+    }
+    const double timestamp = stream->timestamp;
+    if (m_StreamSounds[sound_id].is_playing) {
         SDL_UnlockAudioDevice(g_AudioDeviceID);
-        return timestamp;
     }
 
-    return -1.0;
+    return timestamp;
 }
 
 double S_Audio_StreamGetDuration(int sound_id)
```

**Comment by Richard-L** [comment]
Yup, I always mute any music in the inventory to mimic the PS1 version

**Comment by walkawayy** [comment]
> How about this?

I don't think that will work based on how you are checking the `stream`. In the timestamp assignment, the stream might not be playing, so `stream` doesn't exist outside of the first if check.

What about doing this? I tested it and it works. It doesn't have the nice `if_playing` check, but we can't rely on that if sounds are paused in the inventory. Instead checking the `duration` works.

```
double S_Audio_StreamGetTimestamp(int sound_id)
{
    if (!g_AudioDeviceID || sound_id < 0
        || sound_id >= AUDIO_MAX_ACTIVE_STREAMS) {
        return -1.0;
    }

    double timestamp = -1.0;
    AUDIO_STREAM_SOUND *stream = &m_StreamSounds[sound_id];

    if (stream->duration > 0.0) {
        SDL_LockAudioDevice(g_AudioDeviceID);
        timestamp = stream->timestamp;
        SDL_UnlockAudioDevice(g_AudioDeviceID);
    }

    return timestamp;
}
```

**Comment by rr-** [comment]
Sounds good to me.
