### ISSUE TITLE
The game crashes when exiting to title

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1238]
**Steps to reproduce, method 1:**

1. Go into Lara's Home
2. Then Exit to Title

**Method 2:**

1. Start New Game
2. Skip to the next level
3. Then Exit to Title

________________________

https://nebula.wind.garden/serve/pub/TR1X%203.1.1-117-g370bfad-Windows.zip 

#1177

**Comment by rr-** [comment]
This is now fixed.
