### ISSUE TITLE
Another stone centaur issue in 60 FPS

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1239]
Similar to #1209 

The stone centaur is in two poses at once when semi-activated.

Steps to reproduce:

- Play level 9
- Teleport to room 108
- Pull switch
- Teleport to room 90

______________________________

https://nebula.wind.garden/serve/pub/TR1X%203.1.1-117-g3d8bdd0-Windows.zip

#1177

**Comment by rr-** [comment]
There's also weird camera moment during the level pull. Does it happen in the OG @aredfan ?

**Comment by aredfan** [comment]
@rr- Yep it's OG.  We also have an issue for that here: #954

**Comment by aredfan** [comment]
@rr- My mistake.  The displaced camera bug in #954 happens just before a door opens.  

The screenshot below shows the weird camera moment **after** the door opens.  It's not OG, nor does it happen in 3.1.1.

It happens in both 30/60 FPS.

![1](https://github.com/LostArtefacts/TR1X/assets/94776985/fc116143-bb68-400e-a186-68c81df0cb0a)
