### ISSUE TITLE
Loading screen and underwater tunnel of Midas show briefly at level start

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1240]
https://github.com/LostArtefacts/TR1X/assets/4934209/5aadff8e-87a2-4566-9edb-7ce7f8d62815

Haven't quite noticed this before. It happens in 30fps too. It seems related to the loading screens. It doesn't happen quite as noticeably in v3.1.1 (where there are no loading screens).

Here is the source clip: 

https://github.com/LostArtefacts/TR1X/assets/4934209/ecf708f5-4def-4821-b66e-6929b0033f39

**Comment by aredfan** [comment]
This bug is also present when loading screens are disabled. (The tunnel bit)

![1](https://github.com/LostArtefacts/TR1X/assets/94776985/5454c9ca-0fc9-4b22-97a2-0937149e84e8)

There's no sign of the bug in 3.1.1 for me, I made a recording to check.

**Comment by rr-** [comment]
@lahm86 can you please check? I think this will be the same kind of bug as #1241 .
