### ISSUE TITLE
Lost Valley Demo black screen moment

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1241]
In the Lost Valley Demo, when Lara turns the corner into the open - there's a black screen moment.  This happens in 30/60 FPS.  The bug doesn't happen in 3.1.1.

![Screenshot](https://github.com/LostArtefacts/TR1X/assets/94776985/15cbf768-0ec0-47c2-a493-f1d0aeb7b672)

First part of the video is 3.1.1.  Second part is the dev build.

https://github.com/LostArtefacts/TR1X/assets/94776985/9cd5d7f1-7803-4e5d-9205-ae1d92704ebf

____________________________________

https://nebula.wind.garden/serve/pub/TR1X%203.1.1-117-g3d8bdd0-Windows.zip

**Comment by rr-** [comment]
@lahm86 can you check? Thanks

**Comment by lahm86** [comment]
The WIP camera changes for #1034 don't fix this one unfortunately.

It actually looks like the room is being excluded in the check below for some reason. This has also stumped me for the one identified in Natla's Mines in #1034 - it's this same check at play here.

https://github.com/LostArtefacts/TR1X/blob/develop/src/game/room_draw.c#L35

**Comment by aredfan** [comment]
https://discord.com/channels/1071085441077481544/1075372522377322516/1224477329200254976

I think the video posted by @Richard-L shows the same bug as this one.  I checked 3.1.1 and the black screen moment doesn't happen on that version.

![Screenshot](https://github.com/LostArtefacts/TR1X/assets/94776985/a4b75c2a-00ac-44f4-9ef2-db71d56c5c4c)
