### ISSUE TITLE
Gorillas move sideways and don't attack

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1244]
First observed in https://github.com/LostArtefacts/TR1X/releases/tag/2.15.3

https://github.com/LostArtefacts/TR1X/assets/4934209/d69b42cb-3d89-476b-8e15-b577d4929971

**Comment by rr-** [comment]
https://nebula.wind.garden/serve/pub/TR1X%203.1.1-121-g939c124-Windows.zip

**Comment by rr-** [comment]
This got previously approved by posix on Discord.
