### ISSUE TITLE
Title music plays over loading screen when using level select

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1245]
Expected behaviour would be to kill music.

https://github.com/LostArtefacts/TR1X/assets/4934209/a362e81f-8280-4222-9738-ced06cfc5b6d

**Comment by rr-** [comment]
https://nebula.wind.garden/serve/pub/TR1X%203.1.1-121-g1e1c63a-Windows.zip

**Comment by Richard-L** [comment]
Yup, fixed 👍
