### ISSUE TITLE
OG bug: underwater SFX plays for one frame in Midas

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#1251]
While investigating #1240, I noticed there is an odd (albeit subtle) sound for one frame at the very beginning of Midas - it's the underwater SFX playing and then immediately being cut-off on the next frame. This is present in TombATI as well.

**Comment by walkawayy** [comment]
@lahm86 I had an idea while watching the video in #1253.

My guess is the first frame after loading, the camera is underwater with Lara. One frame later, the look at camera triggers kicks in which changes the camera to above water.

**Comment by lahm86** [comment]
> @lahm86 I had an idea while watching the video in #1253.
> 
> My guess is the first frame after loading, the camera is underwater with Lara. One frame later, the look at camera triggers kicks in which changes the camera to above water.

Yes, I think you're right. Should be relatively easy to fix, I'll have a think about the best approach.
