### ISSUE TITLE
Lara says "no" when taking valid actions in front of a key item receptacle

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#1268]
Lara says "no" when using a medipack, taking out her guns, saving, loading, etc in front of a key item receptacle even though those are valid actions.

Semi-related, Lara says "No" if she tries to use medipack and her health is full already in TR4+. In TR1, the medipack animates open like it's being used.

**Comment by Richard-L** [comment]
This is a good one. Always found it weird that the medi pack animates in this case. 

Although do we feel the "No" is too iconic for bad key choice that it can't be added to other things as well?

Btw I believe the same thing can be done with the Scion. I remember accidentally choosing it years ago which made it animate, and I worried I had "wasted" it on something unrelated, and thinking the game would let me brick the playthrough like that.
