### ISSUE TITLE
Feature request: Add console ports likeness to the options

### ISSUE THREAD

**Issue by filipe-maia** [LostArtefacts/TRX#1301]
Hi.
This is not urgent, and probably hard to implement.
I've always heard that the water in the Saturn looked better than on the PC and PS1.
This issue is to request an option to turn on/off the water of the Saturn version and other options to turn on/off any other things that the PS1 and/or Saturn add different from the PC version.
Another cool option I can think of is the addition of save spheres, for anyone that wants the extra challenge.
Anyway, about the water and other differences:
https://www.reddit.com/r/TombRaider/comments/16lm7mm/tomb_raider_for_the_saturn/
https://core-design.com/article88.html
https://www.tombraiderforums.com/showthread.php?t=212989
https://www.tombraiderforums.com/showthread.php?t=213502
...
Thanks.

**Comment by rr-** [comment]
Hello, thank you for submitting the report. To streamline our tracking process, please create individual issues for each item mentioned. This will help us address them more efficiently.

**Comment by Richard-L** [comment]
@filipe-maia see here https://github.com/LostArtefacts/TR1X/issues/145
