### ISSUE TITLE
Doors open silently on loading saved level

### ISSUE THREAD

**Issue by fawtytoo** [LostArtefacts/TRX#1304]
Save the game at the beginning of the City of Vilcabamba level, then exit (maybe not necessary) and load that saved game. The doors open silently. I don't know if other doors or any animation with sound is affected.

**Comment by Richard-L** [comment]
I think it's impossible to save in the frame where the SFX is triggered, so upon load it's already passed while the animation just starts. I think this is fine personally.

**Comment by rr-** [comment]
Agreed. As a way to deal with this, we could store the SFX and their timestamps in the save files, but IMO it'd do more harm than good – more audible clicks due to audio clipping. Closing for now. We may revisit this if it gains more attention.
