### ISSUE TITLE
Data folder cleanup - injections

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1306]
@walkawayy suggested this idea a little while ago on discord. I hope I'm not being presumptuous by raising this issue.

It would be a good idea to create an injections subfolder to help streamline the game's data assets. This would provide clear distinction between the og files found in the data folder, and the new files found in the subfolders.

Of course, this would necessitate updates for the installer and gameflow files.

**Comment by rr-** [comment]
Agreed. I can prepare something.
