### ISSUE TITLE
Trapdoor camera issue in Temple of the Cat

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1317]
The switch is in level 1, room 20.

![Screenshot](https://github.com/LostArtefacts/TR1X/assets/94776985/ed020c29-1849-4fb6-b622-91b7db5205e9)

**4.0.3:**

https://github.com/LostArtefacts/TR1X/assets/94776985/77f389ff-1f3f-41c4-8fed-02d2fbcb7d76

**Snapshot:**

https://github.com/LostArtefacts/TR1X/assets/94776985/4e168494-a123-40a6-b0ba-4a885591a755

**Opening:**

![1](https://github.com/LostArtefacts/TR1X/assets/94776985/c305e2bd-174a-4dfd-acc8-1741d7f41a77)
![2](https://github.com/LostArtefacts/TR1X/assets/94776985/939dd796-9a04-4eab-a161-4ac1b829b66c)

**Closing:**

![3](https://github.com/LostArtefacts/TR1X/assets/94776985/071c751d-5651-4a89-b82d-70661dbcdb21)
![4](https://github.com/LostArtefacts/TR1X/assets/94776985/b6cf9cb7-ce3b-4573-88a8-82aca8c6639b)

Of course, this is just a small regression.  The new camera code by @lahm86 have already enhanced the TR1 experience in many ways so it's not a problem if there's no solution to be found.

**Comment by lahm86** [comment]
Adding a note here regarding #1451 - potentially we need to shift the cameras and/or targets in these cases, as the removal of the LOS check in #954 causes these other issues.

**Comment by aredfan** [comment]
**Regression since:** [4.1](https://github.com/LostArtefacts/TR1X/releases/tag/4.1).

____________________________________________

I've come across a camera bug which I suspect falls under this issue. Temple of the Cat, room 0.

**Recent build:**

https://github.com/user-attachments/assets/10c6e46a-7ba6-488c-b8fe-582d3132f47e

**4.0.3:**

https://github.com/user-attachments/assets/d869116d-2e93-42ec-b900-6c124c0ef714

**Comment by Richard-L** [comment]
Great find.

Would this one be related as well perhaps?

https://github.com/user-attachments/assets/fc45193b-745b-4001-95ce-e3adf1cfda81

From: https://discord.com/channels/1071085441077481544/1075372522377322516/1232079134084305048

**Comment by aredfan** [comment]
> Great find.
> 
> Would this one be related as well perhaps?

Thank you. That camera issue is also a regression since 4.1, I'm guessing it's related.
