### ISSUE TITLE
Exit to Title via inventory - left page edges issue

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1329]
The issue is on the left side of the passport in the `Exit to Title` section.  The right side of the page alongside the passport's hinge is choppy, and the left side has a few light pixels.  

This regression first appeared in 2.2.  

**2;1:**

![2 1](https://github.com/LostArtefacts/TR1X/assets/94776985/10c94de5-9336-498e-a175-b75c1f1329b6)

**2.2:**

![2 2](https://github.com/LostArtefacts/TR1X/assets/94776985/36dbfb7a-f09f-43bc-a383-755b03a3550a)

**Comment by rr-** [comment]
This was broken by the fix implemented in 4facd271 to address black seams along walls and align vertex calculations with TR2 and TR3. As such I don't think it's likely to be fixed.

**Comment by aredfan** [comment]
Ah no problem, thank you for taking the time to explain. 👍 

I remember when the black jagged lines was fixed, it happened shortly after I took an interest in this project.  I guess the passport regression is a trade-off, but acceptable because of improved visuals.

**Comment by aredfan** [comment]
Reclosing this issue as completed because the bug was fixed in [4.7](https://github.com/LostArtefacts/TRX/releases/tag/tr1-4.7).
