### ISSUE TITLE
Holding look fully forward causes an upside down frame on release

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#1338]
1. Look forward to the max range.
2. Release look
3. While the camera is resetting to normal, an upside down camera frame appears.

![20240422_193755_St_Francis_Folly](https://github.com/LostArtefacts/TR1X/assets/81546780/ee449ff5-2158-48c4-a45a-883f2cc985e5)

![20240422_193754_St_Francis_Folly](https://github.com/LostArtefacts/TR1X/assets/81546780/e61821e8-d04f-4591-8c0c-238ff2c43218)

**Comment by lahm86** [comment]
This happens in TombATI as well.

**Comment by fawtytoo** [comment]
Also happens with PS1 and DOS.

It's not exactly an upside down frame, but more like the camera went slightly past 90 degrees when resetting? At that point maybe something in the code causes it to switch view?

**Comment by walkawayy** [comment]
@rr-  @lahm86 

tr1 values are
#define MAX_HEAD_TILT_LOOK (22 * PHD_DEGREE) // = 4004
#define MIN_HEAD_TILT_LOOK (-42 * PHD_DEGREE) // = -7644

and TR4 values:
MAX_HEAD_TILT_LOOK : 5460
MIN_HEAD_TILT_LOOK : -6370

Making that change fixes the issue. But it slightly changes the look angles. Lmk what you think. This is the full forward tilt with TR4 values:

![20240510_202348_St_Francis_Folly](https://github.com/LostArtefacts/TR1X/assets/81546780/9aaf647b-96c0-41e7-a8a9-2930e205aea5)

**Comment by rr-** [comment]
I think it's OK to change it but I think only one of these two values needs to be adjusted. Ofc with a changelog etc.
