### ISSUE TITLE
Animated textures issue when using different turbo speeds - 60 FPS

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1341]
I noticed these 2 things can happen:

- Animated textures become static when using negative turbo speeds.
- Animated textures speed remain unchanged when using positive turbo speeds.

This may take several attempts to reproduce so keep toggling between 0 and -1 until the animation stops.  The issue is not present in 30 FPS mode.

**A good spot to test this issue in Lost Valley:**
![Screenshot](https://github.com/LostArtefacts/TR1X/assets/94776985/8826e388-14f0-4cc4-819f-10a59b06f61f)

**Comment by rr-** [comment]
The turbo cheat is completely broken with vsync option enabled, as all the 30/60-FPS-independent calculations rely on the turbo cheat multiplying the FPS by relevant factor, whereas the vsync option caps the rendering at screen refresh rate (eg 60 FPS) period.

**Comment by rr-** [comment]
@aredfan 
for the documentation purposes, can you please check the turbo cheat with the following:

- animated textures
- 3D pickups
- static pickups
- game timer while in inventory
- blinking healthbar

and let me know if these work in the current stable or not, and if not, if they're regressions made in 4.0 or were they broken since forever?

**Comment by aredfan** [comment]
Tested on 4.0.3 with 60 FPS mode.  Vsync is on.

**animated textures:**
- Turbo+ Animated texture same as 0.
- Turbo- Animated texture slows down.
- Turbo- Animated texture can also be static. 

**3D pickups:**

- Turbo+ 3D pickup same as 0.
- Turbo- 3D pickup slows down.
- Turbo- 3D pickup doesn't display when animated textures are static.

**static pickups:**

- Turbo+ Static pickup same as 0.
- Turbo- Static pickup slows down.
- Turbo- Static pickup stays on screen when animated textures are static.

**game timer while in inventory:**

- Turbo+ Timer speeds up.
- Turbo- Timer slows down.
- Turbo- Timer stops when animated textures are static.

**blinking healthbar:**

- Turbo+ Blinking same as 0.
- Turbo- Sometimes the blinking is the same as 0.  Sometimes the blinking stops on -2.  Sometimes the blinking slows down as expected.  There's inconsistency here.
- Turbo- Blinking stops when animated textures are static.

_______________________

Tested on 4.0 with 60 FPS mode.  Vsync is on.

- **animated textures:** same issues as 4.0.3
- **3D pickups:** no issues, regression started after this version.
- **static pickups:** no issues, regression started after this version.
- **game timer while in inventory:** same issues as 4.0.3
- **blinking healthbar:** same issues as 4.0.3

I'll find out when the pickups regression started. **Update:** regression for 3D and static pickups started on 4.0.3.
