### ISSUE TITLE
Black screen and crash at UB start with custom EGYPT.PHD

### ISSUE THREAD

**Issue by bursoft-git** [LostArtefacts/TRX#1346]
Hello!
Thanks for your cool work guys!
I translate Tomb1Main-TR1X into russian, and use custom *.PHD files for this
Early versions of TR1X work fine with my custom *.PHD, but version 4.1 crash when i start UB
[EGYPT.ZIP](https://github.com/LostArtefacts/TR1X/files/15138149/EGYPT.ZIP)

TR1X.log
`../../src/specific/s_shell.c 160 S_Shell_ShowFatalError GameBuf_Alloc(): OUT OF MEMORY Cinematic frames -82272`

Other files, if needed, you can grab on my translation page
https://bursoft-portable.blogspot.com/p/tomb-raider-i-gold.html

**Comment by lahm86** [comment]
This does appear to be a regression since 4.1 - many thanks for reporting the problem.
