### ISSUE TITLE
Installation path when upgrading TR1X should be the same as the initial installation

### ISSUE THREAD

**Issue by SixelAlexiS90** [LostArtefacts/TRX#1350]
When you first install TR1X, the program suggest you Documents\TR1X as a destination folder but you are free to change that to a different folder.

If you do that and you run the installer of a newer version to upgrade it, you can select "TR1X" as an installation source since you already have all the files there. 
After you select that tho, the program STILL defaults Documents\TR1X for the _upgrade_ and so you are making a second identical installation if you advance that, and so you have to select your personal installation folder to apply the upgrade on a single installation.

The installer should just respect the personal installation folder once you select "TR1X" instead of forcing you to re-select your installation folder just to upgrade it.
It should be easy to implement since the program is already able to detect your TR1X installation in the first place, this change would make sense and make the upgrading system more streamlined.

Thank you :)

**Comment by aredfan** [comment]
Slightly off-topic, I noticed the installer creates a folder in the Registry Editor called Tomb1Main instead of TR1X.

`Computer\HKEY_CURRENT_USER\Software\Tomb1Main`

**Comment by SixelAlexiS90** [comment]
Hi @lahm86 , I just want to say that this hasn't really been solved since right now I've got a weird issue after changing the installation folder by moving it to another location.

Once done that I've downloaded the new installer, I've clicked on "TR1X" on "Step 1" and selected the previous TR1X installation as the new source folder.

After that you get the "Step 2" and, while the program reads the previous installation, the "destination folder" isn't the one that I've just selected but it still points the OLD location.

So yeah, this time around it doesn't select "Documents\TR1X" but the old installation folder, the weird thing is that once you click on "change", the program put you on the NEW folder, the one that I've selected on "Step 1".
So you have to re-select the NEW folder to actually install it there.

Any chance that the "destination folder" on "Step 2" will actually match the source selected in "Step 1"?

Thank you for your work!
