### ISSUE TITLE
python required version

### ISSUE THREAD

**Issue by netfab** [LostArtefacts/TRX#1356]
Hi,

In https://github.com/LostArtefacts/TR1X/issues/1296#issuecomment-2048290758 you said :
> Please update Python to 3.10, ideally 3.12.

Is this a hard requirement ? If yes, why not check the python version on build ?
https://github.com/LostArtefacts/TR1X/blob/develop/meson.build#L51

Thank you.

**Comment by rr-** [comment]
Yes, it is a necessity. The official builds that make use of Docker images and pinned versions should be free of issues, so please feel welcome to open a pull request if you wish to see a more informative warning outside of the officially supported build routine.
