### ISSUE TITLE
Include PS1 FMVs in installer?

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1364]
Just a thought Dash, feel free to close if you'd rather not. But was thinking since the soundtrack is made available, and since TR1X nicely supports the PS1 video files that _are_ better quality, it would seem like a nice convenience to add them.

I tried compressing them and am coming to ~160mb.

**Comment by walkawayy** [comment]
Gonna close as duplicate of #649.

**Comment by Richard-L** [comment]
Ah, sorry.
