### ISSUE TITLE
Game can crash with more than 16 savegame slots

### ISSUE THREAD

**Issue by Patrxgt** [LostArtefacts/TRX#1374]
Like in title, game either outright crashes or after playing startup FMVs. Also, when anything above 218 is set, game will crash only after trying to start a new game or load a save.

**Comment by aredfan** [comment]
Adding this info because I think it's within scope.  EternalCosmos wrote on discord:

> Something i noticed in my playthrough this weekend: the configurer lets you decide how many saveslots are available. But it seems that 65 different saves  is the cutoff. The saves i did on a new line went back to the very first save on the list.
> 
> Example: my first save is at the first crystal in caves. I keep on using a new slot for every crystal after that. Once i reached natlas mines i kept on saving. When dying and reloading save number 70. The game loaded save number 5 which was somewhere in lost valley 
> If i loaded save 65 it was caves again. 66 was vilcabamba and so on
> Saving on an old slot worked normally and i could load natlas mines no problem

I tested this scenario - if there's a save in slot 65 and no save in slot 1, if you load the save in slot 65, the game crashes.

**Comment by walkawayy** [comment]
I'm going to rename this issue since there's actually two issues going on. Memory corruptions can occur with anything over 16 savegames. The other issue is the game can only read up to savegame slot 64.
