### ISSUE TITLE
TR1X bug: Lightning transparency issue

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1385]
Regression since 1.4

_______________________

**TR1X:** The lightning isn't transparent from this position.
![1 2 TR1X](https://github.com/LostArtefacts/TR1X/assets/94776985/0ea49c52-261c-41e5-90eb-0699d72d63c1)

**TombATI:**
![1 1 TombATI](https://github.com/LostArtefacts/TR1X/assets/94776985/678651b6-e4aa-4bd9-8a04-6ab724ba3b7b)

**TR1X:** The scion altar isn't visible behind the lightning bolts.
![2 2 TR1X](https://github.com/LostArtefacts/TR1X/assets/94776985/a5782438-f231-422e-bbe7-211a151498d2)

**TombATI:**
![2 1 TombATI](https://github.com/LostArtefacts/TR1X/assets/94776985/664436f7-31a9-4734-9c08-2e5c6e147a8b)

**Comment by rr-** [comment]
Broken almost certainly by b431c248.
