### ISSUE TITLE
TR1X bug: Issue with console command to load specific levels

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1399]
**Dev snapshot:** 4.1.2-50-g0a7984f

____________________

If I use console command to load the first 3 levels e.g. `play 1`, Lara's Home is loaded instead.

If I use `play 4`, the game freezes and these messages display:

![1](https://github.com/LostArtefacts/TR1X/assets/94776985/ed4b56ed-535b-462b-b0f8-4c473acb8a3c)

![2](https://github.com/LostArtefacts/TR1X/assets/94776985/1b92d838-8fb6-4f9c-b292-159c74820e59)

**Comment by rr-** [comment]
Fixed in f44cbcfd
