### ISSUE TITLE
TR1X bug: Lara can reach trigger through closed UW gate

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1419]
A regression since [1.1.5](https://github.com/LostArtefacts/TR1X/releases/tag/1.1.5), possibly [1.1.4](https://github.com/LostArtefacts/TR1X/releases/tag/1.1.4) too but I'm unable to check the latter version because it crashes.

The issue is not present in [1.1.3](https://github.com/LostArtefacts/TR1X/releases/tag/1.1.3).

____________________________

This bug manifests in 2 ways:

- The camera doesn't get pushed out after the gate closes.
- Lara can swim against the gate to reach the trigger on the other side which opens the gate.

**TombATI**

https://github.com/user-attachments/assets/8329ab5c-ce02-433a-ba69-8c63a90acdc8

**TR1X**

https://github.com/user-attachments/assets/5771fd33-4306-4689-ac10-6c621ed15425

**Comment by Richard-L** [comment]
Would this at all have anything to do with the dive roll which native TR1 doesn't have?

**Comment by rr-** [comment]
No – the glitch stems from a patch added in cb928f93 to prevent Lara from voiding when a timed door closes on her. Removing it fixes the issue, but also brings the previous bug back.

```diff
diff --git a/src/game/objects/general/door.c b/src/game/objects/general/door.c
index 307c5a03..58a9cdb2 100644
--- a/src/game/objects/general/door.c
+++ b/src/game/objects/general/door.c
@@ -38,10 +38,6 @@ static void Door_Shut(DOORPOS_DATA *d, ITEM_INFO *item)
         return;
     }
 
-    if (item && Door_LaraDoorCollision(item)) {
-        return;
-    }
-
     floor->index = 0;
     floor->box = NO_BOX;
     floor->floor = NO_HEIGHT / 256;
```

**Comment by rr-** [comment]
Here's another propsed patch that changes the proximity check to a block check.
To see its effectiveness we'll need a test level where the OG bug (with door closing automatically on Lara causing her to void) can be reproduced. CC @lahm86 
```diff
diff --git a/src/game/objects/general/door.c b/src/game/objects/general/door.c
index 307c5a03..4a7141f7 100644
--- a/src/game/objects/general/door.c
+++ b/src/game/objects/general/door.c
@@ -23,12 +23,12 @@ static bool Door_LaraDoorCollision(ITEM_INFO *item)
     if (!g_LaraItem) {
         return false;
     }
-    int32_t max_dist = SQUARE((WALL_L * 2) >> 8);
-    int32_t dx = ABS(item->pos.x - g_LaraItem->pos.x) >> 8;
-    int32_t dy = ABS(item->pos.y - g_LaraItem->pos.y) >> 8;
-    int32_t dz = ABS(item->pos.z - g_LaraItem->pos.z) >> 8;
-    int32_t dist = SQUARE(dx) + SQUARE(dy) + SQUARE(dz);
-    return dist < max_dist;
+
+    return (
+        ((item->pos.x & ~WALL_L) == (g_LaraItem->pos.x & ~WALL_L)) &&
+        ((item->pos.y & ~WALL_L) == (g_LaraItem->pos.y & ~WALL_L)) &&
+        ((item->pos.z & ~WALL_L) == (g_LaraItem->pos.z & ~WALL_L))
+    );
 }
 
 static void Door_Shut(DOORPOS_DATA *d, ITEM_INFO *item)
```

**Comment by lahm86** [comment]
Here is a test level. It's when a door isn't on a portal AFAIK; Lara certainly voids with this in TombATI.
[LEVEL1.zip](https://github.com/user-attachments/files/16367001/LEVEL1.zip)

In OG, I think you can recreate it in room 42 in Atlantis if you go onto the antipad and then go back while the door's closing.
![image](https://github.com/user-attachments/assets/4c984e39-5f72-426d-8607-64147183bbbb)
