### ISSUE TITLE
Underwater "caustics" hard cut when exiting menu

### ISSUE THREAD

**Issue by Raildex** [LostArtefacts/TRX#1423]
When you open the inventory, the underwater "caustics" still update, resulting in an abrupt change in the vertex colors when you exit the inventory

https://github.com/user-attachments/assets/0a985721-d262-4d96-8106-f71f4060c72d

**Comment by aredfan** [comment]
TombATI, for reference.

https://github.com/user-attachments/assets/5b613bf8-94a3-4526-8875-c6194c4780c4
