### ISSUE TITLE
TR1X bug: Possible for Lara to start Atlantis level with empty holsters

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1437]
This issue is present in the latest stable 4.2, so nothing new.

__________________

There's 2 things to note:

- In New Game, Lara will always start a new level with pistols in her holsters.
- Lara is automatically given pistols at the start of Atlantis if she doesn't have them in her inventory.

However, it's possible for Lara to start Atlantis with empty holsters or different guns in her holsters.  This happens if there are no pistols in Lara's inventory in the previous level.

**Table for clarity:**

| Guns in holsters (Natla's Mines) | Weapon equipped (Natla's Mines) | Guns in holsters (Atlantis) |
|----------------------------------|-----------------|-----------------------------|
| Magnum                           | Magnum          | Magnum                      |
| Magnum                           | Shotgun         | Empty                       |
| Uzis                             | Uzis            | Uzis                        |
| Uzis                             | Shotgun         | Empty                       |

__________________

On TombATI, Lara will end up with pistols in all 4 scenarios.  I've attached a TombATI save which is at the end of Natla's Mines with only shotgun, magnum and uzi collected. [saveati.zip](https://github.com/user-attachments/files/16571832/saveati.zip)

_____________________

**Update:** To clarify a few things after double checking the game's behaviour.

- The empty holsters issue happen regardless of whether `Pistols as primary weapon` is enabled or disabled.
- If `Pistols as primary weapon` is enabled, Lara incorrectly draws magnums/uzi at the start of Atlantis, scenarios shown above.

**Comment by rr-** [comment]
Can we check which version broke this?

**Comment by Richard-L** [comment]
Took me a moment to understand this. It's for the scenario that a player _doesn't_ pick up the pistols after entering the 3 fuses, but then picks up magnums/shotguns from the baddies?

Is this even possible?

Also what about the setting to keep equipped weapons between level changes? I think there's an option to reset to pistols, no? What happens if there are no pistols in the inventory with this option enabled?

**Comment by aredfan** [comment]
> Can we check which version broke this?

@rr- It's a regression since [2.4](https://github.com/LostArtefacts/TR1X/releases/tag/2.4).

> Took me a moment to understand this. It's for the scenario that a player doesn't pick up the pistols after entering the 3 fuses, but then picks up magnums/shotguns from the baddies?
> 
> Is this even possible?

@Richard-L Yes, you can skip the whole fuse part and run pass cowboy.  It's like doing pacifist run. 

Further on in the level there's a shotgun pickup, see [here](https://github.com/LostArtefacts/TR1X/pull/1435#issuecomment-2280699930).  The shotgun can be used to kill the baddies.

> Also what about the setting to keep equipped weapons between level changes? I think there's an option to reset to pistols, no? What happens if there are no pistols in the inventory with this option enabled?

Good point.  I checked and the issue is still present whether `Pistols as primary weapon` is enabled or disabled.

**Comment by aredfan** [comment]
There's one more scenario I haven't considered before creating this issue.

| Guns in holsters (Natla's Mines) | Weapon equipped (Natla's Mines) | Guns in holsters (Atlantis) |
|----------------------------------|---------------------------------|-----------------------------|
| Empty                            | Shotgun                         | Empty                       |

Also a regression since [2.4](https://github.com/LostArtefacts/TR1X/releases/tag/2.4).  This scenario gives you pistols on TombATI.

**TombATI save:** [saveati.zip](https://github.com/user-attachments/files/16574426/saveati.zip)
(End of Natla's Mines. The only weapon Lara has is a shotgun but she hasn't equipped it yet. Make sure to equip the shotgun before ending the level.)

**Comment by rr-** [comment]
I'll check it out later today, as it appears I'm the one who caused the issue in commit 0e44e5fafbfef1c5a1720e37772e87b4e3939794.
