### ISSUE TITLE
Set default weapon on pickup

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#1443]
If Lara picks up a gun that's not the pistols, it should (perhaps optionally) become the default gun.
See https://github.com/LostArtefacts/TR1X/pull/1442#pullrequestreview-2237460540

I'm not sure that this is a bug, rather a missing feature from OG.

**Comment by Richard-L** [comment]
Maybe a dumb question, but what is a "default gun"?

I guess the pistolless state of Lara is so seldom in the game that I'm unaware of the dynamic you've described in the linked PR.

If she has other weapons than pistols (this being a scenario a player really has to force to happen), and then pressing equip, she won't equip anything unless a weapon is first chosen from the inventory?

**Comment by lahm86** [comment]
Yes, so if you collect the uzis for example but don't have pistols, and then press your draw guns input, nothing will happen. So the idea would be that in this scenario, the engine would make the uzis the "pre-selected" gun, so you could draw them with the input key rather than having to select manually.

**Comment by Richard-L** [comment]
That makes a lot of sense and is a nice idea. I guess more so for TRLEs than the game itself this would be relevant.

So it would mean the last picked up weapon showing in the holster, or none in the holster if only the shotgun is on Lara's back, and then hitting equip would make her equip either what's in the holster, or the shotgun (?).
