### ISSUE TITLE
Screenshots are only a black screen

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#1475]
Screenshots only come out as black screens. My guess is this broke in #1471? I wasn't around to test though, so I'm not sure.

![20240901_205133_Title](https://github.com/user-attachments/assets/554c1ad9-c544-4afc-9f82-975c94f497d7)

**Comment by rr-** [comment]
This is the commit that visibly broke the screenshots: cb5d71ee036b1aa1fa850cf908ee0aa990b7409f
I have a hunch that this is something nastier, though.
