### ISSUE TITLE
Improve vertex movement

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#1493]
When looking through water portals, all vertices in the opposite water status rooms move, which results in gaps where the rooms join. In TR2, room vertices have attributes for controlling this, but TR1 room vertices only have position and shade. Add an initial improvement to this, to target locking vertices that are on room edges.

![image](https://github.com/user-attachments/assets/f6404bdd-7f8d-46a2-96b6-3eff9b47baac)

Note that it won't feasibly be possible to fix every situation, as indeed you can see in TR2. This is a level design issue where vertices don't always match up between faces, and so the movement becomes out of sync. Fixing this would mean manually adjusting faces, vertices and tex infos, which is a very big task.

![image](https://github.com/user-attachments/assets/b76f1e79-68e6-4449-91c9-b3439d398b1e)

**Comment by rr-** [comment]
Reopening as we found a technique so that this can be improved even further.
