### ISSUE TITLE
Restore PS1 purple colouring on save crystals 

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1506]
Now that we have the reflections so truthfully added to TR1X, the only thing missing about the crystals is their characteristic purple colour.

https://github.com/user-attachments/assets/e090a307-d9dd-447c-9af2-4bb312b689d2

@walkawayy I believe you'd identified the shade pretty precisely when doing the PS1 style menu UI, no? Else we can help.

**Comment by rr-** [comment]
@aredfan @Richard-L Can you check what the crystal in the Midas fire room reflects in the PS1 version, when Lara is on fire and standing next to it?

**Comment by Richard-L** [comment]
En route to going on fire:

https://github.com/user-attachments/assets/db256461-502c-467c-94da-57e0ed55436a

On fire:

https://github.com/user-attachments/assets/cc5c9c49-4906-4ef7-93af-6f646b748547
