### ISSUE TITLE
The Pretty pixels option adds gaps between textures

### ISSUE THREAD

**Issue by bursoft-git** [LostArtefacts/TRX#1507]
Hello everyone!
I use the build TR1X-4.3-68-g1cb8ae9-Windows
I prefer to play with the filtering turned off. In this mode, gaps between textures are sometimes visible, especially on moving textures.
Pretty pixels OFF
![Pretty pixels OFF+](https://github.com/user-attachments/assets/ec448732-4482-4c9b-9f59-a8ada3b85ce7)
But with the Pretty Pixels option enabled, the gaps become even more noticeable! 
![Pretty pixels ON+](https://github.com/user-attachments/assets/ee4ae29b-09ca-41e3-bed8-0e97cb8f164d)

Apparently, these half pixels just serve to hide these gaps.
Is there a way to mask these gaps?
Thanks!

**Comment by rr-** [comment]
Try fiddling with the anisotropic filter settings.

**Comment by bursoft-git** [comment]
The Pretty Pixels option only works with filtering turned off, and it doesn't make sense with filtering turned on.
Enabling filtering solves the problem, I know that. But filtering also adds blurriness, and in games with low-resolution textures I prefer not to use filtering.
Filtering ON
![Bilinear filtering ON](https://github.com/user-attachments/assets/c2458dc0-014f-4d77-857c-b4f730ea3e93)
The question was, is there any way to mask the gaps? Because the option implies something beautiful, but in fact adds black stripes between textures.

**Comment by aredfan** [comment]
Anisotropic filter is found in the config tool.  Try reducing the 16.0 value to 1.0.

![Screenshot](https://github.com/user-attachments/assets/a08b6f89-5192-434c-9231-e5260ede7513)

**Comment by bursoft-git** [comment]
> Anisotropic filter is found in the config tool. Try reducing the 16.0 value to 1.0.

ok, I tried
anisotropic filtering 1.0 removes gaps, but adds another unpleasant effect
![Anis](https://github.com/user-attachments/assets/ef8fd15b-86ae-4494-89d1-7ae7c57ebe1d)

**Comment by rr-** [comment]
@bursoft-git can you please LMK whether this build improves things?

https://home.wind.garden/serve/pub/TR1X-4.3-74-g5f6c968-dirty-Windows.zip

**Comment by walkawayy** [comment]
Looks really good to me!

![20240913_204234_Laras_Home](https://github.com/user-attachments/assets/85640817-a874-4bed-b7a9-ed4616391614)


Also the snow in Caves looks soooo much better too. (Re: issue #902) Pretty Pixels does leave some seams. With it off, the black lines in the snow seem totally gone.

Pretty Pixels ON:

![20240913_204454_Caves](https://github.com/user-attachments/assets/dce137dc-d16a-463e-a7f2-5770e8cc5da9)


Pretty Pixels OFF:

![20240913_204557_Caves](https://github.com/user-attachments/assets/b0c8599d-c609-47ed-bd9a-df4e6fa1f470)

**Comment by walkawayy** [comment]
Looks really good to me!

![20240913_204234_Laras_Home](https://github.com/user-attachments/assets/85640817-a874-4bed-b7a9-ed4616391614)


Also the snow in Caves looks soooo much better too. (Re: issue #902) Pretty Pixels ON does leave a few seams. With it OFF, the black lines in the snow seem totally gone!

Pretty Pixels ON:

![20240913_204454_Caves](https://github.com/user-attachments/assets/dce137dc-d16a-463e-a7f2-5770e8cc5da9)


Pretty Pixels OFF:

![20240913_204557_Caves](https://github.com/user-attachments/assets/b0c8599d-c609-47ed-bd9a-df4e6fa1f470)

**Comment by bursoft-git** [comment]
> @bursoft-git can you please LMK whether this build improves things?

@rr- thanks for the answer!
I checked the last build
I use 1920x1080 resolution, 16x anisotropic filtering, Texture filtering - OFF, Pretty Pixels - ON
A little better, the gaps are gone on two surfaces (marked with green arrows)
But the gaps are still visible in the places marked with red arrows. Nothing seems to have changed here.
![Pretty pixels ON, FHD](https://github.com/user-attachments/assets/430d04fb-fbca-4a08-85cc-1e11b724996d)

**Comment by rr-** [comment]
We'll track it in #902 as it's pretty much a duplicate issue.
