### ISSUE TITLE
TR1X: reduced brightness can make reflections very dark

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1511]
#1510 

___________________

With brightness set to 0.7, left is dev snapshot and right is the PR build.

![1](https://github.com/user-attachments/assets/17b474bc-0ce3-4df0-ba17-0da8018fd9c1)

![2](https://github.com/user-attachments/assets/6f6bef87-d765-486f-b9ab-cccdb1f86f2a)

**Comment by rr-** [comment]
Fixed in the PR.
