### ISSUE TITLE
Feature request: Allow Lara to go from deep water to one-click water like in TR2+

### ISSUE THREAD

**Issue by rondeeno** [LostArtefacts/TRX#1537]
Since one-click water support was added in #1005, it would be nice if the ability to move from deep water to one-click water was available for custom levels. From what I can tell, two animations would have to be injected: `UNDERWATER_TO_STAND` (192) and `ONWATER_TO_WADE_LOW` (193).

**Comment by lahm86** [comment]
This will require some tie-in with wading itself as some of the logic is quite tightly related, so we will address this in 4.6.
