### ISSUE TITLE
Problems with saving and loading during the pickup or switch sidestep animation with animated interactions enabled

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#1546]
**Pickups:**
TR1X Animated Interactions On:
❌ Saving mid pickup animation and loading causes Lara to finish the pickup animation but not pickup the item.

TR1X Animated Interactions Off:
✅ Saving mid pickup animation and loading causes Lara to finish the pickup animation and pickup the item.

TombATI:
✅ Saving mid pickup animation and loading causes Lara to finish the pickup animation and pickup the item.

**Switches:**
TR1X Animated Interactions On:
❌ Saving while sidestepping to the switch and loading causes Lara to not pull the switch. She can no longer draw her guns or use her hands unless you go underwater / reset her hands status.

TR1X Animated Interactions Off:
✅ Lara doesn't sidestep, and saving while pulling the switch and loading works properly.

TombATI:
✅ Lara doesn't sidestep, and saving while pulling the switch and loading works properly.

**Comment by rr-** [comment]
IMO the first behavior is tolerable as-is, but we definitely should fix the second point.

**Comment by walkawayy** [comment]
@rr- I checked out tomb4 and it looks like the item Lara is interacting with is saved which I'm assuming is the reason it works but TR1X's doesn't. For the switch and the pickup.

switch target saved here: https://github.com/Trxyebeep/TOMB4/blob/455931881bc1efabe6a3a18ea13fc1fe7d94a701/TOMB4/game/switch.cpp#L284

pickup target saved here: https://github.com/Trxyebeep/TOMB4/blob/455931881bc1efabe6a3a18ea13fc1fe7d94a701/TOMB4/game/pickup.cpp#L490

saved here in savegame: https://github.com/Trxyebeep/TOMB4/blob/455931881bc1efabe6a3a18ea13fc1fe7d94a701/TOMB4/game/savegame.cpp#L92

Am I good to add this to future savegames and increment to `SAVEGAME_CURRENT_VERSION 6` from 5? Thinking I might as well add this whole struct from `LARA_INFO` to the savegame:
```
    struct __PACKING {
        int32_t item_num;
        int32_t move_count;
        bool is_moving;
    } interact_target;
```

**Comment by rr-** [comment]
> @rr- I checked out tomb4 and it looks like the item Lara is interacting with is saved which I'm assuming is the reason it works but TR1X's doesn't. For the switch and the pickup.
> 
> switch target saved here: https://github.com/Trxyebeep/TOMB4/blob/455931881bc1efabe6a3a18ea13fc1fe7d94a701/TOMB4/game/switch.cpp#L284
> 
> pickup target saved here: https://github.com/Trxyebeep/TOMB4/blob/455931881bc1efabe6a3a18ea13fc1fe7d94a701/TOMB4/game/pickup.cpp#L490
> 
> saved here in savegame: https://github.com/Trxyebeep/TOMB4/blob/455931881bc1efabe6a3a18ea13fc1fe7d94a701/TOMB4/game/savegame.cpp#L92
> 
> Am I good to add this to future savegames and increment to `SAVEGAME_CURRENT_VERSION 6` from 5? Thinking I might as well add this whole struct from `LARA_INFO` to the savegame:
> 
> ```
>     struct __PACKING {
>         int32_t item_num;
>         int32_t move_count;
>         bool is_moving;
>     } interact_target;
> ```

Sounds good to me. I too think that we can simply save all of `interact_target`.
