### ISSUE TITLE
OG bug: killing enemies with grenades count as 2 kills

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1560]
[https://www.tombraiderforums.com/showthread.php?p=8251220](https://www.tombraiderforums.com/showthread.php?p=8251220)

When this issue is being worked on - it'll be worth checking the black skidoo riders, bird monster and the dragon.

**Comment by walkawayy** [comment]
Likely needs `Rocket_Control` decompiled to fix.

**Comment by walkawayy** [comment]
@aredfan does the OG game also have a bug where the grenade counts as 2 hits as well instead of 1?

**Comment by aredfan** [comment]
@walkawayy hit points isn't bugged in OG.

For example, I use a grenade on a monk which kills him straight away.  The stopwatch stats shows 1 hit and 2 kills.
