### ISSUE TITLE
OG bug: xian statue disappear after 4 grenade hits

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1561]
**Regression since:** [0.3](https://github.com/LostArtefacts/TR2X/releases/tag/0.3)
(The game crashes when reproduced on 0.2 and the OG .exe (shipped with TR2X.)

_______________

When I try the same steps with the Steam version or TR2Main - the xian statue take no damage from grenades.

**Comment by aredfan** [comment]
The same thing happens on the PSX version with the statues disappearing after a few grenade hits. I'm guessing it's a OG bug.

[https://www.tombraiderforums.com/showthread.php?p=8323595#post8323595](https://www.tombraiderforums.com/showthread.php?p=8323595#post8323595)

**Comment by walkawayy** [comment]
I think TR2Main fixes this by checking if the target's item status is active or not in `Grenade_Control`.
