### ISSUE TITLE
Ambient level music doesn't stop when changing level via console command

### ISSUE THREAD

**Issue by Gizzy-91** [LostArtefacts/TRX#1570]
TR2X 0.3 release

https://www.youtube.com/watch?v=vBbC_fGqH0c

Started in GW, change level to Xian
Activate the audio sting by triggering the trapdoor at the start
End the level once the ambient music starts
Xian's ambient music continues to play

If you don't activate the audio sting at the start and allow the ambient music to start normally, ending the level causes the ambience to stop as you'd expect.

[TR2X.log](https://github.com/user-attachments/files/17083480/TR2X.log)

**Comment by aredfan** [comment]
When reproducing this bug, the xian ambient music continues to play when the inventory is open. Normally all sounds are muted when the inventory is open in OG TR2.

1. `/play 15`
2. fly to the trapdoor to trigger the music
3. `/endlevel`
4. skip the cutscene and end of level stats
5. open the inventory
