### ISSUE TITLE
Feature request: END.PCX for final stats background

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1584]
I assumed the black background on the final stats screen was a bug, but apparently this is OG behaviour.

TR2Main uses the END.PCX image as a background which is a nice touch.  TR2X could perhaps adopt this approach too.

![1](https://github.com/user-attachments/assets/81b3b284-6eff-46fc-9a31-27708bee37d1)

This is what END.PCX looks like:
![END](https://github.com/user-attachments/assets/e71a3e6f-522b-48a7-a6d7-42d47ca863d3)

**Update:** Golden Mask's final stats after Kingdom, is also a black screen

**Comment by Richard-L** [comment]
Interestingly PS1 uses the main menu backdrop.

![Tomb Raider II - Starring Lara Croft (USA) 2024-08-23-23-13-51](https://github.com/user-attachments/assets/602fb0e7-5e8c-4b8a-9c2b-9055d5393cf8)

But I agree if the END.PCX is included on PC it would lend itself a lot.

Curiously after exiting out of the final stats screen on PS1, it goes right to the EIDOS intro as though you'd reset the game. Doesn't make a lot of sense.

**Comment by aredfan** [comment]
The same backdrop is used in SW mode.

![OG](https://github.com/user-attachments/assets/2bed4642-6fad-44c5-b333-032e3a9c484a)
