### ISSUE TITLE
OG bug: exiting during credits does not end process

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#1585]
If you Alt+F4 during the end-game credits, the skidoo music continues and the Tomb2.exe process does not terminate.

**Comment by aredfan** [comment]
This also happens if you Alt+F4 in the end-of-level stats.

**Comment by aredfan** [comment]
This issue was fixed in 1777, but it has resurfaced when force quitting the game during the credits.

**Dev snapshot:** 0.5-172-ge7df771 (latest)
**Steps to reproduce:**

1. `/play 18`
2. `/endlevel`
3. Alt+F4
