### ISSUE TITLE
OG bug: One of the plaques stops spinning and its name disappear

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1586]
**Save:** [savegame.zip](https://github.com/user-attachments/files/16714319/savegame.zip)

**Step to reproduce:**

1. Have both Mystic Plaques in Lara's inventory
2. Insert the first Mystic Plaque on the left side
3. Open Lara's inventory to view the other Mystic Plaque

This issue isn't present when Lara goes to the other slot to insert the plaque.  It's only present if the player opens the inventory after inserting the first plaque.

![1](https://github.com/user-attachments/assets/bcd832fe-acaa-4f53-8ab3-6616ffd0d810)
![2](https://github.com/user-attachments/assets/04c6f819-3d89-4cec-bdf5-8cbac9eea653)
![3](https://github.com/user-attachments/assets/9093a39b-c517-411c-a3d0-e7772dedde94)

**Comment by lahm86** [comment]
This is the "dupe glitch" and is present in TR1 and TR3 (I believe) as well. Not sure about TR4/5. It's used in the Barkhang glitched speedrun where you only need to collect one prayer wheel (discovered by Eycore originally). I don't think it's used anywhere else in runs.
I imagine this should become an optional fix, similar to the other optional glitch fixes in TR1X. Saying that, I don't know what's involved in the fix itself, just adding some comments for the record.
