### ISSUE TITLE
OG bug: If Lara is standing in 2 clicks of water while holding a flare, bubbles appear above the water

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1590]
Screenshots show Bartoli's Hideout (VENICE.TR2), room 139.

![1](https://github.com/LostArtefacts/TRX/assets/94776985/a99acdb3-3718-406d-b030-8437953bd393)

![2](https://github.com/LostArtefacts/TRX/assets/94776985/473f983d-3f4a-4c88-a8d4-3757673adec3)

**Comment by lahm86** [comment]
Also related to this, the sound effects for the flare igniting and burning don't play when Lara's technically in a water room but her hand isn't.
