### ISSUE TITLE
Add Arachnophobia Mode

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1608]
Initially discussed between @rr- and @lahm86 on discord.  The idea is to add an option to replace spiders (small and large) with different types of enemies e.g. rats, tigers, eagles etc.

It's just these two levels containing spiders:
- The Great Wall (WALL.TR2)
- Temple of Xian (EMPRTOMB.TR2)

**Comment by rr-** [comment]
We could also go with less ugly spiders.
