### ISSUE TITLE
Feature request: Add fades

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1623]
Along the lines of what we have in TR1X and PS1.

- Fade in/out on Main Menu
- Fade in/out on all graphic images 
- Fade out after end-of-level statistics
- Fade out after Exit to Title

LMK if I missed any and whether this should remain 1 issue or split up into separate issues.

**Comment by Richard-L** [comment]
https://github.com/LostArtefacts/TR2X/assets/4934209/e9bdbc0d-b997-4ef7-b730-2a19120b01e4

Just to exemplify PS1 fades a bit, in case it's of any interest. Seems to behave pretty much the same as TR1.
