### ISSUE TITLE
Add 3D PickUps

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1634]
Cf TR1X

**Comment by aredfan** [comment]
For this and LostArtefacts/TRX#1633 - I think the devs should make allowance for secrets to remain sprites because there are no 3d models for secrets in TR2/GM.  In other words, a hybrid option of 3d pickups and sprites.

**Comment by rr-** [comment]
Are there any decent 3d models for the dragons that we could inject?
(This could be a separate setting.)

**Comment by Richard-L** [comment]
Ah shoot that's true. 

A hybrid could work. I could also try modelling something perhaps. What format would we need for it? OBJ, STP? Would there be a max face count to regard?

**Comment by rr-** [comment]
I'm afraid I don't know; maybe @lahm86 could answer this?

Regarding style, I'd try to maintain this dragon shape:
![20231106_095108_xbb](https://github.com/LostArtefacts/TRX/assets/1045476/7b40c3fb-1a0c-4c19-a53b-984f99e5a87e)
![20231106_095132_nxm](https://github.com/LostArtefacts/TRX/assets/1045476/ad17cd0b-4805-4347-9d1e-cf793551a526)
and not diverge like this, which can be seen in custom levels:
![20231106_095204_zng](https://github.com/LostArtefacts/TRX/assets/1045476/b0c6118d-77e4-4202-b652-d74cabe1fb66)

Ideally we should maintain low poly style:
![ee82e555feef5805a5e245171997bf46](https://github.com/LostArtefacts/TRX/assets/1045476/6ba02498-dd12-477e-a7ed-5e8778fb1e47)

**Comment by aredfan** [comment]
Low-poly models sound good to me because it's more faithful to imitate the original game.  I thought it might be helpful to add a picture of all the secret sprites for reference, top row is TR2 and bottom row is TRGM.

![1](https://github.com/LostArtefacts/TRX/assets/94776985/55545cdc-8734-4aba-8891-563e5702e7af)

**Comment by Richard-L** [comment]
Thanks a lot!

I was going to look for them. I believe some fans even dug up the source images of these from some 90s stock product. I'll see if I can find some of that. Will be helpful to have as much info as possible to then distil down to something low poly.

**Comment by lahm86** [comment]
Of all the pickup items in TR2, the flare box has the most faces - 325 in total between 4 meshes.

![image](https://github.com/LostArtefacts/TRX/assets/33758420/9ccbfafe-d82f-4f39-9734-5340b425b7d6)

The small medipack has the most meshes (7).

![image](https://github.com/LostArtefacts/TRX/assets/33758420/ce8a884c-efef-45c5-9066-2e978290712e)

I can't say whether or not there are limits, but these numbers seem fairly generous for making new models. In terms of format, WadTool supports several - too many to list :smile: If you open a level, pick any object and then choose Edit Skeleton > Import Mesh, you can see the supported types there.

Whatever is chosen ideally would be compatible with WadTool so we could then easily convert it to TR format and generate injections. For the injections themselves, we'd need to allocate new object IDs as I don't think there are any spare in OG (aside from maybe the unused map object).

**Comment by aredfan** [comment]
A couple more pics to show the "low poly style" of TR2 pickups:

![1](https://github.com/LostArtefacts/TRX/assets/94776985/40279e98-74fd-44c3-a7ec-b0716d4815fe)
![2](https://github.com/LostArtefacts/TRX/assets/94776985/86b86e99-a8e1-421e-8f56-8d792a30e6eb)
