### ISSUE TITLE
Add Dozy cheat

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1642]
Add dozy mode for flying and resurrection. Super useful during testing.

Old:
~~Always useful for testing.~~

~~Basically what we know from TR1x:~~
~~- Dozy~~
~~- Weapons~~
~~- Level skip~~
~~- Door open~~

~~Additionally the TAB key "turbo mode" is also handy (block pushing, ladder climbing), although I'd make it a toggle instead of a step through two speeds for better intuitiveness.~~

**Comment by rr-** [comment]
Can we convert this issue into four different issues? It'll be easier to deliver these one-by-one.

**Comment by Richard-L** [comment]
Sure, done.
