### ISSUE TITLE
OG bug: Fullscreen issue

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1645]
On my setup, there is either a black frame or a windowed border around the game:

Lara's Home:
![Screenshot (1079)](https://github.com/LostArtefacts/TRX/assets/94776985/93de56fb-9c5f-4f14-96f5-89ac2d4f4e64)

After switching to windowed and back to fullscreen by toggling F12.
![Screenshot (1080)](https://github.com/LostArtefacts/TRX/assets/94776985/38929c53-ca62-4a49-abc3-e584365e894f)

When starting a New Game (after skipping FMV):
![Screenshot (1081)](https://github.com/LostArtefacts/TRX/assets/94776985/563a9d70-487a-4a80-9dde-0239d5814b96)

Switching between apps (Alt+tab) makes the windowed border go away but the black frame remains:
![Screenshot (1082)](https://github.com/LostArtefacts/TRX/assets/94776985/ee4ed5ae-41bb-47d2-b623-10e704fc9ce1)

My setup if it's relevant:
- Windows 11
- Nvidia GPU
- 1440x1080

**Comment by Richard-L** [comment]
I have the same behaviour, although it's a bit unreliable?

I also had a case where I couldn't go back from Windowed to fullscreen anymore, but I couldn't find a way to reproduce it.

**Comment by aredfan** [comment]
Fixed in #1983.
