### ISSUE TITLE
Support for non 4:3 aspects

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1647]
Currently the game will force a 4:3 resolution when in windowed mode, and then proportions will look correct. When toggling to fullscreen, it will stretch to fill the screen. It would be nice if it would support non 4:3 displays dynamically, ie widescreen.

**Comment by rr-** [comment]
This can be achieved with the config tool and `/set aspect` now. Supported resolutions are 16:9, 4:3 and any. Trying to use mismatching aspect ratios will always result in letterboxing rather than stretching.
