### ISSUE TITLE
Loading menu displaced in Main Menu

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1649]
![image](https://github.com/LostArtefacts/TRX/assets/4934209/01267b14-dc84-4a71-ab02-2b6b2c62b9fc)

I believe this only started happening when at least one (or two) saves existed.

**Comment by rr-** [comment]
I can't replicate it @Richard-L

**Comment by Richard-L** [comment]
Hmm, it doesn't happen always for me either. I'll try to observe it more in hopes to know how to replicate.

**Comment by Richard-L** [comment]
I can no longer reproduce this myself. Will reopen should it re-occur.
