### ISSUE TITLE
TRX bug: different camera behaviour when Lara collects the first scion piece

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1682]
#1678 

_________________________

**Latest dev snapshot:**

https://github.com/user-attachments/assets/474d50b7-3ed3-4291-9f96-1f5894e5e6a7

**PR build:**

https://github.com/user-attachments/assets/de3d9d14-c995-4169-86cf-9dd24cb8ec96

**Comment by rr-** [comment]
Fixed in the PR

**Comment by aredfan** [comment]
Confirmed. 👌
