### ISSUE TITLE
Passport animate in is too fast when exiting to main menu

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1704]
It's so fast that you basically don't see it.

https://github.com/user-attachments/assets/6574d384-12cf-4a27-9138-e849ba12e0c5

**Comment by Richard-L** [comment]
I could test OG now to determine bug origin, and it's not present when using Tomb2.exe

**Comment by walkawayy** [comment]
@Richard-L can you test again on the latest development snapshot? I can't reproduce this. Also maybe @aredfan could check.

**Comment by Richard-L** [comment]
> @Richard-L can you test again on the latest development snapshot? I can't reproduce this. Also maybe @aredfan could check.

Sorry I wasn't able to verify but I'm sure it's fine 👌
