### ISSUE TITLE
TRX bug: issue with saving Winston

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1735]
**Dev snapshot:** 0.5-97-g05dc05e (latest)

________________

**Steps to reproduce:**

1. `/play 0`
2. Have Lara stand in the position shown in the screenshot below
3. `/save 1`
4. `/load 1`
5. Winston disappears

It's also possible for Winston to reappear if Lara is near him, but not always.

![Screenshot](https://github.com/user-attachments/assets/f1585580-1975-458a-a822-ad2a3a885107)

**Comment by rr-** [comment]
Does this also happen in 0.5?

**Comment by aredfan** [comment]
> Does this also happen in 0.5?

This issue doesn't happen in 0.5. I think it might've been introduced by #1720 as well.
