### ISSUE TITLE
TRX bug: Wreck of the Maria Doria savegame issue

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1736]
**Dev snapshot:** 0.5-97-g05dc05e (latest)

____________________

**Steps to reproduce:**

1. Start up TR2X
2. `/play 8`
3. `/save 1`
4. `/exit` and start up OG TR2
5. Load the savefile
6. This causes a abnormal program termination

**Comment by rr-** [comment]
Thanks - is there any other level like this? This is likely a regression from #1720.

**Comment by aredfan** [comment]
> Thanks - is there any other level like this? This is likely a regression from #1720.

Nope, all the other levels load fine. I've checked this by making a savegame for each level in TR2X, then loaded each one in OG.

**Edit:** Oh wait, gym is affected as well.
