### ISSUE TITLE
TR1: Cannot go left while walking forward

### ISSUE THREAD

**Issue by absolutelynothinghere** [LostArtefacts/TRX#1737]
When Lara is walking (not running) forward, she cannot go left, only right. Is this normal?

I've tested this on TRX-tr1 4.5.1 on Linux.

**Comment by rr-** [comment]
I think it's likely that you're experiencing keyboard ghosting – for some keyboard models, pressing too many keys at once fails to register certain combinations.

**Comment by absolutelynothinghere** [comment]
> keyboard ghosting

I think that's unlikely, the game already handles other multi key presses without issue. Plus I can walk to the right just fine... FWIW I use the [Alt] key for walking and the arrow keys for direction, does that work on your end?

Side note: I just reproduced the issue on the current `develop` branch.

**Comment by aredfan** [comment]
I'm not able to reproduce this issue even if I have Alt assigned to walk.

@absolutelynothinghere can you check if your keyboard is ghosting in this [demo](https://www.microsoft.com/applied-sciences/projects/anti-ghosting-demo#:~:text=A%20quick%20way%20to%20find,ASDW%20keys.)?

**Comment by absolutelynothinghere** [comment]
@aredfan I tried the demo and there was no ghosting, both [Alt]+[<--] and [Alt]+[-->] work.

**Comment by rr-** [comment]
Does the issue only happen with the Alt key, or are other keys affected too? It might be your DM or shortcut keyboard settings messing with the game inputs. We don't have any special settings for Alt, and I can't seem to replicate the problem on Linux from my end either.

**Comment by Richard-L** [comment]
@absolutelynothinghere can you try your desired inputs with this and see if they all register? https://drakeirving.github.io/MultiKeyDisplay/

**Comment by absolutelynothinghere** [comment]
> MultiKeyDisplay

@Richard-L Ok [Alt]+[/\\]+[<--] doesn't register here, so this is most probably not a TRX issue... What would you recommend I do?

>Does the issue only happen with the Alt key

Yes, I set a different key for walking and it works flawlessly.

**Comment by Richard-L** [comment]
This means it's after all a keyboard ghosting issue sadly, and you'll be forced to try out combinations with the tool that work, and then remap accordingly in the game.

On all non-gaming keyboards I have the same issue as you, where I used the numpad for directions as they are much less prone to ghosting. Hope that's an option for you.

**Comment by absolutelynothinghere** [comment]
Alright, thank you very much for your help.
