### ISSUE TITLE
TRX bug: the camera is more rigid when Lara is walking down bridges

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1751]
#1750 

**Save:** [savegame.zip](https://github.com/user-attachments/files/17507043/savegame.zip)
____________________________

**PR:**

https://github.com/user-attachments/assets/95d75499-4b2f-4254-a92b-8a9fb647d0d6

**OG:**

https://github.com/user-attachments/assets/f4a97ec3-a3a5-40df-9db9-85d497e4ad2a

**Comment by rr-** [comment]
@aredfan should be now fixed in the newest build at #1750.

**Comment by aredfan** [comment]
@rr- can confirm this issue is now fixed. 👍
