### ISSUE TITLE
TR1: Exploding mummy kills Lara even when far away

### ISSUE THREAD

**Issue by absolutelynothinghere** [LostArtefacts/TRX#1758]
Hello again, sorry to bother you with all these issues.

In the TR1 level "Obelisk of Khamoon" there are mummies that explode when killed, dealing damage to Lara unless she is sufficiently far away. In TR1X these mummies always insta-kill Lara even when she is far away.

As you can see in the video below, Lara is standing on one end of a bridge while a mummy stands on the other end, just within her line of fire. When Lara shoots the mummy and it explodes, she immediately dies despite standing far away with full health.

The save file from the video: [save_tr1_11.dat.gz](https://github.com/user-attachments/files/17531136/save_tr1_11.dat.gz)

https://github.com/user-attachments/assets/3256a8db-b6a2-43fc-9525-a03ffc8c80db

**Comment by Richard-L** [comment]
Sadly the video is bugged for me. Mostly just shows black (?)

**Comment by absolutelynothinghere** [comment]
Ok do either of these videos work?

[mummy_bomb_vp9+opus.webm](https://github.com/user-attachments/assets/c6e3e31a-a271-4fb7-9463-04f09ec62da2)

[mummy_bomb_vp9+vorbis.webm](https://github.com/user-attachments/assets/f161e6d2-5507-4d1c-86fe-6ecbfc24ddde)

**Comment by Richard-L** [comment]
Yep, both work. Thanks for updating 👍

**Comment by lahm86** [comment]
I can't replicate this with the provided save (or otherwise). Is it the latest build where this happens for you, and is it Windows, Linux or Mac?

Edit: I see it is 4.5.1 from your video.

**Comment by absolutelynothinghere** [comment]
It's version 4.5.1 on Linux, I compiled it myself using Zig CC. If you'd like the library versions used I can put together a list.

My executable is here: [TR1X.gz](https://github.com/user-attachments/files/17530195/TR1X.gz)

**Comment by absolutelynothinghere** [comment]
Update: I just recompiled version 4.5.1 with no optimizations (`-O0`) and the problem seems to have been fixed... I guess that helps?

**Comment by yoqto** [comment]
I threw your binary into a docker container and can confirm Lara dying with your binary. My local build with GCC 14.2.1 and `-O3` does not kill Lara when the mummy goes down on your save. So it seems your compiler is messing up in some of its optimizations.

**Comment by absolutelynothinghere** [comment]
That makes sense, thank you. The problem persisted with `-O2` and even `-O1` so I suppose `-O0` is the way to go...

**Comment by rr-** [comment]
Let's keep this open. We can't have platform-dependent arithmetic in our code.

**Comment by yoqto** [comment]
Beware, armchair debugging:

* When the mummy dies, it calls `Effect_ExplodingDeath` with `damage` `0x7FFF` (32767 decimal). That's way more than one of Torso's parts (250) or a centaur's (100).
* A bit later, `BodyPart_Control` calls `Lara_IsNearItem` with `distance` being 65534 (`damage * 2` via damage being stored as the effect's `counter`).
* `SQUARE(distance)` in `Item_IsNearItem` is 4294705156 (aka -262140 for `int32_t`).
* With Zig 0.13.0 and Clang 19.1.2, the `SQUARE(x) + SQUARE(z) <= SQUARE(distance)` part of the `if` in `Item_IsNearItem` passes -> Lara takes damage from multiple (all?) body parts as they're deemed close enough to her.
* With GCC 14.2.1, however, this is not the case. Maybe 65534^2 is stored in a 64bit register? Neither C nor x86 asm are my strong suit, much less efficiently debugging them. At any rate: no significant damage is dealt and Lara lives.

Declaring the `distance` parameter of `Item_IsNearItem` as `uint32_t` lets Lava live when built with any of the three compilers on my machine. Hope this helps?!

**Comment by rr-** [comment]
Thank you @yoqto that is really helpful! We'll aim to include a fix in the next release.

**Comment by absolutelynothinghere** [comment]
I tried the solution described by @yoqto and it indeed solves the problem!

Here's a patch for TR1X 4.5.1:

```patch
--- a/src/tr1/game/items.c
+++ b/src/tr1/game/items.c
@@ -314,7 +314,7 @@
     return changed;
 }
 
-bool Item_IsNearItem(const ITEM *item, const XYZ_32 *pos, int32_t distance)
+bool Item_IsNearItem(const ITEM *item, const XYZ_32 *pos, uint32_t distance)
 {
     int32_t x = pos->x - item->pos.x;
     int32_t y = pos->y - item->pos.y;
--- a/src/tr1/game/items.h
+++ b/src/tr1/game/items.h
@@ -25,7 +25,7 @@
 int32_t Item_GlobalReplace(
     GAME_OBJECT_ID src_object_id, GAME_OBJECT_ID dst_object_id);
 
-bool Item_IsNearItem(const ITEM *item, const XYZ_32 *pos, int32_t distance);
+bool Item_IsNearItem(const ITEM *item, const XYZ_32 *pos, uint32_t distance);
 bool Item_Test3DRange(int32_t x, int32_t y, int32_t z, int32_t range);
 bool Item_TestBoundsCollide(ITEM *src_item, ITEM *dst_item, int32_t radius);
 bool Item_TestPosition(
```

**Comment by rr-** [comment]
> I tried the solution described by @yoqto and it indeed solves the problem!
> 
> Here's a patch for TR1X 4.5.1:
> 
> ```diff
> --- a/src/tr1/game/items.c
> +++ b/src/tr1/game/items.c
> @@ -314,7 +314,7 @@
>      return changed;
>  }
>  
> -bool Item_IsNearItem(const ITEM *item, const XYZ_32 *pos, int32_t distance)
> +bool Item_IsNearItem(const ITEM *item, const XYZ_32 *pos, uint32_t distance)
>  {
>      int32_t x = pos->x - item->pos.x;
>      int32_t y = pos->y - item->pos.y;
> --- a/src/tr1/game/items.h
> +++ b/src/tr1/game/items.h
> @@ -25,7 +25,7 @@
>  int32_t Item_GlobalReplace(
>      GAME_OBJECT_ID src_object_id, GAME_OBJECT_ID dst_object_id);
>  
> -bool Item_IsNearItem(const ITEM *item, const XYZ_32 *pos, int32_t distance);
> +bool Item_IsNearItem(const ITEM *item, const XYZ_32 *pos, uint32_t distance);
>  bool Item_Test3DRange(int32_t x, int32_t y, int32_t z, int32_t range);
>  bool Item_TestBoundsCollide(ITEM *src_item, ITEM *dst_item, int32_t radius);
>  bool Item_TestPosition(
> ```

I'm glad to hear that the solution worked for you! We might explore a slightly different approach for the final solution, however; likely something akin to what we do in `Math_GetVectorAngles`, since an additional 1 bit of precision might still not be enough for larger level geometries.

**Comment by walkawayy** [comment]
@absolutelynothinghere can you test the latest [development snapshot](https://github.com/LostArtefacts/TRX/releases/tag/latest) TR1X build and see if it fixes the issue?

**Comment by absolutelynothinghere** [comment]
@walkawayy I just compiled the game and the issue is fixed! Thank you all very much.

**Comment by Toumlab** [comment]
Hi Absolutelynothinghere !

I would be really grateful if you could share with us the exact procedure and dependancies you’ve been using to compile TR1X using Zig CC. I’m on Linux, and I have tried to no avail…

I’ve seen on the following page (https://github.com/LostArtefacts/TRX/issues/1535) that your binary is compatible with GLIBC 2.7 and upwards, and that’s something I would like to get as well for more recent (and also upcoming) versions of TR1X (and TR2X as well:) )

I was able to compile TR1X + sdl2 + ffmpeg with Meson, Make and Ninja in the past (and it was cumbersome!), but there is no longer a makefile in the TR1X sources, nor any zig-specific build files, obviously !

Thanks for your help !

**Comment by absolutelynothinghere** [comment]
Hello Toumlab :)

My procedure is quite simple; TRX is built with all its dependencies in a clean [chroot](https://wiki.archlinux.org/title/Chroot), where Zig CC is the sole compiler with target GLIBC 2.7.

I start with a completely empty directory for the chroot, then copy over the Zig compiler and some basic utilities. These programs are all fully statically linked, so no external libraries are pulled into the chroot. I then proceed to compile libX11, glvnd, ALSA, SDL2...etc and finally TRX. I do not compile GLIBC because Zig can already target every GLIBC version out of the box... There are of course some tricks and workarounds throughout this process but it's mostly straightforward.

I would love to get into more detail and share my scripts, but I need to ask permission from the repo owners first as this may turn into a very long post. @LostArtefacts is it okay to discuss this here?

**Comment by rr-** [comment]
I think this should be made into a Discussion page so as not to clobber this thread.

**Comment by Toumlab** [comment]
Sure rr- it makes sense. I'll open a discussion thread asap, thanks!
