### ISSUE TITLE
TRX bug: potential crash when z-buffer is disabled

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1761]
**Regression since:** [0.5](https://github.com/LostArtefacts/TRX/releases/tag/tr2-0.5)
**Save:** [savegame_4.zip](https://github.com/user-attachments/files/17529974/savegame_4.zip)

________________________

The game crashes when Lara swims towards the divers in the attached savegame. This is only when z-buffer is disabled (F7).

________________________

Steps to reproduce without the savegame:

1. Disable z-buffer (F7)
2. `/play 10`
3. `/tp 22`
4. swim in the water towards the divers

**Comment by rr-** [comment]
![shot-2024-11-01_23-59-16 mp4-00:00:05 367](https://github.com/user-attachments/assets/17f8564a-0c21-4751-903e-23f4a535d2dd)

Oops.

**Comment by rr-** [comment]
I think this is actually a regression from 0.2.
