### ISSUE TITLE
TR2X: improve screenshot support

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#1773]
Currently 8-bit screenshots get saved as .pcx, 16-bit screenshots get saved as .tga, while 24-bit and 32-bit screenshots simply do not work at all (#1766). TR1X has the option to choose either jpg or png as the format, puts the screenshots in their own directory, and has a naming conflict resolver. We should implement all of that in TR2 as well.

**Comment by Richard-L** [comment]
Just out of curiosity, and I expect the answer to be "no", but: Do either of these vintage formats offer any advantage over PNG?

**Comment by rr-** [comment]
No, it's just pixel data.
