### ISSUE TITLE
TR2X bug: the savegame number goes dark in specific circumstances

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1814]
**Dev snapshot:** 4.5.1-183-g9a3a2dd (latest)

________________

**Steps to reproduce:**

1. Play any level and create a savegame in the top slot
2. Exit the game
3. Start up the game and open the passport to the load game page
5. Scroll down until the savegame is no longer visible
6. Deselect the passport
7. Select the passport again and scroll up - the savegame number should be dark

![20241102_194526_Laras_Home](https://github.com/user-attachments/assets/003ae83f-c134-4dc0-8272-d9fa7e2ac5e3)

**Comment by rr-** [comment]
Great catch – thank you.
