### ISSUE TITLE
OG bug: possible to increment kills when destroying the scion

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1819]
When Lara shoots the scion - save while the explosion sprites are present.  Load the savegame and Lara remains locked on the (now invisible) scion and has another opportunity to destroy it again.

Lara staying locked on the scion is an OG bug present in TombATI. I've not confirmed if this affects the kill stats but it's highly likely.

https://github.com/user-attachments/assets/589929d2-f64e-4b23-8e29-41ea7835403a

**Comment by Richard-L** [comment]
Very good attention to this kind of detail 🙏
