### ISSUE TITLE
Feature request: ability to examine pickup items

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#1821]
This suggestion came from Leoc1995. Add the ability to define additional/multiline text for pickup/puzzle/key items so players can examine them in the inventory.

**Comment by Richard-L** [comment]
Likely mainly of interest to TRLEs, but it would be fun to collect sensible info to show for the base games too. To brainstorm: Maybe from game leaflets or strategy guides, or even our own texts.
