### ISSUE TITLE
[Custom Level] Game freezes with altered Switch animation

### ISSUE THREAD

**Issue by Raildex** [LostArtefacts/TRX#1833]
I am in the process of creating a custom level.
For that I imported the TR2 button to a TR1 WAD and swapped out the lever up/down anims with the button push.

When You "press" the button once, it works, but once you press it again the game immediately freezes and plays the sound effect of the button on the same frame (even though it is supposed to be played in a different frame)
[Engine.tar.zip](https://github.com/user-attachments/files/17632573/Engine.tar.zip)

When you start the level, the button is immediately to the right side of lara

The logs do not tell anything.

**Comment by lahm86** [comment]
If you change the state ID of animation 64 to `SWITCH_UP` (41) it should work. The problem is you have 40 in both animations, so `Lara_AnimateUntil` is getting stuck.
