### ISSUE TITLE
"Failed to create device" when toggling fullscreen

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1842]
![image](https://github.com/user-attachments/assets/1c2270ee-d272-40e7-96ae-c63df09a3ac7)

Using: https://github.com/LostArtefacts/TRX/releases/tag/tr2-0.6

When the game starts (in windowed mode), and you toggle fullscreen with ALT+ENTER, the error appears. ~~I don't have access to vanilla PC TR2, and the vanilla tomb2.exe doesn't do anything anymore now when I try to run it. So can't verify OG bug on this hardware or not.~~ This was the case because TR2X was still also running in the background.

In OG, it attempts to go to fullscreen, fails without notice, and after some time of a black screen returns to windowed mode.

**Comment by rr-** [comment]
What if you run the setup window and try to start in fullscreen mode from start?

**Comment by Richard-L** [comment]
I forget: Do I need to run TR2X.exe -setup or tomb2.exe -setup?

**Comment by rr-** [comment]
TR2X.exe -setup.

**Comment by Richard-L** [comment]
https://github.com/user-attachments/assets/40454467-a0f5-420e-a7f3-8179062efbf4

This will work, albeit 4:3 aspect ratio is disregarded.
