### ISSUE TITLE
Separate Build for TRX and Custom Levels?

### ISSUE THREAD

**Issue by Raildex** [LostArtefacts/TRX#1846]
As a level designer, I have a clear vision of how my level should be played and do not want some options of the global ConfigTool to be applied to my level.

Would it be possible to provide two different binaries? One for TR1X - TR1 Community edition and one specifically for custom levels where all the config is read from gameflow.json?

**Comment by rr-** [comment]
I understand your perspective as a level designer and the importance of maintaining your vision. While offering different binaries isn't feasible for us, I think we could add a feature to freeze certain options in the gameflow. This might allow builders to restrict changes to things like water color or rendering distances. Could you let us know which specific options are causing the most difficulty for you?

In the meantime, a possible solution could be to include a predefined config with your level and omit the config tool.
