### ISSUE TITLE
Removing Animation injection and enabling underwater roll results in sliding when pressing roll

### ISSUE THREAD

**Issue by Raildex** [LostArtefacts/TRX#1847]
When disabling animation injections but keep the option for underwater roll enabled, you can hold ROLL underwater to make lara slide at a steady rate

https://github.com/user-attachments/assets/80d721dc-83f8-4ba7-8bb4-ebf92f0d367a

**Comment by Richard-L** [comment]
Isn't something very similar to this called "the dolphin" in TR1 speedrunning?

I'm sure it's unrelated, but just came to my head from the video.
