### ISSUE TITLE
TR2X bug: visible seams on thin walls

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1848]
**Regression since:** [0.6](https://github.com/LostArtefacts/TRX/releases/tag/tr2-0.6)
_______________

Lara's Home, rooms 9 and 55.
![1](https://github.com/user-attachments/assets/3e1cba2d-0a62-4d2d-bd3f-fe9dfec99a07)
![2](https://github.com/user-attachments/assets/fec93223-02b7-4cf1-8b41-e4753168ed78)

The Dragon's Lair, room 1.
![3](https://github.com/user-attachments/assets/98505faf-2503-4e9b-981d-2fb642cc1ba1)

**Comment by rr-** [comment]
I have a hunch that #1866 might be just the fix for this issue as well. Can we confirm?

**Comment by rr-** [comment]
Fixed by #1866.
