### ISSUE TITLE
TR2X bug: disappearing static meshes in Lara's Home

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1870]
**Dev snapshot:** 0.6-14-g31aeefa

__________________

The static meshes can disappear and reappear depending on where the camera is positioned.

**Dev snapshot:**
![20241111_183442_Laras_Home](https://github.com/user-attachments/assets/3e554e82-cc12-4c63-b0c2-1555c48693ec)

**Stable:**
![20241111_184831_Laras_Home](https://github.com/user-attachments/assets/d9fa0f6b-6b11-4bbc-94f4-a48251dafdc0)

**Comment by rr-** [comment]
Broken in 5cf6c429
