### ISSUE TITLE
TR2X bug: Lara keeps walking after death

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1880]
**Regression since:** [0.1](https://github.com/LostArtefacts/TR2X/releases/tag/0.1)
_______________

**Steps to reproduce:**

1. `/play 12`
2. `/kill monk`
3. `/hp 50`
4. Have Lara walking when the nearby enemies ambush her

In OG, when hp drops to 0, Lara would stop there and collapse.

**Comment by rr-** [comment]
Ouch!
