### ISSUE TITLE
TR2X bug: different camera position when Lara pulls the dagger

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1886]
**Dev snapshot:** 0.6-42-ge1f77f9

____________________

**Dev snapshot:**
![20241112_204936_The_Dragons_Lair](https://github.com/user-attachments/assets/001d6f2b-e472-4250-a17b-0d8b40d7c440)

**0.6/OG:**
![20241112_204907_The_Dragons_Lair](https://github.com/user-attachments/assets/47b5e1e9-ea5e-4767-850e-b00791422a11)

**Comment by rr-** [comment]
This is most likely related to my FOV / viewport changes.

**Comment by Richard-L** [comment]
I actually kind of prefer the more zoomed out view.

But aredfan's right, it seems to be closer in vanilla (also PS1: https://youtu.be/U_l52zvFZAo?si=4UnlSdbrNQgXqEds&t=718)
