### ISSUE TITLE
The game does not work

### ISSUE THREAD

**Issue by antonio3687** [LostArtefacts/TRX#1895]
[TR1X.dmp](https://github.com/user-attachments/files/17733492/TR1X.dmp)
[TR1X.log](https://github.com/user-attachments/files/17733493/TR1X.log)
[Tree.txt](https://github.com/user-attachments/files/17733538/Tree.txt)

Good afternoon, first of all, thank you very much for the great work you are doing, I am very proud of you. I attach three files. I can not play the level of Lara's house or the game, starts the video and the loading screen and then I close the game, I do not know what can happen. By the way how to play the demo level that I can not play. Thank you very much.

**Comment by rr-** [comment]
Hi @antonio3687 thank you for the detailed report. Can you please try the [development snapshot](https://github.com/LostArtefacts/TRX/releases/tag/latest) that provides more debugging information (that's normally not available in release builds due to performance concerns)? Thanks!

**Comment by antonio3687** [comment]
I have tested with the latest version TR1X-4.5.1-277-g1e6acce-Windows
Best regards.

**Comment by rr-** [comment]
Thanks. While the stack trace doesn't offer immediate hindsight, I see that you have installed the game in C:\Program Files (x86). Maybe you could try copying the game to a different folder, such as your desktop? Many users seem to experience permission-related problems when installing it there.

**Comment by antonio3687** [comment]
Hi, I have tried to change the folder to the desktop and it doesn't work, with the final version 4.5.1 if the game works for me. If you want I can pass you the folder. Thank you very much.

**Comment by lahm86** [comment]
@antonio3687 Could you try the build in the attached file and - assuming this also crashes for you in the same way - send the `TR1X.log` file that's produced? I've added some additional logging to see if we can identify the problem.
[TR1X.zip](https://github.com/user-attachments/files/17787895/TR1X.zip)

Thanks.

**Comment by antonio3687** [comment]
Good evening, it is still not working, I attach the log file and the dmp file. Thank you very much.
[TR1X.dmp](https://github.com/user-attachments/files/17788191/TR1X.dmp)
[TR1X.log](https://github.com/user-attachments/files/17788192/TR1X.log)

**Comment by lahm86** [comment]
Thank you @antonio3687. So it seems that the game is having a problem with some music tracks - "welcome to my home" in your last test, and the Caves ambience in the initial log report. Could you send your copy of `music/track26.flac` and `music/track57.flac` here?

Interestingly, the title track seems to work (I'm assuming you can actually hear it). Did you use the installer to download the music tracks or did you acquire them from somewhere else?

Thanks.

**Comment by antonio3687** [comment]
[music.zip](https://github.com/user-attachments/files/17790927/music.zip)
[Game](https://wetransfer.com/downloads/72dc9e97e0b7d2203d29d9a951ee47eb20241117150359/b5ef24?t_exp=1732115039&t_lsid=21a176b6-cfd3-4991-81ed-824f68c1a6c6&t_network=link&t_s=download_link&t_ts=1731855852&utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)
Good afternoon, the two audios can be heard, the audios are from the TombATI version. I attach my game folder in case you want to take a look at it.
[TombAti](https://www.glidos.net/tombati.html)
I have also tried with yours and it does not work:
[TRX](https://github.com/LostArtefacts/TRX/tree/develop/docs/tr1)
What is strange is that with the final version 4.5.1 the game works.
Thank you very much and best regards.

**Comment by Richard-L** [comment]
Maybe a screen recording from startup to the problems and experience you're having would help? I feel like there might be nuances missed here.
We must help you enjoy TRX Antonio :)

**Comment by antonio3687** [comment]
[video1.webm](https://github.com/user-attachments/assets/69e42b7f-2f10-4b27-9565-d2ea513206b4)
[video2.webm](https://github.com/user-attachments/assets/c8d2ff0e-9f78-42ed-be21-526d25bd25ed)
Good afternoon, I attach two videos, one of the beginning of the game and another of Lara's house. Greetings and thank you very much.

**Comment by rr-** [comment]
Hi, thank you for the continued reports. I've identified the issue and a fix should be available shortly.

**Comment by antonio3687** [comment]
Hello, now it works, thank you very much for your work and sorry for the inconvenience. Best regards.
TR1X-4.5.1-312-g0777355-win.zip
