### ISSUE TITLE
TR2X bug: some music triggers loop and others don't repeat

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#1899]
An example is the trigger at the zip line in Great Wall. Although the trigger isn't one-shot, in OG it only plays once if you stand on the tile, whereas in TR2X it loops until you move away.
One-shot music triggers behave fine.

Another issue is if you complete the assault course and get a best time, then complete and beat the time again without triggering any other music tracks, Lara does not repeat the "best time yet" line at the end.

Regression from 0.2.

**Comment by rr-** [comment]
I think we just need to eliminate `g_CD_TrackID` in favor of `int32_t Music_GetCurrentTrack(void) { return m_TrackCurrent; }` in `music_main.c`.
