### ISSUE TITLE
TR2X bug: the mercenary hits the skidoo late

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1906]
**Dev snapshot:** 0.6-90-gf4162df (latest)

___________________

In the third demo, observe where the blood splatter ends up in each of the screenshots below.

___________________

**OG:**
![1 3 OG](https://github.com/user-attachments/assets/840fe52f-f7d0-4a3a-bb75-45f1702df69c)

**0.6:**
![1 2 0 6](https://github.com/user-attachments/assets/85e7e0a8-3f66-4d8c-a0f4-4db3b23a36ca)

**Dev snapshot:**
![1 1 Dev](https://github.com/user-attachments/assets/6cfc24e1-d01e-4320-b943-86a6a5b1ecd8)
The mercenary hits Lara a _tiny_ bit late as opposed to the first 2 screenshots.
_______________________

**OG:**
![2 3 OG](https://github.com/user-attachments/assets/a54faf3a-1473-4d81-a560-14fd437ebc99)

**0.6:**
![2 2 0 6](https://github.com/user-attachments/assets/f12fd96a-eb86-4c26-9661-610b3653484d)

**Dev snapshot:**
![2 1 Dev](https://github.com/user-attachments/assets/a68cfa4f-dfa6-4f45-9b8f-80ec723f6717)

**Comment by rr-** [comment]
Regression introduced in f166dcb65afda2279a247641dc601bb9128c223f.

**Comment by rr-** [comment]
Item 32 is activated on frame 1086 prior to that change, whereas it gets activated on frame 1087 from the affecting change onwards. Here's the patch that I used to measure this:

```patch
diff --git a/src/tr2/decomp/decomp.c b/src/tr2/decomp/decomp.c
index 304a2dcc..06b45b98 100644
--- a/src/tr2/decomp/decomp.c
+++ b/src/tr2/decomp/decomp.c
@@ -1070,9 +1070,11 @@ void __cdecl CutscenePlayerGen_Initialise(const int16_t item_num)
     item->dynamic_light = 0;
 }
 
+int32_t g_Frames = 0;
 int32_t __cdecl Level_Initialise(
     const int32_t level_num, const GAMEFLOW_LEVEL_TYPE level_type)
 {
+    g_Frames = 0;
     g_GameInfo.current_level.num = level_num;
     g_GameInfo.current_level.type = level_type;
 
diff --git a/src/tr2/game/game.c b/src/tr2/game/game.c
index 66705f66..0add1418 100644
--- a/src/tr2/game/game.c
+++ b/src/tr2/game/game.c
@@ -179,8 +179,10 @@ int32_t __cdecl Game_Control(int32_t nframes, const bool demo_mode)
     return 0;
 }
 
+extern int32_t g_Frames;
 int32_t __cdecl Game_Draw(void)
 {
+    g_Frames++;
     Room_DrawAllRooms(g_Camera.pos.room_num);
     Overlay_DrawGameInfo(true);
     S_OutputPolyList();
diff --git a/src/tr2/game/room.c b/src/tr2/game/room.c
index 320cc133..623d6185 100644
--- a/src/tr2/game/room.c
+++ b/src/tr2/game/room.c
@@ -512,6 +512,8 @@ void Room_PopulateSectorData(
     } while (!FLOORDATA_IS_END(fd_entry));
 }
 
+extern int32_t g_Frames;
+#include <libtrx/log.h>
 void __cdecl Room_TestTriggers(const int16_t *fd, bool heavy)
 {
     ITEM *camera_item = NULL;
@@ -658,6 +660,7 @@ void __cdecl Room_TestTriggers(const int16_t *fd, bool heavy)
             }
 
             if (!item->active) {
+                LOG_INFO("Activating item %d on frame %d", value, g_Frames);
                 if (g_Objects[item->object_id].intelligent) {
                     if (item->status == IS_INACTIVE) {
                         item->touch_bits = 0;
```
