### ISSUE TITLE
TR2X bug: issue with the final stats in SW mode

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1915]
**Regression since:** [0.6](https://github.com/LostArtefacts/TRX/releases/tag/tr2-0.6)

_______________________

![0 6](https://github.com/user-attachments/assets/5d3ebfbb-9a12-48c0-a58d-1bcb181656ef)

**Comment by rr-** [comment]
@aredfan since it's a regression since 0.6, does it mean it only exists in the development snapshots?

**Comment by aredfan** [comment]
@rr- nope, this bug is present on 0.6, at least on my end.

I've checked 0.5 too and the final stats displays normally in SW mode.

**Comment by lahm86** [comment]
Regression introduced in https://github.com/LostArtefacts/TRX/commit/2989b9b1c2e369a87590ab160406031e4f00c82a.
