### ISSUE TITLE
Accents in Spanish words

### ISSUE THREAD

**Issue by antonio3687** [LostArtefacts/TRX#1919]
![4 6](https://github.com/user-attachments/assets/74e7ea31-9d9f-465a-9826-62af527ea0a6)
![4 5 1](https://github.com/user-attachments/assets/1269fdea-7e3f-4ee6-ace1-36fb51114330)

Good afternoon, the accents in the Spanish words have disappeared, I attach two images, one that works in the final version 4.5.1 and one that does not work in version 4.6.
How do you play at the demo level?
Thank you very much.

**Comment by rr-** [comment]
Hi @antonio3687 as per the release notes, the accents need to be adjusted:

- `\{umlaut}`
- `\{hat}`
- `\{acute accent}`
- `\{grave accent}`

Unfortunately, there's currently no official support for the translated content so any changes to the gameflow files need to be presently made by hand.

**Comment by antonio3687** [comment]
Hi, can you give me an example of what it would look like? And is playing at the demo level by commands? Best regards.

**Comment by lahm86** [comment]
You can place the accent before the letter as follows in the gameflow:

`"INV_ITEM_COMPASS": "Br\\{acute accent}ujula",`

For playing the demo, there is information in #1378. You pass `-demo_pc` at the command line, but you will also need to acquire the demo PHD files and put them in a folder named `data_demo_pc` (see the demo gameflow).

**Comment by antonio3687** [comment]
Good evening, there is nothing for the letter ñ, is there? Thank you very much for the example of the accent and I have already been able to play the demo level. Thank you very much and best regards.

**Comment by Wronschien** [comment]
Hello, how comes entities must start with a double \ when the changelog in the release only states single \ ?

**Comment by lahm86** [comment]
> Good evening, there is nothing for the letter ñ, is there? Thank you very much for the example of the accent and I have already been able to play the demo level. Thank you very much and best regards.

Only the original accents are currently supported (these are the only glyphs available in the original level files).

**Comment by lahm86** [comment]
> Hello, how comes entities must start with a double \ when the changelog in the release only states single \ ?

This is standard in JSON (and programming in general) when you want the `\` to be part of the string, which it must be for the game to recognise it. If it were a single `\` within the quotes, it would be treated as an escape character, and I don't think the gameflow would even load as it would be parsed as invalid.

**Comment by Wronschien** [comment]
Oh I see, I don't know much about json and didn't know that this had to be escaped. Maybe this should be added in the changelog ?
Thanks for the reply.

**Comment by rr-** [comment]
I don't think a changelog entry is necessary for this change. The `"\\"` works as expected: it appears as `\` onscreen (as it used to be the case). Only if it's followed by a recognized sequence like `"\\{umlaut}"`, it will be replaced with an umlaut.
