### ISSUE TITLE
OG bug: missing death tiles in Temple of Xian

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#1920]
Room 91 has 6 sectors where Lara can stand in the lava.

![image](https://github.com/user-attachments/assets/f7962380-12dc-4132-86f2-3c6f41af1159)

**Comment by Richard-L** [comment]
There's another one in floating Island in this pit:
https://youtu.be/jmGZNr_vecQ?t=15m24s

Before the block is in you can stand there without catching fire.

**Comment by lahm86** [comment]
Thanks. The problem there would be the floor on top of the block would inherit the death property from below, so you wouldn't be able to stand there after dropping it. Ideally there should be a flipmap here so the tile would have different states. That's a bigger problem to inject at the moment.
