### ISSUE TITLE
Requires X11 on linux

### ISSUE THREAD

**Issue by exalented** [LostArtefacts/TRX#1927]
The `TRX 4.6 linux` release requires X11.

Without `env SDL_VIDEODRIVER=x11 ./TR1X` (or unsetting it from `wayland`) I get:
```
$ ./TR1X
specific/s_shell.c 266 main Game directory: /TR/
specific/s_shell.c 169 S_Shell_ShowFatalError Cannot initialize SDL: wayland not available
```
```
$ env SDL_VIDEODRIVER=x11 ./TR1X
specific/s_shell.c 266 main Game directory: /TR/
libtrx/game/input/backends/controller.c 378 M_FindController 0 controllers
specific/s_shell.c 372 S_Shell_CreateWindow Trying GL backend 3.3
..
libtrx/gfx/context.c 136 GFX_Context_Attach OpenGL renderer string: Mesa Intel(R) Arc(tm) A750 Graphics (DG2)
..
game boots fine..
```
It would be nice to not need x11 moving forward.
I believe the `ubuntu:latest` image needs wayland.
https://github.com/LostArtefacts/TRX/tools/tr1/docker/game-linux/Dockerfile

**Comment by rr-** [comment]
Hey @exalented can you please check the dev snapshot in #1929?

**Comment by exalented** [comment]
Only the bottom zip works. TY https://github.com/LostArtefacts/TRX/pull/1929#issuecomment-2488077203
