### ISSUE TITLE
Some symbols are not displayed in the game

### ISSUE THREAD

**Issue by bursoft-git** [LostArtefacts/TRX#1928]
Hello! Thank you for your hard and interesting work!
I am translating TR1X into Russian, and using a modified texture of standard symbols.
In this texture, the symbols "<" and "," are replaced with Russian "ы" and "ь". This worked well before, but in TR1X-4.6 these symbols are not displayed in the game. I tried to escape them in different ways, but with no luck.
How can I fix this without redrawing the texture? Thank you!)
![2024-11-20_100324_cr](https://github.com/user-attachments/assets/b119e346-5223-496f-8c98-efedd38a75eb)

**Comment by rr-** [comment]
Hi, we have recently changed the way the glyphs are handled. Could you please provide us with a list of sprites? Going forward, we can aim to bundle them in the next stable version.

**Comment by bursoft-git** [comment]
> Could you please provide us with a list of sprites?

Yes, of course! Can you tell me in more detail what (and how exactly) I should provide? I don't fully understand, sorry

**Comment by rr-** [comment]
> > Could you please provide us with a list of sprites?
> > Yes, of course! Can you tell me in more detail what (and how exactly) I should provide? I don't fully understand, sorry

Thanks – dropping a zip file with png files, ideally annotated with each glyph they represent, would be ideal.

**Comment by bursoft-git** [comment]
> Thanks – dropping a zip file with png files, ideally annotated with each glyph they represent, would be ideal.

Here are all the sprites that I used to translate. Sprites that are not displayed in the game are in a separate folder.
[RU_sprites.zip](https://github.com/user-attachments/files/17832063/RU_sprites.zip)

**Comment by bursoft-git** [comment]
[rr-](https://github.com/rr-) 
I checked the build https://github.com/LostArtefacts/TRX/commit/47a3d5452eaee5426d6d4dd5d16336aa54705d2d, and it works fine (except for the latin letters g j p q y)
![TR1X_2024_11_22_19_42_45_365](https://github.com/user-attachments/assets/e0dad8bf-d259-4d68-acba-1e936121bb0e)

But the build https://github.com/LostArtefacts/TRX/pull/1933/commits/c76de3fb8e18a04176d720d561dcf04106375457 does not work for me, the letters are not visible at all

This is a great implementation, thanks! I rechecked the archive RU_sprites.zip that I posted above, correct all the inaccuracies, and added the missing letters (Ё Ж Щ Ъ Ы Ь Э ъ э ё). now it contains all the letters of the Russian alphabet (66)

[RU_sprites-new.zip](https://github.com/user-attachments/files/17874120/RU_sprites-new.zip)

**Comment by rr-** [comment]
@bursoft-git please hold on, that PR is a heavy WIP and will be unlikely to be finished this week.
