### ISSUE TITLE
TR2X bug: push block collision isn't being saved

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1930]
**Dev snapshot:** 0.6-170-gcbae162 (latest)

_____________

**Steps to reproduce:**

1. `/play 1`
2. `/tp push`
3. move the block
4. `/save 1`
5. `/load 1`

**Comment by lahm86** [comment]
Although not present in the 0.6 release, this stems back to https://github.com/LostArtefacts/TRX/pull/1891/commits/0ceec1b554648196d9975ea7830c08dab9aa0151 and only impacts the debug build.
