### ISSUE TITLE
OG bug: wolves and bats have transparent eyes

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#1945]

**Comment by aredfan** [comment]
The wolves in levels 1-4 are affected by this bug.

Screenshot for reference:
![image](https://github.com/user-attachments/assets/2a49ea60-335c-41ca-bf38-bfd2cce010d7)

**Comment by lahm86** [comment]
Adding bats too for tackling in the same issue (Caves and Vilcabamba).
https://github.com/LostArtefacts/TRX/discussions/736#discussioncomment-10857802
