### ISSUE TITLE
TR1X Lost Valley

### ISSUE THREAD

**Issue by Arc-Leviathan** [LostArtefacts/TRX#1948]
For some reason, an invisible wall is blocking the tile before the door at the end of Lost Valley.
I had a search through the issues tab but couldn't find any other reports on this.

Has anyone else experienced this anomaly?

**Comment by aredfan** [comment]
Confirmed to be a regression since [4.6](https://github.com/LostArtefacts/TRX/releases/tag/tr1-4.6).
