### ISSUE TITLE
TR1X bug: incorrect pixel format and stride pair on some devices

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#1979]
This occurs on any picture display e.g. Eidos logo, title screen.

![image](https://github.com/user-attachments/assets/5fb12c29-b19c-4e32-92f8-1f1e5c404744)
[TR1X.log](https://github.com/user-attachments/files/17970170/TR1X.log)

**Comment by rr-** [comment]
Can someone ask the original reporter whether the newest dev snapshot fixes this issue? Thanks.

**Comment by lahm86** [comment]
Leoc1995 has confirmed the problem has been resolved.
