### ISSUE TITLE
TR2X bug: the copyright screen and intro FMVs doesn't display

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1984]
**Dev snapshot:** 0.6-238-g1860bdf (latest)

________________

I first noticed this issue while testing #1981, but I forgot to investigate it.

- The copyright screen is just a black screen. Other pictures like credits are working as expected.
- The intro FMVs doesn't display but the sound is working. Other FMVs in-game are working as expected.

**Comment by rr-** [comment]
Hey @aredfan is it working as expected in #1983 ?

**Comment by aredfan** [comment]
@rr- Yes, the copyright screen and the intro FMVs are working in 1983, thanks for the heads-up. 👍
