### ISSUE TITLE
TR1X bug: visible artifacts on explosion sprites

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1985]
**Dev snapshot:** 4.6.1-73-g8fbcf5e

______________________________________

Notice the thin lines bordering the explosion sprites.

**Dev snapshot:**
![20241203_105428_Caves](https://github.com/user-attachments/assets/f839d414-9d94-4f9d-87b7-2eacf215d783)

**4.6.1:**
![20241203_105407_Caves](https://github.com/user-attachments/assets/b453859b-9a38-401e-81cc-47f785dfc2f6)

**Comment by Richard-L** [comment]
"No Laras were harmed in the making of this footage"
