### ISSUE TITLE
Wrong depth buffer clipping

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#2003]
![20241211_194553_City_of_Vilcabamba](https://github.com/user-attachments/assets/64103afa-4f82-4f86-8d12-bda565d2f188)

Certain objects, when viewed from the right angle, get weirdly clipped.
Present since very old versions. @aredfan it'd be nice if we could get a confirmation if TombATI does this too.

**Comment by aredfan** [comment]
@rr- The clipping issue is indeed present in TombATI as well. 👇 

![screenshot0000](https://github.com/user-attachments/assets/a63d7a60-cc5a-4ec8-8621-8fbcca1b5518)

**Comment by rr-** [comment]
Actually this is a duplicate of #819 which captures this much better.
