### ISSUE TITLE
OG bug: Obelisk keys are positioned slightly too low

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#2006]
**Copied over from 2004:**

> There's a new issue with the Obelisk keys being partially buried in the drawbridges.
> 
> **Edit:** The sprites are also partially buried in the DOS version - which doesn't suffer from the clipping issue. It's an OG bug. 
> 
> **Sprite pickups**
> 
> Dev snapshot
> ![1 1 Dev](https://github.com/user-attachments/assets/93dac4e9-8775-4f4d-abdf-7fa35d563f5d)
> PR build
> ![1 2 PR](https://github.com/user-attachments/assets/81df7e0f-fea4-4671-837b-584ae6536de8)
> 
> **3D pickups**
> 
> Dev snapshot
> ![2 1 PR](https://github.com/user-attachments/assets/c20cb87d-2136-4a5d-a43c-7d08f6011325)
> PR build
> ![2 2 PR](https://github.com/user-attachments/assets/85ab9586-ea5a-4c7f-8f73-4618180c8487)

**Comment by rr-** [comment]
Also when tackling this, let's remember to fix the origin point for the drawbridge object (items 19,20,21, and 22).

@lahm86 While playing with the injector, I put together a utility function that you might find handy:

```diff
diff --git a/src/Types/ItemBuilder.cs b/src/Types/ItemBuilder.cs
index 300bea0..c80a9b3 100644
--- a/src/Types/ItemBuilder.cs
+++ b/src/Types/ItemBuilder.cs
@@ -34,4 +34,30 @@ public abstract class ItemBuilder : InjectionBuilder
             },
         };
     }
+
+    protected static TRItemEdit NudgePosition<T>(TREntity<T> item, short itemIndex, short x = 0, short y = 0, short z = 0) where T : Enum
+    {
+        return new()
+        {
+            Index = itemIndex,
+            Item = new()
+            {
+                Angle = item.Angle,
+                X = item.X + x,
+                Y = item.Y + y,
+                Z = item.Z + z,
+                Room = item.Room,
+            },
+        };
+    }
+
+    public static TRItemEdit NudgePosition(TR1Level level, short itemIndex, short x = 0, short y = 0, short z = 0)
+    {
+        return NudgePosition<TR1Type>(level.Entities[itemIndex], itemIndex, x, y, z);
+    }
+
+    public static TRItemEdit NudgePosition(TR2Level level, short itemIndex, short x = 0, short y = 0, short z = 0)
+    {
+        return NudgePosition<TR2Type>(level.Entities[itemIndex], itemIndex, x, y, z);
+    }
 }
```

**Comment by aredfan** [comment]
A new issue I noticed - the senet table which previously had some clipping with the floor, now has z-fighting instead.

PR build:
![20241212_073046_Obelisk_of_Khamoon](https://github.com/user-attachments/assets/f33bcc4e-31e4-4793-91b4-26a79554c008)

Dev snapshot:
![20241212_072945_Obelisk_of_Khamoon](https://github.com/user-attachments/assets/6a9ad8db-4f66-4772-9eed-89ff8fdb7528)

**Comment by rr-** [comment]
Yeah that one will also need to be raised a bit.

**Comment by lahm86** [comment]
There is also a floating chair in this room. May as well include it while shifting the senet table.

![image](https://github.com/user-attachments/assets/1c8b2ffa-ac51-4e97-b628-8f0dbd80496d)

**Comment by aredfan** [comment]
@lahm86 The same chair type is also present in Return to Egypt (static 151) and Temple of the Cat (static 72).

**Comment by lahm86** [comment]
Oh thanks, I always forget UB.
