### ISSUE TITLE
Restore microphone position functionality

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#2024]
#1983 moved the microphone position option into the JSON config, but currently the option isn't linked to the related functionality.

**Comment by Richard-L** [comment]
@lahm86 would this mean that the setting becomes available in TR1 as well re https://github.com/LostArtefacts/TRX/issues/1438 ? 👀

**Comment by lahm86** [comment]
> @lahm86 would this mean that the setting becomes available in TR1 as well re #1438 ? 👀

Not quite yet, we'll tackle it under #1438. This was just to link the setting to the functionality in TR2 since the removal of the setup window and registry settings.
