### ISSUE TITLE
TR1X bug: motorboat z-fighting with animated water

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#2038]
Natla's Mines, rooms 4 and 83.

The animated water texture has z-fighting with the front part of the boat.

https://github.com/user-attachments/assets/e28d5ae3-5dae-44dd-8fd6-f2da0a58fc37

The video below shows 4.6.1, which matches TombATI behaviour.

https://github.com/user-attachments/assets/667c0c7c-0a42-4227-9da9-ab80f87bdf39

The water is visible or hidden depending on the camera angle. I think it'd make sense for the water to be hidden because the hull of the boat is displaced water. I'm guessing the static parts of the boat will have to be slightly adjusted to fix the issue, if the issue does end up getting tackled.

The DOS version which doesn't suffer from the clipping issue, also hides the water texture.

https://github.com/user-attachments/assets/e3beb84c-283e-491e-880b-e5758db90f53

**Comment by rr-** [comment]
We'd need to lower the boat to resolve this properly.

**Comment by Richard-L** [comment]
fwiw, PS1 shows the water surface texture only on one side, with no z fighting.
![Tomb Raider (Europe) 2024-12-14-15-08-47](https://github.com/user-attachments/assets/39037d54-23a5-4ddb-b89d-79eadbb2e8f2)

Would be nice to mimic DOS behaviour indeed. Nice detail find aredfan.
