### ISSUE TITLE
Clock hands are swallowed up

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#2050]
Maybe some z-fighting fun going on?

I cut these videos to always show the front face of the stopwatch:

TR2X

https://github.com/user-attachments/assets/4de07d0a-d025-44cd-9987-7091ae6aa07c

PS1

https://github.com/user-attachments/assets/59020f6c-629f-4170-b5f6-b624cae17b5c

**Comment by rr-** [comment]
Do you have z-buffer enabled? (F7)

**Comment by Richard-L** [comment]
I hadn't no. Enabling it fixes it.

Should that be all there is to this?

I presume z-buffer must remain optional because enabling it introduces problems elsewhere? I remember 2d sprites being half underground and similar shenanigans.

**Comment by rr-** [comment]
> I hadn't no. Enabling it fixes it.
> 
> Should that be all there is to this?
> 
> I presume z-buffer must remain optional because enabling it introduces problems elsewhere? I remember 2d sprites being half underground and similar shenanigans.

The ability to disable it, as the case with SWR, is there mostly for those who want to experience the true nostalgia. Eg #1752

**Comment by Richard-L** [comment]
Alright, if this is expected behaviour, then we shall close.
