### ISSUE TITLE
Allow to pick Lahm's Maria Doria (not) upside down

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#2053]
Seeing as @lahm86 has done such a wonderful job turning Maria Doria around again, it could be a sweet touch of TR2X to allow playing the level like that via the config tool. It would also allude to the project's strong connection to TRLEs.

Naturally it would need a disclaimer and some words of introduction. But having played through Lahm's edited version, you cannot help but notice the level feels very authentically classic TR2.

Just a quick idea I wanted to share.

**Comment by lahm86** [comment]
Thanks @Richard-L. Just to add, it was also equally Eycore's effort in creating this.

But IMO this is mod territory and I don't think we should include it. It would need the changed level file shipped with the game or an external tool made for people to edit their own file, neither of which is desirable. I think sharing info about it is nice though, here or on Discord, and the fact it's available online elsewhere already and is very simple to install, I feel is enough.

**Comment by Richard-L** [comment]
I understand where you're coming from Lahm ❤️ 

Dash, if you have an opinion thanks for sharing it. But please do try Lahm's edit first 😉

**Comment by rr-** [comment]
I 100% agree with Lahm, although I didn't know of the mod. I'm curious to play it. Where can I download it? :D

**Comment by Richard-L** [comment]
@rr- It's here :) https://core-design.com/community_tr2wreckofthemariadoriaflipped.html

Video: https://youtu.be/6qYyNijf1xo

**Comment by rr-** [comment]
Thanks. Closing this one as it's a mod territory.
