### ISSUE TITLE
Demo play takes control

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#2068]
1. Focus an item in the main menu, for example Lara's home, but don't activate it.
2. Give it time for the demo timer to run out.
3. Press the key for "inventory" in order to go back to the ring menu.

The game will instantly launch into the demo play. Expected behaviour is that the "back" command resets the demo timer, and allows you to use the ring menu.

The bug does not occur in TR1X.

**Comment by aredfan** [comment]
Regression since [0.3](https://github.com/LostArtefacts/TR2X/releases/tag/0.3).
