### ISSUE TITLE
Failure in the textures of the colosseum

### ISSUE THREAD

**Issue by antonio3687** [LostArtefacts/TRX#2071]
![20241217_182631_El_coliseo](https://github.com/user-attachments/assets/547aec4f-c61b-4d19-8a40-3a16d527d4d2)
![20241217_182639_El_coliseo](https://github.com/user-attachments/assets/cc1f76d1-a722-4701-940b-524315e17739)
Good morning, the textures of the coliseum remain the same, I have attached two images. I have the version: TR1X-4.6.1-167-g5c20e72-Windows. Best regards.

**Comment by aredfan** [comment]
@antonio3687 Do you mean the colosseum roof textures? It appears like that if the `Fix texture issues` option is enabled.

![Screenshot](https://github.com/user-attachments/assets/8d7f3d89-73f6-429a-9804-be43d3807e78)

**Enabled:**
![20241218_123513_Colosseum](https://github.com/user-attachments/assets/b4de5189-3371-493e-93f8-5aaae6f8f135)

**Disabled:**
![20241218_123459_Colosseum](https://github.com/user-attachments/assets/25278cc0-4024-42fc-b339-100bc57a665a)

**Comment by antonio3687** [comment]
But then, if I activate it, it corrects the textures and if I deactivate it, it does not correct them, right?

**Comment by aredfan** [comment]
> But then, if I activate it, it corrects the textures and if I deactivate it, it does not correct them, right?

Yes that is correct.

**Comment by antonio3687** [comment]
And couldn't they be made to stay corrected along with all the fixes to the other textures on all levels?
I have tried with other files from the original cd that I have of the game and if it works, with the others that I had before it didn't work.

**Comment by rr-** [comment]
> And couldn't they be made to stay corrected along with all the fixes to the other textures on all levels? I have tried with other files from the original cd that I have of the game and if it works, with the others that I had before it didn't work.

Could you please help me understand the specific issue you're facing? Thanks.

**Comment by antonio3687** [comment]
If when the texture correction of all levels is activated, the texture of the coliseum ceiling in the image would also be corrected. Could this be done?

**Comment by aredfan** [comment]
> If when the texture correction of all levels is activated, the texture of the coliseum ceiling in the image would also be corrected. Could this be done?

The correct roof textures as shown in your screenshots, is a part of the `Fix texture issues` option.

Are you saying the roof texture looks identical with the option enabled and disabled?

**Comment by antonio3687** [comment]
No, with the action disabled the roof textures appear correctly and with the option enabled they do not appear correctly.

With the action enabled, could you also put the roof textures?

I'm sorry I don't know how to explain myself well and I use an English translator.

**Comment by aredfan** [comment]
> No, with the action disabled the roof textures appear correctly and with the option enabled they do not appear correctly.

Could you please post a screenshot for each action, to help us understand better? Thanks.

**Comment by antonio3687** [comment]
You can close the topic, it is already working for me, thank you very much and sorry for the inconvenience. Best regards
