### ISSUE TITLE
Dobermans don't focus Lara

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#2080]
Not sure if this is really anything, but notice how in OG (PS1) the dogs have their heads turned towards Lara and focus even when they can't reach her. They don't seem to show this behaviour in TR2X. They also seem to bark a bit more, but this could be speculation.

TR2X

https://github.com/user-attachments/assets/5fbb687c-54bd-4516-a427-817c0ee140b1

PS1

https://github.com/user-attachments/assets/1007d9b6-c12e-4d8e-8b1a-9c414cdb4102

**Comment by aredfan** [comment]
Regression since [0.6](https://github.com/LostArtefacts/TRX/releases/tag/tr2-0.6).
