### ISSUE TITLE
Controller User Keys Resets not working!

### ISSUE THREAD

**Issue by Snake356** [LostArtefacts/TRX#2090]
In TR1X you can no longer reset the custom assignment for the controller as no button is displayed. This should be fixed.

![image](https://github.com/user-attachments/assets/81956e19-d115-47a3-a01c-7f4490aa0632)

**Comment by rr-** [comment]
Thanks for the report. You can try the PR builds in the linked pull request, or wait for a hotfix that we'll likely release soon.
