### ISSUE TITLE
OG bug: Lara can void when collecting underwater items

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#2096]
https://github.com/user-attachments/assets/d7d4ea47-fa22-40b0-b68a-fb4ec246ffa8

I think this can happen in TR1 as well although it's more difficult to reproduce. Needs some further investigation there.

**Comment by Richard-L** [comment]
I've only ever experienced this in TR2, at different spots, but I also don't use TR2's swim mechanics in TR1. My hunch is it happens more often if Lara's swim speed is still relatively high as she initiates the pickup. It's almost as if the game doesn't stop her movement and overlaps the pickup, but by the time that's finished she's already moved beyond the level mesh.

**Comment by lahm86** [comment]
Thank, @Richard-L. Yes, it certainly seems like Lara's speed isn't being checked/reset. I think once we find the fix, we can mimic it in TR1 as a safeguard.
