### ISSUE TITLE
circumflex accent not displayed

### ISSUE THREAD

**Issue by Wronschien** [LostArtefacts/TRX#2101]
The `\{hat}` entity should display a circumflex accent whereas now it is ignored by the parser. Everything's alright with `\{acute accent}` or `\{grave accent}` though.

**Comment by rr-** [comment]
> The `\{hat}` entity should display a circumflex accent whereas now it is ignored by the parser. Everything's alright with `\{acute accent}` or `\{grave accent}` though.

Thanks for the report. Can you show the full string you're using? Also you might want to try and use the characters directly: âĉêĝĥîĵôŝûŵŷẑ ÂĈÊĜĤÎĴÔŜÛŴŶẐ

![20241222_001814_Title](https://github.com/user-attachments/assets/87a734ce-16f3-4e0c-82a9-f30b42ab6e60)

**Comment by Wronschien** [comment]
I didn't know you could use direct accents now, this works indeed (but only when the json is encoded in UTF8 and not ANSI).
Is there any benefit using entities then ?

The one that doesn't work is :
`"INV_ITEM_CONTROLS": "Contr\\{hat}oles",`

**Comment by rr-** [comment]
> I didn't know you could use direct accents now, this works indeed (but only when the json is encoded in UTF8 and not ANSI). Is there any benefit using entities then ?
> 
> The one that doesn't work is : `"INV_ITEM_CONTROLS": "Contr\\{hat}oles",`

There's no real benefit – they should be considered a legacy solution that will likely get removed in upcoming versions.

**Comment by Wronschien** [comment]
Alright, so I'll stop using them, thanks for keeping the project better and better
