### ISSUE TITLE
Question: support for Tomb Raider 3, 4 and 5

### ISSUE THREAD

**Issue by Kappa971** [LostArtefacts/TRX#2104]
Hi, just a simple question if you add Tomb Raider 3, The Last Revelation and Chronicles support in the future.
In these games, unlike Tomb Raider 2, decompilation has already been done:
Tomb Raider 3:
https://github.com/Trxyebeep/tomb3-legacy
https://github.com/Trxyebeep/tomb3
Tomb Raider The Last Revelation:
https://github.com/Trxyebeep/tomb4-legacy
https://github.com/Trxyebeep/TOMB4
Tomb Raider Chronicles:
https://github.com/Trxyebeep/TOMB5

**Comment by rr-** [comment]
TR3 likely yes,  TR4+ status unknown at the moment.

**Comment by Kappa971** [comment]
Well, I hope you will also consider Tomb 4 and 5, to have the complete PS1 series in TRX source port.

As already said the decompilation work has already been done by others, this could, perhaps, speed up your great work a lot (or maybe you plan to do the decompilation from scratch?).
