### ISSUE TITLE
TR1X Demo Mode desync

### ISSUE THREAD

**Issue by drydenj** [LostArtefacts/TRX#2113]
My bad - it's the new settings affecting Lara's position, either swim or jump.

TR1X I noticed the second demo mode (Lost Valley) becomes clearly different to the TR1 original when Lara fights the wolves. She ends up shooting at a wall three times rather than at the last wolf. 30/60 fps doesn't appear to affect it.

Old PC and PSX demo mode vids for reference: 
https://youtu.be/gMM6OIQQkzI
https://youtu.be/u7jP614WB3c?t=20

**Comment by drydenj** [comment]
My bad - it's the new settings affecting Lara's position, either swim or jump.

**Comment by lahm86** [comment]
It's responsive swim cancel causing this, we should disable this during demos. Will re-open and address.
