### ISSUE TITLE
TR1X bug: rare crash involving fire and water

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#2116]
**Dev snapshot:** 4.7.1-120-g39b10a1
**Regression since:** [0.8](https://github.com/LostArtefacts/TRX/releases/tag/tr1-0.8)

____________________

**First steps:**

1. `/play 7`
2. `/tp 23 -4 67`
3. `/save 1`

**Second steps:**

1. Have Lara catch fire
2. Have Lara fall into water
3. Press `O` at the last possible moment before Lara is submerged
4. If no crash, `/load 1` and try again

____________

https://github.com/user-attachments/assets/e26f1f05-e653-4399-b2f0-bd5d2041ba33

**Comment by aredfan** [comment]
This bug is pretty old and originates from [0.8](https://github.com/LostArtefacts/TRX/releases/tag/tr1-0.8).

**Comment by rr-** [comment]
@aredfan thank you for searching for the specific version. Does the log file contain a stack trace?

**Comment by aredfan** [comment]
@rr- Anytime and you're very welcome.

I'm actually not sure whether the log file contains a stack trace so I'll upload it for you to check.  It's from the latest dev snapshot (4.7.1-128-ge3d6d8c) after triggering the crash.

[TR1X.log](https://github.com/user-attachments/files/18241905/TR1X.log)
