### ISSUE TITLE
Can't skip to Opera House with cheats

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#2118]
1. `/play 1`
2. Use the level skip cheat until Opera House
3. Game freezes at Bartoli's Hideout stats screen

**Comment by rr-** [comment]
Actually I think this is an invalid issue and stems from my local testing tooling causing an OS-level deadlock in logs captures. @aredfan can you confirm if it's working fine for you in the latest develop branch? Thanks.

**Comment by aredfan** [comment]
@rr- No problem, I can confirm the latest dev snapshot doesn't have this issue. I'm able to skip the levels from Great Wall to Offshore Rig without the game freezing.

(I'm able to skip all the levels from start to finish.)

**Comment by rr-** [comment]
Thanks. Closing as invalid.
