### ISSUE TITLE
Graphical glitch in Bartoli

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#2125]
Experienced a not seen before and pretty bizarre graphical glitch using this build https://github.com/LostArtefacts/TRX/pull/2117#issuecomment-2561965859

I had to record it with my phone, as the OBS recording _does not_ capture it curiously (it shows the game normally). This made me worry something might be wrong with my monitor, but it's only happening in this spot, and only when Lara is angled the way she is here:

https://github.com/user-attachments/assets/971f0560-a492-4ff2-a8f4-d8fe714269d7

**Comment by rr-** [comment]
This looks like a faulty HDMI cable or connector to me. It can manifest in bizarre ways like this, e.g. depend on the content fed to the screen. The inability of OBS to capture it supports this theory.

**Comment by Richard-L** [comment]
You're probably right. I'll close for now.
