### ISSUE TITLE
TR2X bug: HSH intro fixed camera can get stuck or skipped when using cheats

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#2129]
**Regression since:** [0.7](https://github.com/LostArtefacts/TRX/releases/tag/tr2-0.7)

_________________

The fixed camera (the one focused on enemies in the courtyard) gets stuck with these steps:
1. On the main menu, execute `/play 18`
2. Let the intro play out fully

The fixed camera gets skipped with these steps:
1. `/play 17`
2. Use the skip level cheat
4. Let the intro play out fully (don't move Lara)
5. `/play 18`
6. Let the intro play out fully again

**Comment by rr-** [comment]
I think it's actually a regression from 0.6.

**Comment by rr-** [comment]
Broken in f166dcb65afda2279a247641dc601bb9128c223f.
