### ISSUE TITLE
TR1 Compile Error [uthash.h not usable] - 4.7 / 4.7.1

### ISSUE THREAD

**Issue by jrugia** [LostArtefacts/TRX#2145]
As of 4.7 /4.7.1 I'm getting an error that uthash.h is not usable (I'm assuming not found).

Up to 4.6.1 this wasn't an issue, I also noticed in 4.7 and 4.7.1 the uthash.wrap file in "/src/libtrx/subprojects" directory is no longer there.

What changed please and how can I resolve this?

Thanks

**Comment by rr-** [comment]
Please rebuild the docker toolkit. Thanks

**Comment by jrugia** [comment]
Never used docker,  been compiling the project on Linux from the meson file. Any other way to compile without docker please?

**Comment by lahm86** [comment]
You can see details below for how to get setup without docker, although it's overall easier if you use the supported approach. If you are going for the manual approach, I imagine you will need to install uthash on your system, and possibly clear out your previous build directory to ensure everything is compiled afresh.
https://github.com/LostArtefacts/TRX/blob/develop/docs/CONTRIBUTING.md#compiling-on-ubuntu

**Comment by rr-** [comment]
Ref #1923

**Comment by jrugia** [comment]
Installed the uthash dev files system wide and it compiled fine.

Thanks for the help, closing ticket.
