### ISSUE TITLE
Ingame timer doesn't respond to turbo speed

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#2167]
Observed in the 265 build.

**Comment by aredfan** [comment]
See this [reply](https://github.com/LostArtefacts/TRX/pull/1421#issuecomment-2248963321).

Whilst Dash was talking about TR1X specifically, I'd imagine the same applies to TR2X.

**Comment by Richard-L** [comment]
Thanks for the link. The reasoning makes no sense to me though. Speeding the game up cheats the time, and makes finishing times totally invalid if they're not sped up along with the game.

**Comment by rr-** [comment]
The reason is the cost of making this work while offering little value.
I can revisit this now that I have more energy for this.

**Comment by Richard-L** [comment]
Thanks rr.

Surely you should do what you prefer. Just good to capture it I think.
