### ISSUE TITLE
Inventory animate in SFX is too early

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#2169]
I've only begun noticing this since the build here (265) https://github.com/LostArtefacts/TRX/pull/2166#issuecomment-2565637222

You can hear the animate in sfx is already done in TR2X before the ring even starts its in-animation.

TR2X

https://github.com/user-attachments/assets/a9d57fbf-17a5-4680-983f-1912ce908531

PS1 (loading bar says hi first)

https://github.com/user-attachments/assets/698b465c-eaac-4d06-805e-9d6eae9e05f1

**Comment by lahm86** [comment]
Did the linked PR definitely cause this or was it on previous builds? I'm not very good at hearing this kind of difference.

**Comment by rr-** [comment]
Thank you @Richard-L for finding this out, I knew something was off, but couldn't wrap my finger around what exactly. A fix will be made available shortly.
