### ISSUE TITLE
OG bug: the green arrow can overlap with the health bar

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#2180]
#797 for reference
___________________

When the inventory is open and a medipack is highlighted, it's possible for the health bar and green arrow to overlap.
![20241231_075214_Diving_Area](https://github.com/user-attachments/assets/2212571c-5a41-418d-a33c-18f7ab084294)

TR1X's approach is to hide the arrow when a medipack is highlighted in the inventory.
![20241231_080650_City_of_Vilcabamba](https://github.com/user-attachments/assets/a5ab337e-4782-434f-8812-2d63da36c802)

**Comment by rr-** [comment]
This also manifests in OG, only depending on the resolution.
