### ISSUE TITLE
Feature: Unicode support

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#386]
:D

**Comment by oziphantom** [comment]
with a bitmap font?... nah

**Comment by rr-** [comment]
Yes, with a bitmap font
ビットマップ フォント even

**Comment by Richard-L** [comment]
I love it. I would think we can use OpenLara's bitmap glyphs perhaps? Should I ask?

**Comment by rr-** [comment]
I don't think OpenLara uses bitmaps that are readily reusable?

https://github.com/XProger/OpenLara/blob/a4eac0afa15bf11c1c62544cd62f50f277fa2a6c/src/lang/glyph_gr.h

**Comment by Richard-L** [comment]
Ah, maybe I misassumed. Was thinking of these:
https://github.com/XProger/OpenLara/blob/master/src/lang/glyph_ru.png
https://raw.githubusercontent.com/XProger/OpenLara/master/src/lang/glyph_ja.bmp
https://raw.githubusercontent.com/XProger/OpenLara/master/src/lang/glyph_gr.bmp
