### ISSUE TITLE
Improve fade skipping

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#541]
Very nitpicky thing, but something you do notice after prolonged testing:

Currently the fades cannot be skipped via ESC or the action button. Take for example the initial EIDOS logo: you can only skip after fade-in, or before fade-out, but not during. It would be really nice if the skip behaviour were extended to all these three states: fade-in, image showing, fade-out.

I wonder where else this has an effect. I reckon during the end credits.

**Comment by rr-** [comment]
You can skip it during but it just starts fade out sooner and doesn't immediately close.

**Comment by Richard-L** [comment]
Yeah, that's what I meant by skipping while the image is showing. It will start the fade-out. But the fades _themselves_ you cannot interrupt with a button press.

If this is annoying to change then nvm. I just think it's good to give people control. And I'm really feeling the fades each time I fire up the game for testing :stuck_out_tongue_winking_eye:

**Comment by walkawayy** [comment]
If you press ESC or action during the Eidos fade in, it will start to fade out instantly. So the faster you press, the shorter the fade out and skip.
Once the Eidos logo is fully faded in, you can't skip it.
