### ISSUE TITLE
T1M bug: Faster passport closing animation on New Game and Save Game

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#542]
Hello, I've noticed that after selecting New Game, the passport closing animation moves faster than usual.  The video below compares the load/new game passport closing animations.

https://user-images.githubusercontent.com/94776985/167241567-ad8edebc-7a4a-4086-8844-22b19498259f.mp4

**Edit:** Can also confirm that when starting a New Game from the manor level, the passport closing animation is also faster.

**Comment by rr-** [comment]
I can't see the difference in this video?

**Comment by aredfan** [comment]
The video doesn't really show this very well, but the passport closes and pulls away faster when you select New Game.  I assumed this is a bug because it doesn't happen in TombATI.

**Comment by walkawayy** [comment]
I think I've noticed this mostly with save game.

**Comment by fluxtom** [comment]
https://user-images.githubusercontent.com/40272218/169842831-91923791-eaaf-4c63-a6ca-a2eb77bca98f.mp4

Left is load game, right is new game.

I didn't manage to get them to line up frame perfectly, load game has one or two frames of the selection screen, but I'm seeing a faster new game

**Comment by walkawayy** [comment]
Whoops I actually broke this in #458. At the end of `option_passport.c`, `if (page == 2) {` became `if (page == PASSPORT_PAGE_2) {`. It should be `if (page == PASSPORT_PAGE_3) {`. I confirmed with TombATI that the Exit option on page 3 should be the option that closes the passport from the back. Page 2 with new game / save game should flip back to page 1 and close.
