### ISSUE TITLE
Feature request: Make grey arrows optional

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#543]
Hello, may I request for the grey arrows to be made optional.  As a long time pc player it's hard for me to get used to this change.

**Comment by rr-** [comment]
Personal opinion but this sounds like a feature creep to me.

**Comment by Richard-L** [comment]
I would tend to agree with rr.

The only argument I could see in favour of it was a consideration whether 100% PC or PS1 UI appearance of the game is intended or not. Currently we have a situation with a (mostly agreed upon) best of both worlds kind of mix.

I assume the desire to make this optional might also stem from experience with TR2M, where most any small little detail like this is customisable. I have no insight into the manageability of the code, but I do worry a bit about getting too lost in details and killing the fun for devs.

**Comment by aredfan** [comment]
Yeah I was wondering if I was nitpicking before putting in this request.  I get that T1M will include compromises or 'best of both worlds' changes.  I hope I don't come across as ungrateful but I do feel there should be a way to opt-out because grey arrows changes the previously solely golden aesthetics on the pc version.

Regardless of whether it happens, thank you for hearing me out 👍
