### ISSUE TITLE
Requestor is incorrectly sized at high UI scaling

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#546]
When UI scaling is increased, the requestor menu is bugged and displayed off screen. This is due to the removal of low resolution checks in #516. They just need to be added back in.

Screen of 2.0 scaling:
![20220509_111608_Title](https://user-images.githubusercontent.com/81546780/167441579-6a95db9b-2619-4cf9-9217-8177cf04454f.jpg)

**Comment by walkawayy** [comment]
@rr- check here for the bug. High UI scaling uses the lower resolution requestor.

**Comment by rr-** [comment]
@walkawayy do we want to release it as a hotfix?

**Comment by walkawayy** [comment]
I don't think it needs to be but I'll leave it up to you.
