### ISSUE TITLE
Feature request: instant kill cheat

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#553]
For TRLE builders. I suggested it after watching Sabatu test The Great Pyramid and having to go through the torso fight again and again. This would be similar to the door open cheat. Alternative implementation: have all guns deal 10000 damage when the cheat is on.

**Comment by Rapora9** [comment]
This is a good cheat. I think the best way to implement the cheat is by setting health to 0 for the enemy who Lara is targeting when the corresponding cheat button is pressed. This way the player (and builders) can for example
- easily decide which enemy they want to be killed
- kill an enemy from a long range
- get a lock to an enemy by shooting it, and then killing it even when behind a wall, in a different room etc.
- kill other enemies with normal ammo and others with one-shots.

If I had more time I'd be interested in doing this but right now I can't.

**Comment by rr-** [comment]
To whoever takes it, please wait until #561 gets merged because it affects the input code significantly and would conflict with this ticket.

**Comment by walkawayy** [comment]
I think this can be closed since it's now a console cheat as Lahm linked in the PR @rr-
