### ISSUE TITLE
Additional cheats

### ISSUE THREAD

**Issue by daninthemix** [LostArtefacts/TRX#556]
Any chance of god mode / infinite ammo / one hit kill cheats?

**Comment by rr-** [comment]
God mode is guaranteed with the fly cheat
Infinite ammo is accomplished with the item cheat
Instant kills will be handled with #553

**Comment by Rapora9** [comment]
> God mode is guaranteed with the fly cheat

Sometimes it would be nice to be invincible and still walk, shoot and climb at the same time. However that can be mostly achieved with unlimited medi packs. **I'm not suggesting to reopen this issue**, but I wanted to point out that fly cheat doesn't cover all cases where someone would like to not take any damage.

**Comment by rr-** [comment]
Thing is we're running out of buttons on the keyboard to cater for each bit, yet alone a controller.
