### ISSUE TITLE
Doesn't revert to pistols at new level start

### ISSUE THREAD

**Issue by MatthTheGeek** [LostArtefacts/TRX#557]
OG always reverted to pistols as the selected weapon when starting a new level. Tomb1Main keeps the last weapon equipped.

This is a minor issue but does cause a balance issue for speedrun/races between OG / TombATI and Tomb1Main. It is not bad for QoL for casual play tho, so a config toggle might be best.

**Comment by Richard-L** [comment]
Could you post a screenshot of the title screen with your version in the bottom right corner?

**Comment by Richard-L** [comment]
Hmm I was sure we'd talked about this one before. Anyhow, it seems there is indeed currently no setting to maintain OG behaviour.

PS1

https://user-images.githubusercontent.com/4934209/168423845-82d47a40-35c3-4b9a-aa4b-c1cb66793de8.mp4

TombATI

https://user-images.githubusercontent.com/4934209/168423850-0383f70b-b6e9-4bf1-abd4-545615c08711.mp4

TR1M

https://user-images.githubusercontent.com/4934209/168423855-f9389c4c-90cc-4d69-8760-244724d53368.mp4

**Comment by rr-** [comment]
Is there anyone actually using Tomb1Main for speedrunning / races, or is this ticket strictly hypothetical?

**Comment by MatthTheGeek** [comment]
In theory I would, I'm in a community that sometimes does TR classic races, we mostly use tombATI and I've quietly been promoting Tomb1Main there. 

We're mostly casual so that issue is not considered a big deal, but I thought it would be best to bring it up anyway.
