### ISSUE TITLE
T1M Bug: Atlantis levels crashing

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#581]
When walking up to this room in Atlantean Stronghold near the beginning of the level, the game crashes. The log does not contain any useful errors. This is new since 2.9 and happens on 2.9.1 as well.

![image](https://user-images.githubusercontent.com/81546780/172014029-e5d412bf-8eb8-43cc-b219-a79beec5f885.png)

**Comment by walkawayy** [comment]
Did some flying through Atlantis and it also happens in this room before Bacon Lara. I don't think it has anything to do with a trigger since the UB crash wasn't on one. And the pods at the beginning of Atlantis work fine.

![image](https://user-images.githubusercontent.com/81546780/172014423-6b9335b7-5fe1-436e-a5ed-2f4ad532ed3d.png)

**Comment by Richard-L** [comment]
Since we had the other UB issue with the jump, I'm curious what version of the level files is used here.

**Comment by walkawayy** [comment]
I think it's related to a rename issue since nothing else should have changed in these levels in the latest update.

**Comment by rr-** [comment]
I can't reproduce this issue. In both rooms there is a centaur. Are you sure you're using 2.9.1?

**Comment by walkawayy** [comment]
My bad. Saw a report on TRF. I was still on 2.9 when I tested. This is the centaur bug which is fixed in 2.9.1. Closing this.
