### ISSUE TITLE
The TR1Main doesn't support W7

### ISSUE THREAD

**Issue by bisousmwah** [LostArtefacts/TRX#582]
Not really much to put in here, but everytime I open the Community Edition's game executable, the game will results in a error of 'App Name' Stopped Working.
And that prevents me to play TR1 Custom Levels (Like the Sabatu TR1) which annoys me.
I would be honored if you made it compatible with older Windows Operating Systems.

**Comment by Richard-L** [comment]
Have you tried the main game? I'm on Win7 and it runs fine. Could be to do with the custom level perhaps.

**Comment by bisousmwah** [comment]
Not really, since TR1 Win 7 CD Version gets an error of unsupported OS
bit(Mine is 64Bits).

**Comment by oziphantom** [comment]
by main game he means run Tomb1Main with just the normal levels and data and not Sabatu's levels.

**Comment by bisousmwah** [comment]
No, it keeps putting the stopped working like the first comment of mine
said.

**Comment by oziphantom** [comment]
do you have it in any directory that would have a no standard ASCII character, such that your user name or computer name in downloads, my documents, desktop etc has you username which has any letters that are not a-Z a-z 0-9 no ú etc no Asian/African/Arabian languages or Russian based languages ?

**Comment by bisousmwah** [comment]
I don't think so, it's the default, DELL-PC / DELL.

**Comment by Gerwin2k** [comment]
Old issue, but still open?
Just ran the published release v2.11 on Windows 7 Prof x64. Loaded a few different levels and Unfinished Business. No problems.  All good.

**Comment by carlo-bramini** [comment]
Excuse me, is it possible that the hardware configuration doesn't support shaders version 1.30?

**Comment by Richard-L** [comment]
@carlo-bramini what is the best way under Windows to check for this info?

**Comment by carlo-bramini** [comment]
> @carlo-bramini what is the best way under Windows to check for this info?

I got this idea because I'm able to run the engine on a real PC, but it hangs with exactly this error when it runs in a virtual machine under VirtualBox. Same behaviour for Seven and XP. So, I suspect that the Operating System is not the issue.

**Comment by Gerwin2k** [comment]
I use this to get OpenGL capabilities
https://github.com/gkv311/wglinfo

**Comment by bisousmwah** [comment]
Oh god, the tea I got from a 3(?) months old thread-

**Comment by rr-** [comment]
Closing this to be tracked as part of #327
