### ISSUE TITLE
T1M bug: Non-triggered centaur causes rendering artifacts

### ISSUE THREAD

**Issue by gamefreq0** [LostArtefacts/TRX#585]
While playing through the Atlantis level, I did the skip from the clanging spike doors above the lava pit, up to the platform where the boss fight happens in the next level. Upon continuing into the next room, there is a centaur, which, while in it's default deactivated pose, causes Lara to disappear, and nearby rooms to render improperly, when looked at.
![20220612115730_1](https://user-images.githubusercontent.com/42497703/173242250-84df2a46-6d7d-4def-b13a-ac0283285ada.jpg)
![20220612115731_1](https://user-images.githubusercontent.com/42497703/173242251-55328c09-caa3-4562-967b-f76bcab84cef.jpg)
[Tomb1Main.log](https://github.com/rr-/Tomb1Main/files/8886212/Tomb1Main.log)

This is on version 2.9.1, on Gentoo Linux, via Proton-GE 7.10. Further relevant information can be supplied if needed. Log is attached, though it doesn't appear to indicate much.

**Comment by rr-** [comment]
Can someone take a look at it?

**Comment by walkawayy** [comment]
I can look at this.

**Comment by Richard-L** [comment]
Are they using anti-aliasing as per driver settings? 🤔

**Comment by walkawayy** [comment]
I don't see any issues on Windows 10. I wasn't sure what Proton-GE was, so I looked it up. Seems like it's a fanmade Proton patch. Maybe that is causing your issues? I would also double check again you are on 2.9.1 and not 2.9. 2.9 is the only version we've seen reports of centaur bugs.

![20220617_000205_Atlantis](https://user-images.githubusercontent.com/81546780/174222439-bf17b20f-7cea-47c6-a4f3-bfb93fd59fdb.jpg)

**Comment by gamefreq0** [comment]
My mistake, it is, in fact, 2.9 I was running. And yes, that fixed the issue. Sorry about that.
