### ISSUE TITLE
Can't access secret #2

### ISSUE THREAD

**Issue by Wronschien** [LostArtefacts/TRX#596]
The way to reach the secret is to position oneself on the very left underneath the opening to the secret, then jump and grab the ledge. With Tomb1Main Lara doesn't grab the ledge, even when holding Ctrl before jumping.
Can something be done about that ?

**Comment by oziphantom** [comment]
secret #2 as in Level 1. 
You need to be in the left most corner, fact the entrance and press forward + Ctrl. Jumping won't get you into the secret. I

**Comment by Wronschien** [comment]
Thank you !
It's been so long I hadn't played it, I remembered the location but not the little trick of letting her jump automatically.
I'll close the thread then.
