### ISSUE TITLE
Unify logos and icons

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#597]
![image](https://user-images.githubusercontent.com/4934209/181241940-a6bd6edc-868b-45d5-88e7-ae24437523d4.png)
Now that there is a first step towards visual identity, let's make use of it.
Who did the logo in the end btw?

**Comment by rr-** [comment]
Richard, I already told you in private messages multiple times that the game icon is not going to change for a variety of reasons, including a community vote as well as forward compatibility with projects such as T3M.

Please stop making issues about this.
