### ISSUE TITLE
remove_scions in gameflow causes Lara to draw weapons

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#605]
If `remove_scions` is in the gameflow without `remove_guns`, Lara will always draw her weapons when the level starts, regardless of whether or not she finished the previous level with them drawn or holstered. This can be reproduced by adding `remove_scions` to any level in the default gameflow, or by removing `remove_guns` from Natla's Mines.

This was found during implementation of #599 - additional comments are [here](https://github.com/rr-/Tomb1Main/issues/599#issuecomment-1205629833).

**Comment by walkawayy** [comment]
Are you working on this @lahm86? I could take a look at this at some point if not.

**Comment by lahm86** [comment]
> Are you working on this @lahm86? I could take a look at this at some point if not.

Please feel free to take a look - I'm not currently working on this.

I did have an initial try at it but was struggling to track where the gun status was being set, but to be honest I wasn't able to give it much time. I did try splitting `Lara_InitialiseInventory` out as follows, and then calling `Lara_InitialiseInventoryItems` from the gameflow. This seems to work but it feels more like a patch than finding/resolving the actual issue. Hopefully it is something simple that I've missed.

```
void Lara_InitialiseInventory(int32_t level_num)
{
    Lara_InitialiseInventoryItems(level_num);

    RESUME_INFO *resume = &g_GameInfo.current[level_num];

    g_Lara.gun_status = resume->gun_status;

    if (g_Config.revert_to_pistols
        && g_GameInfo.current[level_num].flags.got_pistols != 0) {
        g_Lara.request_gun_type = LGT_PISTOLS;
        g_Lara.gun_type = LGT_PISTOLS;
    } else {
        g_Lara.gun_type = resume->gun_type;
        g_Lara.request_gun_type = resume->gun_type;
    }

    Lara_InitialiseMeshes(level_num);
    Gun_InitialiseNewWeapon();
}

void Lara_InitialiseInventoryItems(int32_t level_num)
{
    Inv_RemoveAllItems();

    RESUME_INFO *resume = &g_GameInfo.current[level_num];

    g_Lara.pistols.ammo = 1000;
    if (resume->flags.got_pistols) {
        Inv_AddItem(O_GUN_ITEM);
    }

    if (resume->flags.got_magnums) {
        Inv_AddItem(O_MAGNUM_ITEM);
        g_Lara.magnums.ammo = resume->magnum_ammo;
        Item_GlobalReplace(O_MAGNUM_ITEM, O_MAG_AMMO_ITEM);
    } else {
        int32_t ammo = resume->magnum_ammo / MAGNUM_AMMO_QTY;
        for (int i = 0; i < ammo; i++) {
            Inv_AddItem(O_MAG_AMMO_ITEM);
        }
        g_Lara.magnums.ammo = 0;
    }

    if (resume->flags.got_uzis) {
        Inv_AddItem(O_UZI_ITEM);
        g_Lara.uzis.ammo = resume->uzi_ammo;
        Item_GlobalReplace(O_UZI_ITEM, O_UZI_AMMO_ITEM);
    } else {
        int32_t ammo = resume->uzi_ammo / UZI_AMMO_QTY;
        for (int i = 0; i < ammo; i++) {
            Inv_AddItem(O_UZI_AMMO_ITEM);
        }
        g_Lara.uzis.ammo = 0;
    }

    if (resume->flags.got_shotgun) {
        Inv_AddItem(O_SHOTGUN_ITEM);
        g_Lara.shotgun.ammo = resume->shotgun_ammo;
        Item_GlobalReplace(O_SHOTGUN_ITEM, O_SG_AMMO_ITEM);
    } else {
        int32_t ammo = resume->shotgun_ammo / SHOTGUN_AMMO_QTY;
        for (int i = 0; i < ammo; i++) {
            Inv_AddItem(O_SG_AMMO_ITEM);
        }
        g_Lara.shotgun.ammo = 0;
    }

    for (int i = 0; i < resume->num_scions; i++) {
        Inv_AddItem(O_SCION_ITEM);
    }

    for (int i = 0; i < resume->num_medis; i++) {
        Inv_AddItem(O_MEDI_ITEM);
    }

    for (int i = 0; i < resume->num_big_medis; i++) {
        Inv_AddItem(O_BIGMEDI_ITEM);
    }
}
```

**Comment by lahm86** [comment]
@walkawayy I've found another issue which I think is related to this - could be something to do with the order in which things are called. Here is an example:

- Lara starts level 1, which has `remove_guns` in the gameflow.
- She picks up the Uzis in this level.
- Lara starts level 2, which also has `remove_guns` in the gameflow.
- Level 2 also has an Uzi weapon pickup but the game changes this to Uzi ammo.

So Lara is left unarmed with no guns to pickup. Again, I think it's one of those things that doesn't affect OG because I don't believe `Item_GlobalReplace` is called against pistols/pistol ammo.

Is it possibly an option to move all inventory initialisation to just before the `Game_Loop` call in the gameflow?

I can provide test levels for above if this helps.

**Comment by walkawayy** [comment]
Sure you can post them. I am tackling the save crystals issue atm, so I'll get to this when I have some free time.

**Comment by lahm86** [comment]
Here is the example from above.

[GlobalReplaceIssue.zip](https://github.com/rr-/Tomb1Main/files/9385492/GlobalReplaceIssue.zip)

Thanks - appreciate the help with this.

**Comment by walkawayy** [comment]
@rr- is it feasible to reorder the gameflow? If we move `remove_guns` and `remove_scions` to before `start_game` in the gameflow, all we have to do is remove the `Lara_InitialiseInventory(level_num);` calls from their gameflow sequences. Then these gameflow removals will update the `g_GameInfo.current[level_num].got_pistols = 0` and the like before the level is loaded and avoids the `Item_GlobalReplace` issues.

**Comment by rr-** [comment]
Yes that's fine for me, @lahm86 wdyt?

**Comment by lahm86** [comment]
That sounds good to me if you guys are happy with that. I can make adjustments in the randomizer to make sure we insert these entries before `start_game`.
Does the installer replace the default gameflow file if it already exists? I was just wondering if it would be an issue for people who have customised their gameflow but then the file is replaced on the next release.

**Comment by walkawayy** [comment]
Just checked the installer and it only overwrites the gameflow file if the overwrite option is checked. So yes this would cause issues if people upgrade without overwriting the gameflow.

![image](https://user-images.githubusercontent.com/81546780/185796406-00a0fce5-5cb7-4dd7-9996-aba07eaf71a3.png)


The only other fix to me looks like it would require reloading the level. Because any weapon pickups get replaced during the `Level_Initialise` function which has to happen during the `start_game` gameflow process. Changing the gameflow would be the cleanest and least hacky method IMO.

**Comment by rr-** [comment]
Let's change the GF and also warn people in  the installation notes that this new version requires overwriting the gameflow.
