### ISSUE TITLE
Fix glitches related with trapdoors and bridges

### ISSUE THREAD

**Issue by BlackWolfTR** [LostArtefacts/TRX#606]
**1st issue:**
When trapdoor is placed a little bit above the slope and it has dummy trigger on it Lara slides.
Same goes for the bridge objects.
Would be cool if there was an optional option to fix this issue.

https://user-images.githubusercontent.com/111443302/185347808-ed262f21-fb55-41f3-b7fe-b588a07b5042.mp4

**2nd issue**
When Bridge (tilt = 1) and Bridge (tilt = 2) objects are placed 1 sector or so higher above the slope, they are glitchy and Lara is unable to go upwards along it.
She cannot walk with shift as well.
She can go normally downwards still though.

https://user-images.githubusercontent.com/111443302/185348103-6b2089af-39ae-4d94-a77f-b1aab9c89e82.mp4

**3rd issue:**
When there are two bridge objects that are on the same sector but on different height, if you trigger the lower bridge, the game crashes as soon as you enter to the level.
The higher bridge can still be triggered and it doesn't crash though.

**Comment by rr-** [comment]
Hi, thanks for the report. It's hard to say when this will be worked on but we'd appreciate the level you were testing it on.

**Comment by Richard-L** [comment]
Out of interest, is this a TRLE-only concern?

**Comment by rr-** [comment]
I'm pretty sure that the OG does not feature this kind of geometry which would mean yes.

**Comment by BlackWolfTR** [comment]
Yes it's mainly TRLE concern.

Here's the file with the level:

**Comment by BlackWolfTR** [comment]
Yes it's mainly TRLE concern only.

Here's the file with the level:
https://www.mediafire.com/file/nrc9d39v1utswgt/test.phd/file
Just change the name in script ofc.

Do you want the one with the 3rd issue? It crashes only
(sorry for the mess with reopen but I'm pretty new to github and accidentally clicked what I shouldn't, not used to it ;-;)

**Comment by walkawayy** [comment]
FWIW, here's what Troye had to say on this:

`None of these are fixable. One and two are the same issue, and the third one is a direct misuse of the bridge system, can possibly make it not crash but it’ll never be possible to have 2 bridges in the same sector in 1 room.`

Never say never, but bridges are super hacky in TR games.

**Comment by walkawayy** [comment]
Another issue with tilted bridges related to the bridge offset being 0 instead of the max of 1023:

![image](https://github.com/user-attachments/assets/f916d8a7-4498-4712-83af-0b949edbcd87)
