### ISSUE TITLE
Save crystals won't save

### ISSUE THREAD

**Issue by Klona13** [LostArtefacts/TRX#607]
When I disable them, the game saves normally.
When enabled:
- I can interact with the save crystal.
- It opens the journal with the "save" page.
- I press ctrl/enter to open the save menu.
- The journal closes and it unpauses the game without saving at all.

Although, it does make a save file when I check the save folder. It's just that I cannot load it.

Also at some point it just crashed when I pressed ctrl to open the save menu (I wasn't able to reproduce this, it only happened once)

**Comment by walkawayy** [comment]
I'll take a look at this. I can definitely reproduce the journal always saving in slot 1 instead of letting the player select a level. I have had no issues loading a level or pressing action to save so far.

**Comment by walkawayy** [comment]
@Klona13 try this build. I think it should fix your issues. I couldn't get my game to crash so if it happens again let me know how it broke if you can.

[Save Crystal Fix v1.zip](https://github.com/rr-/Tomb1Main/files/9385539/Save.Crystal.Fix.v1.zip)

**Comment by Klona13** [comment]
It works now :)
