### ISSUE TITLE
Highlight newest save when game starts

### ISSUE THREAD

**Issue by NaBu1908** [LostArtefacts/TRX#618]
It would be nice when I open TR1Main for the first time and game would suggest me (highlight) literally last created savefile just like in TR2/TR2Gold instead of this one that is on the top of Lara's passport. Newest TR1Main can have more number of savefiles than stantard game so if may become an annoying issue if you will have to scroll down to the bottom of save files every time you launch a game after quit.

**Comment by rr-** [comment]
@walkawayy can you take a look? Should be easy to fix.
