### ISSUE TITLE
Stacked pushblocks can cause void issue

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#619]
If the game is saved when Lara is standing on top of a pushblock, which itself is on top of another pushblock, when that save is reloaded Lara voids. If an earlier save, where she is not standing on the block, is loaded, she can only get on top of the block after it is pushed/pulled. This isn't an issue with single blocks, only when they are stacked.

https://streamable.com/za1zsz

Found by LORDmeSH1NE during rando testing. The above is original level data and this has been checked with enhanced saves both on and off.

**Comment by lahm86** [comment]
This seems to be caused by the order of the items as they're defined in the level file. If I switch items 1 and 9 in the level file for Khamoon, the issue doesn't occur. So I think what happens in the original is the top block comes first in the item list, so when the game reloads the save it sets the floor height to 2048. The bottom block comes later in the list, and it adds another 1024 to the height. So when they're the other way around, they each add 1024 only to the floor height.

![image](https://user-images.githubusercontent.com/33758420/189498447-9a10bafc-1cd3-4a20-82b0-b6cc6815f102.png)

So it's easy to workaround the issue (for the randomizer/custom levels) - should Tomb1Main implement a "FixKhamoonBlocks" option that does this? Or is it feasible to scan over the blocks based on their y pos in the savegame load logic so the floor height is amended in order?

**Comment by rr-** [comment]
I'd say the latter is the more universal and desirable fix.

**Comment by walkawayy** [comment]
So this happened because the top of the block was near a room portal.

![image](https://user-images.githubusercontent.com/81546780/190836025-3ce92dfa-27a7-498e-90b0-4db0b7bb76b7.png)

![image](https://user-images.githubusercontent.com/81546780/190836027-000adb5a-e038-45de-81c9-cd7dd5dc94de.png)
