### ISSUE TITLE
Feature request: Always undraw weapon when out of ammo

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#629]
If Lara does not have her pistols and uses all of the ammo for whichever other weapon she is currently using, she will fire blanks infinitely. In TR2 and TR3, she puts her weapon away, which feels logical as she realises she doesn't have any ammo left.

This is an issue not seen in the original levels as Lara wouldn't be in a situation where she could pick up a weapon without having her pistols first i.e. in Natla's Mines she can only collect other weapons after killing the enemies.

Noticed by Topixtor during randomizer testing. To reproduce, add `remove_guns` to the gameflow settings for Lost Valley, head to the shotgun beside the skeleton, draw it and fire repeatedly.

https://user-images.githubusercontent.com/33758420/192164372-5bd06689-d47a-4072-991f-8bff136fa0e4.mp4

**Comment by Rapora9** [comment]
> This is an issue not seen in the original levels as Lara wouldn't be in a situation where she could pick up a weapon without having her pistols first i.e. in Natla's Mines she can only collect other weapons after killing the enemies.

One of the secrets in Natla's Mines has a shotgun so you actually can have all the other weapons (by using that shotgun to kill cowboy and skater) without having pistols in OG.

EDIT:

I tested this in TombATI. I didn't have pistols and picked up the shotgun. After wasting all 76 shells, Lara switches to pistols (??) and starts shooting with them. The pistols don't show up in inventory. I can switch back to shotgun, and then back to pistols by trying to shoot with the emptied shotgun.

**Comment by lahm86** [comment]
> > This is an issue not seen in the original levels as Lara wouldn't be in a situation where she could pick up a weapon without having her pistols first i.e. in Natla's Mines she can only collect other weapons after killing the enemies.
> 
> One of the secrets in Natla's Mines has a shotgun so you actually can have all the other weapons (by using that shotgun to kill cowboy and skater) without having pistols in OG.

Good point about the secret, I had forgotten about that. 

> I tested this in TombATI. I didn't have pistols and picked up the shotgun. After wasting all 76 shells, Lara switches to pistols (??) and starts shooting with them. The pistols don't show up in inventory. I can switch back to shotgun, and then back to pistols by trying to shoot with the emptied shotgun.

That's also interesting about TombATI. I think this is the piece of code and it just needs an `else` to make Lara unarmed; I guess TombATI perhaps doesn't have this condition and just sets the status to pistols regardless?

https://github.com/rr-/Tomb1Main/blob/develop/src/game/gun/gun_misc.c#L338

**Comment by lahm86** [comment]
I've changed it to the following and it seems to work OK.
```
if (Inv_RequestItem(O_GUN_ITEM)) {
    g_Lara.request_gun_type = LGT_PISTOLS;
}
else {
    g_Lara.gun_status = LGS_UNDRAW;
}
```
Before:
https://streamable.com/a9y7lb

After:
https://streamable.com/6hezsw

**Comment by Richard-L** [comment]
This should be tested on PS1 too. It's usually more cleaned up with these sort of things.
