### ISSUE TITLE
Sounds click and pop if they stop prematurely

### ISSUE THREAD

**Issue by Lrflx** [LostArtefacts/TRX#631]
What I mean is, for example, here in level 3 

https://youtu.be/byJ5to20C6I?t=1751

when Lara starts cog mechanism game uses sfx which plays and stops several times in a row, and in that automated fix version it works smoothly enough, but in tomb1main it clicks every time it replays. Same thing happens with other sounds as well, like when boulder rolls. I guess there needs to be implemented feature like earlyStopFadeOutTime Indirectsound has

**Comment by rr-** [comment]
I would appreciate something looking into this. Oziphantom might have an idea too.

This may be affected by how we need to resample the sounds and the music to the mixer's sample rate.
