### ISSUE TITLE
Config tool

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#633]
To my surprise we don't seem to have had logged an issue for this, but that's the goal of 2.11.

In this ticket, we want to improve the user experience around tinkering with the game configuration.

- Merge config JSON and runtime config JSON
- Create a GUI tool to edit the configuration

Technical details:

- GUI uses C# and WPF like our other GUI project, the installer
- We use GitHub Actions to automate building and shipping of the configuration tool
- We should merge/move `src/game/settings.c` to `src/config.c`
- Hold one global struct for all the settings
- Game reads the settings at the start, updates the struct upon certain player actions (changing game volume, rebinding the keys), and writes the struct back into a JSON file
- Same with the config tool
- Data races are tolerable (e.g. if the user tweaked the settings using the config tool while the game was running, it's OK if adjusting the music volume ingame discards these changes)
- Losing the comments in the config JSON is OK, the users are not expected to be editing the file any longer
- We still should pretty-print the configuration file for the tech-savvy
- Backwards compatibility is not important, but we need to warn the users about it with big flashy warnings when the 2.11 release is complete
- We need to pay attention to the GitHub Action new version release script, that it packages the new configuration correctly
- We need to pay attention to the installer, that it understands the files it needs to ship upon fresh installation and an update
- No new settings or features as part of this ticket

 @lahm86 has volunteered to create a tool for us :heart:

**Comment by Richard-L** [comment]
Oh wow, thank you sooooo much @lahm86 🙏

Other than an issue we had these two discussions:

Mainly: https://github.com/rr-/Tomb1Main/discussions/402

Also: https://github.com/rr-/Tomb1Main/discussions/247

**Comment by walkawayy** [comment]
Done and released in 2.11.
