### ISSUE TITLE
Holding down select during game exit crashes the game

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#646]
Holding the `select` key during `Shell_Shutdown` spins a call to `Input_Update()` in a while loop. I tested holding it after selecting exit game from the passport, and the game got stuck in a black screen and had a Windows crash error. Is there a reason the game does this at all and doesn't just do a shutdown? I checked and this seems like an OG bug (at least a TombATI bug).

**Comment by Richard-L** [comment]
I believe I heard a few speedrunners mention you mustn't hold a button whilst the level exits or TombATI will crash.
