### ISSUE TITLE
[Bug] Default Keybinds Override User Keybinds

### ISSUE THREAD

**Issue by OpenRift412** [LostArtefacts/TRX#652]
If a key that already has a default bind is set to something else, the default bind overrides the custom bind. Shouldn't it be the other way around?

**Comment by walkawayy** [comment]
I'm gonna close this as a duplicate of #564. A controls system rewrite is currently in progress, so this will hopefully be fixed soon.

**Comment by OpenRift412** [comment]
> I'm gonna close this as a duplicate of #564. A controls system rewrite is currently in progress, so this will hopefully be fixed soon.

Will this rewrite include a sub-menu specifically for controller binds as well?

**Comment by walkawayy** [comment]
Yes something will be done to
Make controllers customizable.
