### ISSUE TITLE
Allow customizable controller inputs

### ISSUE THREAD

**Issue by byblo** [LostArtefacts/TRX#659]
Cannot change the joypad buttons layout.

Ingame, pressing a button on a selected function like "Roll", will trigger the new input waiting, but then only pressing a keyboard key will be accepted. Pressing a joypad button at the new input waiting does not do anything.

Also, even tried to edit manually a layout to invert pads keys (in my case, I needed to invert 93 and 91 for Roll<-->Draw Weapon) from the file Tomb1Main.json5, but again, it does not make any changes.

Got the problem on main but still also on current develop branch.

Tried also my joypad in both XInput and DInput modes.

**Comment by walkawayy** [comment]
The control code is still going through a rework right now. The controller buttons are not changeable at the moment. I think Joy to Key would be your only solution in the meantime.

**Comment by byblo** [comment]
Yes it is no big deal for me. I reported the problem just to be sure you guys know about this issue
