### ISSUE TITLE
game crashing at closing due to SDL_GameControllerClose() second pass

### ISSUE THREAD

**Issue by byblo** [LostArtefacts/TRX#663]
Closing game is always crashing the second time that function is called:

`void S_Input_Shutdown(void)
{
    if (m_Controller) {
        SDL_GameControllerClose(m_Controller);
    }
}`

No idea what exactly that function does, but I managed to fix it somehow by adding a new line to prevent a second pass that always fixes it for me:

`void S_Input_Shutdown(void)
{
    if (m_Controller) {
        SDL_GameControllerClose(m_Controller);
        m_Controller = 0;
    }
}`

Note that I got only one joypad (see the logs)
Also added some new logs entries to trace it better: ---

[Tomb1Main.crashing_at_second_SDL_GameControllerClose()_pass.log](https://github.com/rr-/Tomb1Main/files/10199351/Tomb1Main.crashing_at_second_SDL_GameControllerClose._pass.log)

[Tomb1Main.no_crashing_with_m_Controller=0_after_first_SDL_GameControllerClose()_pass.log](https://github.com/rr-/Tomb1Main/files/10199350/Tomb1Main.no_crashing_with_m_Controller.0_after_first_SDL_GameControllerClose._pass.log)

Edit: Forgot to mention that it crashes on both branchs. Also crashing with default Tomb1Main.json5 file.

**Comment by oziphantom** [comment]
I threw a couple of breakpoints in and tested it. I normally Alt+f4 to exit so I've not seen the issue in the past. But if you exit from the passport menu then `Shell_Shutdown` is called from `S_Shell_TerminateGame` and at the end of `Shell_Main`. If you Alt+F4 only the `S_Shell_TerminateGame`  version is called. So the fix in this case is to remove the call at the end of `Shell_Main`.

**Comment by byblo** [comment]
Your fix works
