### ISSUE TITLE
Demo level support

### ISSUE THREAD

**Issue by carlo-bramini** [LostArtefacts/TRX#667]
I'm wondering if it would be possible to add a reply to this question to "Q&A" section of [README.md](https://github.com/rr-/Tomb1Main#readme).

It would be useful to write few instructions for knowing how to make them working, if the engine is able to run (or it may be able to do it in the future if it does not yet).
I think that it would be very useful to be able to run them, for testing/evaluating the engine without having the full game.

**Comment by oziphantom** [comment]
the demo data is stored in the level data, the engine just looks at each level in turn to see if it has a demo data segment in it. I don't know of any tools that would insert it for you though.

**Comment by carlo-bramini** [comment]
> the demo data is stored in the level data, the engine just looks at each level in turn to see if it has a demo data segment in it. I don't know of any tools that would insert it for you though.

Actually, I was not talking about the demo embedded inside the level data, but the playable demos of the first Tomb Raider.
The playable demo allows to play the level of the city of Vilcabamba.
I have seen two versions are available, one for plain PC and one for 3DFX.

There is also a demo version of the Unfinished Business extension. Two versions are available, one for PC and one for Mac (don't know if there are differences between them into the data files).

Those demos are also freely and legally downloadable from many places, that's why they could be useful to play with the engine even if you don't own the full game.

**Comment by oziphantom** [comment]
oh, make a custom Tomb1Main_gameflow.json5 file and then in the 
```
 // level 1
        {
            "title": "Caves",
            "file": "data\\level1.phd", <- change these to be your demo phd files. 1 per level for as many as you have.
            "type": "normal",
            "music": 57,
            "sequence": [
                {"type": "play_fmv", "fmv_path": "fmv\\snow.avi"},
                {"type": "start_game"},
                {"type": "loop_game"},
                {"type": "stop_game"},
                {"type": "level_stats", "level_id": 1},
                {"type": "exit_to_level", "level_id": 2},
            ],
            "strings": {},
        },
```

**Comment by Richard-L** [comment]
Hey Carlo, I also assumed you meant the demonstrations that play out after idling in the main menu.

I agree with you the official demos would be lovely to have supported by the installer, just because as you say people without the game can immediately try TR1M without having to pirate or enter credit card details to whoever distributes the games digitally.

I had brought this up in the [asset import](https://github.com/rr-/Tomb1Main/discussions/247#discussion-3696927) discussion from a year ago, and linked to what I think is a nice collection of TR demos by (the venerable) b122251: https://www.tombraiderforums.com/showthread.php?t=207170

Whilst he includes the PS1 and SS demos next to those of the PC, he doesn't include TRUB. There were demos for that? Since the UB files were made freeware later, it probably doesn't matter that much.

And having tested the PC demos of Vilcabamba with OpenLara, it seems they had a forced level end the moment you enter the large area with 4 wolves, and the three gates of the puzzle chambers. I thought this was curious, but I can understand why they didn't want to give away the whole level.

**Comment by carlo-bramini** [comment]
> Whilst he includes the PS1 and SS demos next to those of the PC, he doesn't include TRUB. There were demos for that? Since the UB files were made freeware later, it probably doesn't matter that much.

Yes, it seems to me that there are also demo versions for Unfinished Business extension.
I had found them, together with the demo version for PC, at this address:

https://allgamestaff.altervista.org/download-tomb-raider/tr-1/

**Comment by carlo-bramini** [comment]
I tried to play a bit with the code of Tomb1Main and the demo version of Tomb Raider for PC.
I wrote a new .json5 file for this task, but at first try the engine hangs with an error.
After some research, I found the explanation in this documentation:

https://opentomb.github.io/TRosettaStone3/trosettastone.html

In this page, at chapter "10.10 Differences between normal TRs and Demos", it is written that:

```
The TR1 and Unfinished Business (.TUB) demos have their palettes moved to between the SpriteSequences and the Cameras.
```

So, I did a quick hack into `level.c`, function `Level_LoadFromFile()` by commenting this code:

```
if (!Level_LoadPalette(fp)) {
    return false;
}
```

and moving it between the calls to `Level_LoadSprites()` and `Level_LoadCameras()`.
After doing this change, the demo of the game started with Tomb1Main and it's fully playable.

Probably, the best solution is to add an optional item into `struct GAMEFLOW`, perhaps by reading it from the json file without hardcoding anything into the main code.
I hope that you will find it useful.

**Comment by Richard-L** [comment]
So nice the demo files can be played - I love it. Thank you so much 👏

**Comment by Richard-L** [comment]
@walkawayy why has this never made it into the game? It seemed completed?

**Comment by walkawayy** [comment]
> @walkawayy why has this never made it into the game? It seemed completed?

I'm not sure. I didn't create this pull request. Maybe @rr- can elaborate? I wouldn't mind finishing it if there was some guidance on what needs done.

**Comment by carlo-bramini** [comment]
It looks like that some changes have been done in the meanwhile, so I did few small fixes to the PR, to make it working again with master.

**Comment by rr-** [comment]
I don't see the changes. https://github.com/LostArtefacts/TR1X/pull/722

**Comment by walkawayy** [comment]
> It looks like that some changes have been done in the meanwhile, so I did few small fixes to the PR, to make it working again with master.

Can you push your changes if you still have them? I can try to finish the PR if you don't have time.

**Comment by carlo-bramini** [comment]
> Can you push your changes if you still have them?

I will do it.
