### ISSUE TITLE
Disabling Xbox 360 controller input

### ISSUE THREAD

**Issue by vaibhavrmahadevan** [LostArtefacts/TRX#669]
I checked out the latest version and found out that both the controller input and the user key map through AntiMicroX were being read at the same time. I tried disabling Xbox one controller in the JSON file but the issue still persisted. I had completed a play through Pop! OS using AntiMicroX earlier this year so I feel it may be an issue on my end :(

OS: Linux Mint 21 
Controller: Redgear Pro Series Wireless Gamepad (Xbox 360 controller)

**Comment by walkawayy** [comment]
Are you using the latest [2.11 version](https://github.com/rr-/Tomb1Main/releases/tag/2.11)? The Xbox controller option shouldn't exist anymore? The controller should be read natively now in the game without the need for something like AntiMicroX or JoyToKey. But I will admit I have only played on Windows.

**Comment by vaibhavrmahadevan** [comment]
@walkawayy oh I see 

The json file I edited might have been a part of the older version

I think waiting for the customisable controller inputs in a future version is the answer :)

I want to thank everyone for the wonderful work done with this project and wishing the very best for the future!💗

**Comment by walkawayy** [comment]
Yes I am hoping to finish it soon, but it will probably require testing too. Ok I am going to close this issue. Feel free to reopen in the future if the new release still has this problem.

**Comment by vaibhavrmahadevan** [comment]
@walkawayy Hi walkawayy!

Really loved the new update and I feel bad for asking whether controller input could be turned off as I have become more comfortable using AntiMicroX for playing TR1 and 2 as I can map both right trigger and B for action
