### ISSUE TITLE
Save crystal collision pushes Lara through walls

### ISSUE THREAD

**Issue by AshRusty** [LostArtefacts/TRX#682]
The problem is that the save crystal is located right above pickup and Lara can't pick it up, she gets stucked in the hitbox of the save crystal. Is there any way to fix this issue like fixing the hitbox of the save crystal or moving it nearby that place so it won't interfere?

**Comment by walkawayy** [comment]
Definitely a bug. For now, I was able to still grab the idol by getting close and pressing action to bypass it until it's fixed.

**Comment by AshRusty** [comment]
> Definitely a bug. For now, I was able to still grab the idol by getting close and pressing action to bypass it until it's fixed.

Also I met this bug in St.Francis Folly
