### ISSUE TITLE
Rats' death position is broken after killing them in the water and draining the water out.

### ISSUE THREAD

**Issue by BlackWolfTR** [LostArtefacts/TRX#687]
Rats' death position is broken after killing them in the water and draining the water out. 
This wasn't the case in the OG version. They seem like they are still alive.
![20221229_190338_The_Cistern](https://user-images.githubusercontent.com/111443302/210428455-15aa7d3e-ab6f-46d8-a272-2491e3a641b2.jpg)

**Comment by walkawayy** [comment]
I killed the rats in the water then drained the room. The rat appeared dead on the ground like normal (see the one in the back). The only weird thing was the second rat died in an awkward spot and got stuck, but that seems like a different issue.

![20230111_193800_The_Cistern](https://user-images.githubusercontent.com/81546780/211948336-e67314e3-0ecc-4f31-a4c5-4a62e7b24dbf.jpg)


The dead rat remained on the ground when I added the water back. I'm not sure if that's a bug or not. (I drained the water a second time and the rat stayed dead on the ground)
![20230111_194107_The_Cistern](https://user-images.githubusercontent.com/81546780/211948672-d3e05062-26ed-45ca-bfe2-7d49abe5edba.jpg)

**Comment by walkawayy** [comment]
Rat appears alive after draining the water. (And crocodile stuck dead in midair). 
https://www.youtube.com/watch?v=YF5ejDPN_Ww

If you save and reload after killing the rat in the water, the rat appears alive and stays at the old water level even after the room is drained. In TombATI the rat stays dead and floats a little to the top after reloading, and the rat doesn't float mid-air after the room is drained.
https://www.youtube.com/watch?v=xlIoXP6r3P4

**Comment by walkawayy** [comment]
This broke all the way back in march 14, 2021 with this commit.

https://github.com/rr-/Tomb1Main/commit/2aa66a0ce3f54d298f89f2ae619089467fd01fff
