### ISSUE TITLE
Reinstate classic health and air bar style

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#698]
Apologies in advance for posting something so nitpicky and annoyingly "purist", but I still cant help notice this after all this time.

If…
```json5
"enable_smooth_bars" : false,
```
…could I ask to have the authentic PS1 health and air bar style be reinstated?

When TR1M came out I thought this was just a case of having to find the right bar scaling, but I could never reproduce the same classic look.

I looked into it a bit more, and the differences are of course rather marginal:
- bigger grey border
- no bevel effect in the border
- bigger black padding inside the border
- the 5 colours making the gradient are slightly different to what TR1M uses, and each in equal height

![Health Bar](https://user-images.githubusercontent.com/4934209/212486248-6b1b2e3b-ad82-44cc-b333-bc9eeb0c26b8.png)

![Air Bar](https://user-images.githubusercontent.com/4934209/212486258-834b6682-c9fa-4a48-93ff-a49b6c084820.png)

It just feels to me that if someone chooses to not use the smooth bars, they should nail the classic look.

Thanks for considering.

**Comment by Rapora9** [comment]
I was just today trying to make the health bar look as close to PS1 as possible. I would definitely like to see this change to be made. Thanks for posting :)

**Comment by rr-** [comment]
In my opinion we can ditch the T1M altogether in favor of the PS1 healthbar. It looks way better. Thoughts?

**Comment by aredfan** [comment]
I'm also okay with this idea.  The PS1 bars looks great.

**Comment by Richard-L** [comment]
Personally would be happy for it.

**Comment by Rapora9** [comment]
Sounds good to me too.

**Comment by walkawayy** [comment]
How does this look?

Smooth:
![image](https://user-images.githubusercontent.com/81546780/224598362-f5df7c11-fd38-478b-83d0-a68a87091efe.png)

Not smooth:
![image](https://user-images.githubusercontent.com/81546780/224598160-0d8140aa-2ff6-4233-adb8-4d9d024acf78.png)


Smooth:
![image](https://user-images.githubusercontent.com/81546780/224599099-55708184-09b7-42d0-9a52-f30d0aefb150.png)

Not smooth:
![image](https://user-images.githubusercontent.com/81546780/224598971-c111bd69-46bc-43c8-9516-44ed1a999a76.png)

**Comment by rr-** [comment]
Looks great to me

**Comment by Richard-L** [comment]
@walkawayy any chance you could post a test build? It looks nice but the outer edge I think is a bit slim (?)
Think if we're doing this kind of minute cosmetic fix (which is super appreciated btw) we should make sure there is no crying over wrong pixels later.

**Comment by walkawayy** [comment]
Sure. I didn't touch the border size.

[Tomb1Main Classic Bars v1.zip](https://github.com/LostArtefacts/Tomb1Main/files/10957300/Tomb1Main.Classic.Bars.v1.zip)

**Comment by Richard-L** [comment]
Thanks so much 🙏
I have some business in London this week so I hope it can be a few days.

**Comment by Richard-L** [comment]
@walkawayy it's still not close to the classic look.

Please check the border spacings, size, colours, and top/right (or left) offset from viewport.
![SLUS-00152_2023-03-14_23-44-42](https://user-images.githubusercontent.com/4934209/225159440-4e503786-e753-4632-9ba6-4a75aceea6ec.png)

I tried replicating the scale but the screenshot function seems to cap bar scale at x2.0 even if you set it higher, and even if it appears bigger in game.

**Comment by walkawayy** [comment]
I only updated the colors of the bar and the border color. I didn't touch any of the sizing. I can look into that though. I'd have to tag @rr- to make sure he's ok with messing with all of that other stuff. I originally thought the issue was about the coloring.

**Comment by walkawayy** [comment]
How does this look? This is a bar scale of 1. 🤔 

480p:
![20230315_235030_Colosseum](https://user-images.githubusercontent.com/81546780/225510163-66a27c1e-2cc0-482a-b176-18c1b35f833a.jpg)

1440p:
![20230315_235255_Colosseum](https://user-images.githubusercontent.com/81546780/225510181-a14fe012-fb52-4f3b-8285-926b6964f23b.jpg)

**Comment by Richard-L** [comment]
That's seriously nicer! 👍

Did you not want to have banding inside the gradient to obtain an even more classic look? Guess it becomes very personal preference at this point, but the smoothness of the gradients is strange to my eyes fwiw.

**Comment by walkawayy** [comment]
Oh I was testing with both smooth and unsmooth. The screenshots I took are with smooth on. I can post the classic look later.

**Comment by walkawayy** [comment]
Unsmooth example

480p:
![20230317_103843_Colosseum](https://user-images.githubusercontent.com/81546780/225936177-fb54811f-e01c-4d67-9101-047827955e8a.jpg)


1440p:
![20230317_103832_Colosseum](https://user-images.githubusercontent.com/81546780/225936188-b0d9f77a-c075-479e-a57e-8773d98198f0.jpg)

**Comment by Richard-L** [comment]
Looks amazing walkaway! Really well done.
The lightest blue tone on the air bar seems to be ever so slightly brighter than the hex colour code on the PS1. Is that intentional at all?
And do we want to mimic viewport position of the bars as well or leave as is?

**Comment by walkawayy** [comment]
> Looks amazing walkaway! Really well done.
> 
> The lightest blue tone on the air bar seems to be ever so slightly brighter than the hex colour code on the PS1. Is that intentional at all?
> 
> And do we want to mimic viewport position of the bars as well or leave as is?

I could double check, but I used the color codes you provided.

I tried to mimic the PS1 version's viewport for 480p. I didn't touch how the scaling gets done for higher resolutions yet. But for higher res, idk if it makes sense to keep the size of the big PS1 bars? I wanted to get feedback on that.

**Comment by Richard-L** [comment]
How does the bar scaling work? Is it just 1:1 where on hi-res you'd need to increase it to avoid tiny bars, and lower it on low-res as otherwise the bars are too big?

**Comment by walkawayy** [comment]
> How does the bar scaling work? Is it just 1:1 where on hi-res you'd need to increase it to avoid tiny bars, and lower it on low-res as otherwise the bars are too big?

The bar is designed for the lower res. I didn't implement how it scales with resolution or bar scaling option, so I'd have to read how it's done.

**Comment by walkawayy** [comment]
New test build:
[Tomb1Main Classic Bars v2.zip](https://github.com/LostArtefacts/Tomb1Main/files/11024073/Tomb1Main.Classic.Bars.v2.zip)

480p:
![20230320_203757_Colosseum](https://user-images.githubusercontent.com/81546780/226494373-6fed3c64-9489-4575-98a4-a7baf2e32d3f.jpg)


1440p.
![20230320_203805_Colosseum](https://user-images.githubusercontent.com/81546780/226494381-7c8458a8-5b14-48f8-888f-305cccaae1f0.jpg)


I tried to make the ammo text size more comparable to the PS1 size.
![image](https://user-images.githubusercontent.com/81546780/226494111-432a312e-a180-48cd-8bfa-bcc4ef356635.png)

**Comment by walkawayy** [comment]
Here's a 1440p pic with an enemy health bar:

![20230320_203911_Sanctuary_of_the_Scion](https://user-images.githubusercontent.com/81546780/226494498-19ca5eac-ffc9-48fc-bbdf-d9a4556b56e7.jpg)

**Comment by Richard-L** [comment]
Looks really beautiful. And really great you also scaled the ammo text! Can't wait to try once.

One thought: is it happy in cases where you have low health and swim, so that both bars need to stack?

**Comment by rr-** [comment]
Good point about having low health underwater from Richard.
This looks amazing. I think we're ready to open a PR for this and get it out to the people so that they play with it?

**Comment by walkawayy** [comment]
> Looks really beautiful. And really great you also scaled the ammo text! Can't wait to try once.
> 
> One thought: is it happy in cases where you have low health and swim, so that both bars need to stack?

There are no underwater weapons in TR1, so the ammo drawing isn't an issue. As for the stacking, I'll double check all the resolutions tonight, but the stacked bars look like the pics from my earlier post: https://github.com/LostArtefacts/Tomb1Main/issues/698#issuecomment-1471261683. (I decided to use `Screen_GetRenderScale(padding/border=2)` and let that function scale the padding/border size for each resolution.)

I also need to double check everything looks ok with the bars in all different positions (chosen through the config tool). Right now I've just been doing top right to mimic the PS1 style. One thing I did notice was that the PS1 version has fixed positions. So the air bar is always in the same spot (shifted down) even if the health bar is not present. IMO I like how T1M handles it better where the air bar moves up to the health bar position if Lara's health isn't damaged/low. But I just wanted to note that.

![image](https://user-images.githubusercontent.com/81546780/226640840-72b8ecae-75a7-4000-a180-bf56ec22b035.png)

**Comment by rr-** [comment]
I agree that we shouldn't use fixed positions and should leave the current dynamic positioning.

**Comment by Richard-L** [comment]
Was thinking too whether the PS1 positions are desirable or not. I would probably prefer them, but that's mainly just personal preference from playing the PS1 version the most. I think it can be nice to know your health always in the same spot sometimes. The scenario I meant with both bars stacked is when a croc attacks you under water and both bars show. If you have a dynamic positioning I suppose that will almost always mean the air bar came first and the health bar will show under it.
What if someone has their health bar set to flashing when low? I guess that will reserve the top spot for the health bar for them and the air bar would then come second, however it would be first if health is high and thus not flashing?
I'm not sure this potential for position mixing is great, but at the end of day it's also not super important maybe. It's more of an issue with TR3 that has 4 bars.
Also walkaway NB the bar positions change from right to left even on PS1 across the western and Japanese versions ;)

EDIT: had a chat with walkaway who explained that the health bar will always be on top. I had assumed it works in a FIFO dynamic kind of way, so my above message is likely a bit confusing/irrelevant.
