### ISSUE TITLE
Touching the mummy in Tomb of Qualopec does not count as a kill

### ISSUE THREAD

**Issue by Arthandas** [LostArtefacts/TRX#701]
1) To get 8/8 kills in the level you need to shoot the mummy in the room with the Scion. If you get too close it will lunge at Lara and become noninteractive leaving the player with 7/8 kills at max.

Solution A (preferable): Allow shooting the mummy when it's lying down.
Solution B: Make triggering the lunge count as a kill.

Note: Defeating Larson counts as a kill. IMO it shouldn't and the level stats should show max kills as 7, not 8.

2) Loading the game after picking up the Scion will make it respawn. It can be picked up again along with triggering the cutscene (Lara will cover but no debris falls this time). I'm attaching a screenshot where I have two Scions :)
![Tomb1Main 2023-01-15 15-40-16](https://user-images.githubusercontent.com/41027064/212548233-53286cce-378c-45d6-8f27-b337de21ed3a.png)

**Comment by Rapora9** [comment]
Case 1 is because the mummy dies if its hitpoints go to 0 or if Lara touches it. Allowing player to kill it again (solution A) while it's already dead isn't a good solution in my opinion. There's 2 more possible solutions: remove the mummy from the kill count since it's not a "proper" enemy anyway, or do nothing and consider this similar to leaving an area (that you cannot return to) while not killing all enemies in that area. I don't really see this as a bug.

_I would either make it count as a kill by Lara if you touch it, or remove it from the kill count._

What comes to Larson, that's a proper enemy and a proper fight, and I think it should count as a "kill". Think of **Kills** more like **Won fights** or **Defeated enemies**.

**Comment by Arthandas** [comment]
> Case 1 is because the mummy dies if its hitpoints go to 0 or if Lara touches it.

Except the game counts it as a kill only in the first case.

> Allowing player to kill it again (solution A) while it's already dead isn't a good solution in my opinion.

Depends on how you think about it. Since the game doesn't treat it like a kill you may argue it's lying on the ground "alive". But  yes, making the lunge count as a kill is probably the most elegant solution.

> remove it from the kill count

I wouldn't. You can interact with it, it has an HP bar and you can shoot it.

> What comes to Larson, that's a proper enemy and a proper fight, and I think it should count as a "kill". Think of **Kills** more like **Won fights** or **Defeated enemies**.

Fair enough.

**Comment by Arthandas** [comment]
I know the mummy is a very small issue but on the other hand I was doing a 100% run (all kills, secrets and items) and I've spent like an hour running across the whole level searching for the 8th enemy (I triggered the lunge earlier and was unknowingly stuck at 7/8 kills).

**Comment by walkawayy** [comment]
I agree that the Larson "kill" isn't really a bug.

We can add the mummy to the kill count if it's interacted with and not shot.

**Comment by Rapora9** [comment]
> > Case 1 is because the mummy dies if its hitpoints go to 0 or if Lara touches it.
> 
> Except the game counts it as a kill only in the first case.
> 
> > Allowing player to kill it again (solution A) while it's already dead isn't a good solution in my opinion.
> 
> Depends on how you think about it. Since the game doesn't treat it like a kill you may argue it's lying on the ground "alive". But yes, making the lunge count as a kill is probably the most elegant solution.

That is because the kill count update is tied to Lara killing something with guns. So the game doesn't see touching the mummy as a kill, but it does think it as a death of the mummy.


_The Scion load bug should probably be a separate issue btw._
