### ISSUE TITLE
Scion respawns after loading in Tomb of Qualopec

### ISSUE THREAD

**Issue by Rapora9** [LostArtefacts/TRX#707]
This was mentioned by @Arthandas in #701 but it was buried under the mummy thing so I decided to bring it back. Text and the image are theirs:

> Loading the game after picking up the Scion will make it respawn. It can be picked up again along with triggering the cutscene (Lara will cover but no debris falls this time). I'm attaching a screenshot where I have two Scions :)

![kuva](https://user-images.githubusercontent.com/97730054/212570783-ae0641aa-1f05-45a2-8ce0-90a827adf5e5.png)

Additional information by me: this happens in TombATI as well.

**Comment by walkawayy** [comment]
No wonder I couldn't figure out what commit broke this. It happens in TombATI too.
