### ISSUE TITLE
Climbing animations for 2 and 3 click heights bugged in some cases

### ISSUE THREAD

**Issue by Rapora9** [LostArtefacts/TRX#720]
Here's a test level with 2 rooms: lower blue and upper brown.

![kuva](https://user-images.githubusercontent.com/97730054/214602068-bc87df1c-15d7-4e9d-8b37-65d23788505a.png)

When Lara climbs up from the 4 click height spot, everything goes fine. When she climbs up the 2 or 3 click height, she will glitch through the floor and end up in the lower room. If there's a pushable block under the floor (circled 2), she will drop form the ceiling of the upper room. If there's solid wall under the ceiling (circled 3), she will climb up fine.

I couldn't think of any case like this in OG levels. I think the room border/portal needs to be in that position so that Lara transitions from the lower room to the upper room during the climbing animation. Also in some cases with 4 click height Lara refuses to do  the climbing up animation, but I guess that's a separate issue.

TEST LEVEL
[LEVEL1.zip](https://github.com/rr-/Tomb1Main/files/10500713/LEVEL1.zip)

**Comment by Rapora9** [comment]
Here's every spot in a video to show clearly what the issue is.

https://user-images.githubusercontent.com/97730054/214638095-4d8ae063-6be5-4646-ae09-bb301dfd3448.mp4

**Comment by walkawayy** [comment]
According to Troye:
```
u can’t fix that without changing the level files I’m pretty sure
It’s because TranslateItem in AnimateLara moves Lara to the new position
so the game tries to find a new room number, and detects the low one
The common fix is to change the anim commands to move lara twice (up, then forwards)
I once tried to fix it in code but I failed
```

And ChocolateFan:
```
we would need to change level files and also the code because
we would need 2 SetPosition
and if memory serves an anim can have only 1
```

**Comment by Rapora9** [comment]
Tough luck. I guess the only option to avoid this is to arrange the portals in a different way.

Should this be closed as "won't fix" or something?...
