### ISSUE TITLE
Bugs with pushable blocks that are placed on air (and triggered to fall)

### ISSUE THREAD

**Issue by Rapora9** [LostArtefacts/TRX#723]
Reporting some more issues with pushable blocks, this time when they fall down. I'm not sure if these bugs are caused by Tomb Editor because so far they only happen in a custom level. Then again there's only 2 places in OG levels (Thor room, TNT in Natla's Mines) where this mechanic is used, so maybe they somehow avoid it. In Thor room it might be related to how the hammer stands on the trigger. Maybe.

I will keep testing and reporting here if I find more info, and hopefully someone can take a look at these issues. Also, some of the issues might be a result of misusing the blocks? Would be nice to know what can be done and what can't.

Anyway, to the point. Here's a clip that shows some of the core issues. Under certain circumstances, if you put blocks on the air (with intent to make them fall), the data is not updated correctly and Lara can go through blocks or they can form invisible "blocks" (that can be stood/climbed on). Saving and loading makes it wrose. Below the video I will try to explain all the conditions I'm aware of. The list might seem big but I think they all stem from the same 1-3 reasons.

https://user-images.githubusercontent.com/97730054/215189076-df6da13e-caba-41cd-bb05-8b9a9c323e58.mp4

[LEVEL1.zip](https://github.com/rr-/Tomb1Main/files/10522847/LEVEL1.zip)

The blocks may act differently if they're set invisible or not, and based on where they are put: in a room where there's floor below (floor room) them or portal (portal room).

BEFORE ACTIVATING and NO SAVE/LOAD
- visible block in floor room: there's an invisible "block" below it, and the block itself has no collision
- visible block in portal room: there's flickering and camera issues below the block, and no collision for block itself
- visible block above ceiling in portal room: flickering and camera issues below the block, no collision for block itself

SAVE/LOAD and then ACTIVATING
- invisible block in floor room: falls 1 block below the floor
- visible block in floor room: lands on top of an invisible "block"
- visible block in portal room: flickering / camera issues on the same spot as above
- visible block above ceiling in portal room: flickering / camera issues on the same spot as above

SAVE/LOAD and then ACTIVATE and then SAVE/LOAD
- invisible block in floor room: there's 1 block "hole" in the floor now
- visible block in floor room: finally normal
- invisible block in portal room: has no collision now
- visible block in portal room: has fallen through the floor, flickering / camera issues on the same spot as above
- visible block above ceiling in portal room: block has no collision

ACTIVATE
- visible block in floor room: lands on top of an invisible "block"
- visible block in portal room: flickering / camera issues in the bottom of portal room (same spot as above)
- visible block above ceiling in portal room: flickering / camera issues in the bottom of portal room (same spot as above)

ACTIVATE and SAVE/LOAD
- visible block in floor room: no collision
- invisible block in floor room: no collision, still 1 invisible "block" below it
- visible block in portal room: no collision and flickering / camera issues in hte bottom of portal room (same spot as above)
- visible block above ceiling in portal room: no collision

As you might see, "invisible block above ceiling in portal room" has never any problems. This is how the block is set up in Thor room. So you could maybe argue it's the only way to use the blocks. However given how hacky the TR games are, I think this is just the first way they got it to make and never needed anything else so it stayed like that. It would be nice to have more options for level builders to use this mechanic, and also be able to have the blocks visible and still working correctly (most of the problems are for the visible blocks).

**Comment by Rapora9** [comment]
Found at least something in Thor room, not sure if related. If you are in this spot (can be reached by jumping from the block), and the camera angle is correct, the room is clipped.

![Näyttökuva (219)](https://user-images.githubusercontent.com/97730054/215220430-b8290a62-ef5f-4c2e-874d-8f8f93393ea8.png)

![Näyttökuva (220)](https://user-images.githubusercontent.com/97730054/215220451-f7b765b4-cb6f-485c-86a7-a2f8f077bb5e.png)

**Comment by rr-** [comment]
> Found at least something in Thor room, not sure if related. If you are in this spot (can be reached by jumping from the block), and the camera angle is correct, the room is clipped.
> 
>(images)

Isn't this a completely separate bug? If so, it should be filed as such. Does it happen in the OG too?

**Comment by Rapora9** [comment]
I tested it more. It happens in TombATI as well. And based on my new findings, I think it's indeed related to this bug.

- the camera clipping room(s) is similar to "camera issues" with the test level blocks.
- you don't have to be in that spot in the air; the important part is that the camera is in the same tile as the block. See the new video clip too.
- THIS ONLY HAPPENS AFTER YOU SAVE & LOAD. See how the issues in the original post always got worse after save&load.


https://user-images.githubusercontent.com/97730054/219434565-0fcb8967-0ac1-49a1-8d64-63f8c36e9fd5.mp4
