### ISSUE TITLE
Add support for save states and game rewind

### ISSUE THREAD

**Issue by crashGG** [LostArtefacts/TRX#727]
It would be great if could add periodic saving of memory snapshots to support rewind.
For example, a memory snapshot is saved every 0.1 seconds, A total of 10 seconds. Maybe 1~2G of memory will be occupied
Because the Tomb Raider has a very high frequency of death, it has to save and read files frequently. If the rewind function is added, then players (more new modern players) will not need to read and save files frequently , just rewind in place for a few seconds after death. It will be a smooth experience like no other.

**Comment by Richard-L** [comment]
There's already this I think https://github.com/rr-/Tomb1Main/issues/600

And you know you can always dozy revive and fly back to where you were 😉

**Comment by rr-** [comment]
This is pretty much the same as #600, closing as a duplicate. The idea of manual rewind like the seekbar in YouTube videos is not going to happen.
