### ISSUE TITLE
Save crystal collision is broken

### ISSUE THREAD

**Issue by Rapora9** [LostArtefacts/TRX#729]
Save crystal collision reaches below and above the crystal, even beyond rooms and floor/ceiling, making a "beam" that Lara cannot go through. It doesn't extend like this in all places, but this is very noticeable for example in St. Francis Folly with a lot of platforms and save crystals. 

Let me know if you need more information of the situations where this happens, and I can test.

https://user-images.githubusercontent.com/97730054/219439927-de22d69c-f7e3-40f8-a21f-18bbe0d3f88e.mp4

**Comment by walkawayy** [comment]
Already fixed in #691 (issue #682). Will be out in the next release.
