### ISSUE TITLE
Tomb Raider HD Textures with Gamma Corrected + Remastered Cutscenes + Missing Audio. Is the wrong Track being played at the Start of Unfinished Business ?

### ISSUE THREAD

**Issue by Kristijan1001** [LostArtefacts/TRX#732]
So i have this for over 5 years on my HDD, dunno exactly where i got it all, long time ago i setup all my games to the best possible version. I just recently discovered this. 

Noticed that there are no HD Textures even though they were available back then, also i noticed not sure if i am wrong on this but the wrong soundtrack is played at the beginning of Unfinished Business.

The Textures should work both on Main Tomb Raider & Unfinished Business. Also i included Remaster of the Cutscenes, which also not sure where i got them from. I have all this in playable form with Gildos with the DOS version, since i didn't know how exactly to get tombati to work with the textures and audio.

My Unfinished Business Soundtrack that plays at the start:

https://user-images.githubusercontent.com/24441639/219484894-f12bdc1d-a88f-4d44-8646-227fbbb54170.mp4

HD Textures + FMV:

https://user-images.githubusercontent.com/24441639/219487188-1ebeaf22-8c7f-4f77-ab57-eae97403d78c.mp4

HD Picture:

![lCOvLiy8zV](https://user-images.githubusercontent.com/24441639/219487399-049fb414-d5d0-4ff5-b349-fe0388d9e915.jpg)

Download:

https://mega.nz/file/UYQwnT6b#jRz1Y4xLNLw69TkXu6WPQrAj48jzV_C5sDvmF5npvzI

**Comment by rr-** [comment]
This issue lacks focus - each of the problems should be reported separately.

Support for texture packs is tracked in #347.
Support for HD FMV is there, you just need to put the FMVs in the folder. We don't supply them.
Audio in UB was always a touchy topic since the true originals never had any music, it had to be added by fans.

**Comment by Kristijan1001** [comment]
> This issue lacks focus - each of the problems should be reported separately.
> 
> Support for texture packs is tracked in #347. Support for HD FMV is there, you just need to put the FMVs in the folder. We don't supply them. Audio in UB was always a touchy topic since the true originals never had any music, it had to be added by fans.

I see, since this is a dupe i will just go ahead and close this. Thanks for the reply.
