### ISSUE TITLE
Larson's gun texture issue | Tomb of Qualopec

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#737]
The recently added injection feature have opened up new possibilities for T1M, and so I thought it's worth putting in this request.

Personally I don't understand the process behind the injection feature so if my suggestion doesn't work then please feel free to close this issue.  That being said, when Lara gets into a gunfight with Larson after collecting the first scion, Larson's gun seem to use a incorrect texture.

![20230221_110150_Tomb_of_Qualopec](https://user-images.githubusercontent.com/94776985/220335457-87d789c6-cc4a-4e16-bc7b-c78929f8463b.jpg)

In the following cutscene, Larson's weapon is grey as it should be (it's on the ground near Lara).

![20230221_110158_Cut_Scene_1](https://user-images.githubusercontent.com/94776985/220335762-9691656a-fe73-4fcf-82d9-8f70805a42f4.jpg)

Also in Sanctuary of the Scion, here's Larson holding his gun, again using the correct texture.

![20230221_110653_Sanctuary_of_the_Scion](https://user-images.githubusercontent.com/94776985/220335842-ac4d2d53-e8de-4136-b092-79bc75ff9944.jpg)

**Comment by walkawayy** [comment]
Hm looks like a level asset issue. Could be possible to fix with injection @lahm86 ?

![image](https://user-images.githubusercontent.com/81546780/220409482-74a560c5-ad6d-4701-8068-e1be212ad069.png)

**Comment by lahm86** [comment]
Yes, this is definitely fixable. I'm happy to take a look at this.

**Comment by Richard-L** [comment]
Hah interesting. Tested on PS1 and it's the same.
Are we sure the texture during the FMV isn't "wrong" though? It just looks like he has a rusty gun during this fight, and then a new one in the later fight. But I don't mind either way.

**Comment by aredfan** [comment]
> Hah interesting. Tested on PS1 and it's the same. Are we sure the texture during the FMV isn't "wrong" though? It just looks like he has a rusty gun during this fight, and then a new one in the later fight. But I don't mind either way.

I also checked the Saturn version on a video from YouTube and it's the same - Larson has a "rusty" gold-looking gun during the Peru gunfight, then "clean" gun in the following cutscene and again later in the game.

You do make a good point though, there's no way to be sure which gun texture is correct. But at least this proposed fix will give Larson a consistent weapon throughout the game.

**Comment by aredfan** [comment]
TRFan94 shared an image of Larson from one of the betas on discord.  I'm guessing the gold-looking gun is a leftover from beta.

![image](https://user-images.githubusercontent.com/94776985/220852444-4ae15e4b-baec-4e27-8eca-17e5f0dd7e75.png)

**Comment by lahm86** [comment]
I notice here that there is mention of it being white in earlier builds - https://core-design.com/article93.html
So I suppose the fact that it's grey in the cutscene and in Sanctuary, means it should really be grey in Qualopec too? I think if it didn't appear in the cutscene you could argue that he replaced his gun before reaching Sanctuary, but otherwise I'm inclined to say it should be grey throughout.
