### ISSUE TITLE
"enter" key does not work

### ISSUE THREAD

**Issue by legluondunet** [LostArtefacts/TRX#738]
Hello,
I installed Tomb Raider I with Tomb ATi (tested it all work as expected).
Then installed Tomb1Main, Tomb Raider launch OK, cinematics and audio played ok. 
The main menu appears, I can hear music (audio tracks in flac format played ok).
But when I press "enter" key, nothing happen.
Other keys work: escape, arrows to wheel menu OK.
Is it a bug or did I missed something?
I 'm a Linux user and I use Wine. 
I can not use Tomb1Main installer because of dotnet, so I extracted Tomb1Main  zip files in Tomb Raider main folder.
Thank you for your help.

**Comment by aredfan** [comment]
There's been some recent changes with the controls scheme, so you'll have to use the "Ctrl" key instead of enter.

**Comment by legluondunet** [comment]
tested, ctrl keys (left and right) work. Do you plan to reenable "return" key?
Another thing: is gamepad supported?

**Comment by Richard-L** [comment]
What @aredfan said. And just to add you can then map ENTER in the controls menu in-game. I use it for pause (ie PS1 Start button), and it works for me.

**Comment by legluondunet** [comment]
ok thank you all.
