### ISSUE TITLE
Unfinished Business launcher via Config Tool

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#739]
This is my second request for @lahm86 in a few days, hope he doesn't mind!

There will be times when new players run into difficulty when setting up Unfinished Business.  I think adding a "Launch Gold" button to the Config Tool like in tomb3 will make things easier for them.

tomb3 Config Tool for reference 👇 

![1](https://user-images.githubusercontent.com/94776985/220894648-9a7f7998-c6c6-4e77-a789-c349ea8f991c.png)

**Comment by lahm86** [comment]
I don't mind at all 😊. Great idea - this should be a straight-forward update.

**Comment by aredfan** [comment]
> I don't mind at all 😊. Great idea - this should be a straight-forward update.

Wonderful! Thank you for answering so quickly 👍

**Comment by lahm86** [comment]
@ajtudela Would the following translation be suitable for this addition? In English, the button will display `Launch Unfinished Business`.

![image](https://user-images.githubusercontent.com/33758420/225426022-dda54eb1-5996-4491-a12a-103e684b5596.png)

**Comment by ajtudela** [comment]
Hi!
I think it could be translated as well. The spanish translation for 'Unfinished business' would be 'Asuntos pendientes'. So, in spanish the button will display 'Abrir Asuntos pendientes'.

Great idea!

**Comment by lahm86** [comment]
> Hi! I think it could be translated as well. The spanish translation for 'Unfinished business' would be 'Asuntos pendientes'. So, in spanish the button will display 'Abrir Asuntos pendientes'.
> 
> Great idea!

Great, thanks!
