### ISSUE TITLE
Feature request: adding subtitles to cutscenes and videos.

### ISSUE THREAD

**Issue by carlo-bramini** [LostArtefacts/TRX#742]
I think that adding support for subtitles would be an interesting features that no other engines have.
This can be implemented when playing movies and when there are some speeches during gameplay.
As first step, this new feature can be started by having documented all the speeches and their timing and later they could be described inside a .json file, dedicated for multilanguage support (somehow related to issue #715).
Perhaps, some mother tongue users may help to do it, since it does not require coding skills.
Then, adding this feature when playing movies is probably less complicated than handling cutscenes, since libavformat can already help us to do it.
Actually, doing it for cutscenes is a bit obscure to me, since the demo files have not something useful for testing, but I think that it can be also done if somebody wants.

**Comment by vvs-** [comment]
> I think that adding support for subtitles would be an interesting features that no other engines have.

They have. See here: https://github.com/XProger/OpenLara/tree/master/src/lang

**Comment by Richard-L** [comment]
Like @vvs- said, OpenLara has had this for 5+ years or so. Other than the cutscenes, there are also subtitles for any kind of speech, like for example the gym:
![image](https://user-images.githubusercontent.com/4934209/221360392-ff8f6fe2-65f1-4d71-8234-d5a75c282716.png)

There's support for the 4 retail languages (English, French, German, Japanese), the Russian fandub, and then another 6 subtitle/interface languages, latter which it combines with the English dub. Consequently XProger has done a lot of work on the glyphset for all these languages. Cf https://github.com/LostArtefacts/Tomb1Main/issues/386#issuecomment-1027866433

Nevertheless a really nice and perfectly worthwhile feature. Imo a subtask of a larger "localisation" effort.

**Comment by walkawayy** [comment]
Hopefully we can do this sometime in the future. Lot of good info here but it's a duplicate, so I am gonna close this but link to the original issue #382.
