### ISSUE TITLE
Kid's & Kold's texture issues | Natla's Mines

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#744]
It's been a pretty exciting time for the T1M project - seeing texture fixes getting done here and there, from the Colosseum roof to the [black mesh faces](https://github.com/LostArtefacts/Tomb1Main/discussions/736).

I would like to put in another request for a texture fix by @lahm86, if you're okay with the idea (sorry to keep you busy lately 😅)

I read the [article](https://core-design.com/article93.html) you've shared earlier and one issue that stood out to me is the yellow texture on Skateboard Kid's right arm.

![1](https://user-images.githubusercontent.com/94776985/221406412-528bea9a-e30a-449c-bd43-c5ca310049d8.jpg)

In addition to the right arm there are 3 other faces with yellow textures on Kid, one on the neck and two on each hand where the Uzis meet.

![2](https://user-images.githubusercontent.com/94776985/221407963-4b2fbd88-6fb7-45f8-b21d-925326dbb603.png)

I have 2 suggestions for tackling this issue.  The first is to do what's necessary and that's just to correct the texture on Kid's right arm.  The second is to do a "clean job" and fix all the yellow textures on Kid.  Personally I'm in favour of the second option.

@Richard-L @walkawayy and if anyone else's interested, please feel free to chime in on this issue!

**Comment by Richard-L** [comment]
I love this. Your attention to detail is great. Also agree it's an exciting time since Lahm has been such a massive enabler to the project ❤️ 

I honestly wouldn't have known these texture had yellow bits. Is the image file itself actually containing yellow, or is it a different technical reason why these faces show up like that?

Complete fix would be wonderful, but whatever Lahm says I'll follow.

**Comment by lahm86** [comment]
My guess is the model was initially created solid yellow and then they re-textured face-by-face, but they missed these faces for one reason or another. You can see his arm has three "good" textured sides, and one coloured side. We can remap this one to remain a solid colour, but to use the correct palette index (and the same for the other meshes, just as well to be thorough).

![image](https://user-images.githubusercontent.com/33758420/221411549-b701ef84-c7d5-4464-81ce-4362ff547027.png)

Kold has similar issues - well in my opinion anyway. I don't think the orange is intended at all. Should we group these together as they're related and in the same level?

![image](https://user-images.githubusercontent.com/33758420/221411647-bca35f22-e9d7-4afd-b4d5-45684a80f848.png)
![image](https://user-images.githubusercontent.com/33758420/221411969-b652d439-ae1f-43d0-9d2c-79ca57d4fb3f.png)

**Comment by aredfan** [comment]
> Kold has similar issues - well in my opinion anyway. I don't think the orange is intended at all. Should we group these together as they're related and in the same level?

Grouping these issues together is absolutely fine with me.  Also, judging by your screenshots - that is a definite improvement of Kold.  I love this change already.

Thank you for picking up this issue 👍

**Comment by Richard-L** [comment]
Oh wow the difference really is a striking improvement!

**Comment by walkawayy** [comment]
Based on the FMV, I'd say Kold having random orange patches is definitely a bug lol. Looks much nicer.

![image](https://user-images.githubusercontent.com/81546780/221422830-7fc55bf3-396f-4811-a8a8-560eeec91992.png)

**Comment by aredfan** [comment]
Just to add as it's related to this level - Cowboy has yellow textures at the end of his arms, although it's hard to spot.

![1](https://user-images.githubusercontent.com/94776985/221816843-25b8ca7c-8998-4bc8-ad45-003463b6f7f7.png)

I also checked all Larson and Natla models in both levels and cutscenes, and both look good 👍
