### ISSUE TITLE
Crash when loading a save with spaz_effect_count set

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#746]
If the game is saved while Lara is in the following animation and then reloaded, a crash occurs. This is present in TombATI as well as T1M (found by Radgryd during randomizer testing).

![20230304_144736_Atlantis_6](https://user-images.githubusercontent.com/33758420/222913048-79d95f69-0311-4a41-a0f8-e37270598534.jpg)

Saving during Lara's normal animation doesn't lead to a crash.
![20230304_144737_Atlantis](https://user-images.githubusercontent.com/33758420/222913131-52b4085b-4e7a-49ce-b755-f89938e0bb37.jpg)

The cause I think is that while `spaz_effect_count` and `spaz_effect` are [saved](https://github.com/LostArtefacts/Tomb1Main/blob/develop/src/game/savegame/savegame_bson.c#L1065), only `spaz_effect_count` is [restored](https://github.com/LostArtefacts/Tomb1Main/blob/develop/src/game/savegame/savegame_bson.c#L712).

The crash seems to occur below as `g_Lara.spaz_effect_count` is used in the condition, but `g_Lara.spaz_effect` is assumed to be set.

https://github.com/LostArtefacts/Tomb1Main/blob/develop/src/game/lara/lara_control.c#L158

**Comment by lahm86** [comment]
Savefile for Atlantis for reference.
[save_tr1_15.zip](https://github.com/LostArtefacts/Tomb1Main/files/10888958/save_tr1_15.zip)

**Comment by walkawayy** [comment]
Looks like it's a NULL pointer issue. Just trying to print ` g_Lara.spaz_effect->pos.x` on load causes a crash. `spaz_effect` gets set to `FX_INFO *fx = &g_Effects[fx_num];` depending on what caused it. Looks like that isn't being saved and restored properly in legacy or new save format.

**Comment by rr-** [comment]
Fixed in 2.13.2
