### ISSUE TITLE
T1M bug: Holsters are empty when starting a new level if shotgun is equipped beforehand

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#749]
Whether Lara has pistols, magnums or uzis holstered - each of these will disappear when starting a new level *if* the shotgun is equipped beforehand i.e. the shotgun is the weapon Lara draws.

**End of Lost Valley:**
![20230307_161153_Lost_Valley](https://user-images.githubusercontent.com/94776985/223486669-d2ffb96c-5e7f-4543-84bb-b57078870257.jpg)
**Beginning of Tomb of Qualopec:**
![20230307_161200_Tomb_of_Qualopec](https://user-images.githubusercontent.com/94776985/223486698-e4c7d22c-b2b9-4cdd-a04b-6d8d187a74be.jpg)

The outcome is the same whether "Pistols as primary weapon" is enabled or disabled.

In TombATI, pistols will always appear in Lara's holsters when starting a new level no matter which weapon is holstered or equipped beforehand.

**Comment by Richard-L** [comment]
Just to mention we'd looked at something mildly related a while back: https://github.com/LostArtefacts/Tomb1Main/issues/557
