### ISSUE TITLE
Bat does not trigger | Colosseum

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#750]
The bat (Item 73) has no trigger tile to activate it.  Lahm86 mentioned that floordata injection is coming soon so I thought it's worth opening this issue.

![image](https://user-images.githubusercontent.com/94776985/223966996-b84381d7-d613-4bc9-97af-64f9dd3b7344.png)

**Comment by lahm86** [comment]
Thanks for raising this. Bat 74 is listed twice in the two triggers in this area, so it will just be a case of correcting the duplicated index.

![image](https://user-images.githubusercontent.com/33758420/223997322-d7effb49-d787-4fe1-9765-4f2f5e8f4358.png)

**Comment by lahm86** [comment]
@ajtudela - one more translation, sorry for so many pings! This is in combination with #788 where we will be merging some options.

```json
"fix_floor_data_issues": {
  "Title": "Fix floor data issues",
  "Description": "Fixes original issues with floor data/triggers, including the following.\n- The untriggered bat in Colosseum.\n- The secret in Great Pyramid that does not register."
},
```

**Comment by ajtudela** [comment]
No problem.

```
"fix_floor_data_issues": {
  "Title": "Arreglar problemas de datos de suelo",
  "Description": Soluciona los problemas originales con los datos/activadores del suelo, incluyendo los siguientes.\n- El murciélago no activado en el Coliseo.\n- El secreto no registrado en la Gran Pirámide."
},
```
