### ISSUE TITLE
Missing trigger tile for a rat | Tomb of Tihocan

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#751]
It seems I keep raising issues for @lahm86 lately, I'm so very sorry.  Also tagging @Richard-L too in case he has any thoughts to share.

This issue is about a rat which doesn't seem to trigger until Lara gets closer.

![20230309_121008_Tomb_of_Tihocan](https://user-images.githubusercontent.com/94776985/224045903-0768e31e-d544-4771-b10d-81ab9fd20459.jpg)

The interesting thing is the trigger tiles are there and extends all the way to the edge, see the screenshot below.

![Screenshot (227)](https://user-images.githubusercontent.com/94776985/224046499-8cb1e72d-17c3-4fa1-a705-517b64121f6e.png)

However when flipmap is triggered the tiles are reduced.  I suspect this is a mistake.

![Screenshot (228)](https://user-images.githubusercontent.com/94776985/224046506-72f93f95-6feb-41df-babf-a46f972e026e.png)

**Comment by Richard-L** [comment]
I've noticed this rat in speedruns where it will always trigger a bit late. However a precise jump is used in this scenario that avoids swimming.
Are you climbing out of the water?

**Comment by Rapora9** [comment]
@Richard-L The rat should activate early in speedruns with the jump, and late when you climb out of the water. Are you sure you've seen speedruns where it triggers late? For example in this speedrun (https://www.youtube.com/watch?v=i6Am1jdLC7M) you can see the rat is triggered already when Lara is still in the first tile:

![Näyttökuva (246)](https://user-images.githubusercontent.com/97730054/224068216-7717c982-e1f2-47bf-8ec0-943ea96ba846.png)

**Comment by Richard-L** [comment]
Maybe I misconcluded this in fact. Since this rat _always_ seems to manage to hit speedrunners, I thought that had to do with it trirggering late, and thus making it impossible for the rat to miss.

**Comment by lahm86** [comment]
I agree that this looks like an oversight. We can make the flipped room's triggers match the unflipped room's so that it's consistent. I'd argue the second tile's trigger isn't needed at all - I don't think it's possible to skip the first tile, but that's not really important.
