### ISSUE TITLE
Feature request: don't kill music when enemies talk

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#762]
Similar to #17, it would be nice to provide an option to prevent enemy speeches killing the current music track. Each of these tracks has a corresponding SFX entry in the relevant level file which could be used.

* MX_BALDY_SPEECH
* MX_COWBOY_SPEECH
* MX_LARSON_SPEECH
* MX_NATLA_SPEECH
* MX_PIERRE_SPEECH
* MX_SKATEKID_SPEECH

**Comment by lahm86** [comment]
Hi @ajtudela. Would you be able to provide the translation for the new config entry for this feature?
```json
"fix_speeches_killing_music": {
  "Title": "Do not stop music when enemies speak",
  "Description": "Fixes enemies stopping the active music track when they speak."
}
```

**Comment by ajtudela** [comment]
Of course. That would be:

```
"fix_speeches_killing_music": {
  "Title": "No parar la música cuando hablan los enemigos",
  "Description": "Impide que los enemigos paren la pista de música cuando hablan."
}
```

**Comment by lahm86** [comment]
> Of course. That would be:
> 
> ```
> "fix_speeches_killing_music": {
>   "Title": "No parar la música cuando hablan los enemigos",
>   "Description": "Impide que los enemigos paren la pista de música cuando hablan."
> }
> ```

Thank you 👍
