### ISSUE TITLE
OG bug: poor arm animation with shotgun equipped

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#771]
When Lara has her shotgun equipped, her left arm suffers from poor animation in several cases.

* Walking backwards
* Starting to walk forwards
* Stopping after walking/running
* Landing while doing continuous running jumps

The following video demonstrates this.

https://youtu.be/3qyPAB-1imw

**Comment by Richard-L** [comment]
This is so odd. Must be new? I'm pretty sure I would have noticed this on a playthrough before.

**Comment by lahm86** [comment]
It's there for sure in TombATI.

**Comment by walkawayy** [comment]
> It's there for sure in TombATI.

Yep I just checked and it's the same in TombATI. Even does this slightly in the run to stop animation and hop back. Can't believe I never noticed lol.

**Comment by lahm86** [comment]
Troye and Topixtor pointed it out to me a while ago in the rando, but I hadn't ever noticed it before then either. I have been speaking to Troye and have tested a fix for it already - I'll sort that out properly this weekend.

**Comment by aredfan** [comment]
Just checked the dos version and can confirm the poor arm animation happens there.  Can't say I noticed this before lahm brought it up.

**Comment by Richard-L** [comment]
Just checked PS1 and it has it too.
