### ISSUE TITLE
Dart emitter status isn't stored in saved games

### ISSUE THREAD

**Issue by Danath85** [LostArtefacts/TRX#774]
Hello, i'm currently trying to build a TR1 level using Tomb1Main and i'm facing a problem.

Dart traps status aren't saved. 
The traps are active on level load, then i'm using a pickup trigger to deactivate. They do that correctly, but when i save and load they are back to on.

I know i can use "timer" on the trigger to set a "distance" for the trap to be active, but it would be best if it could work without it.
Is it possible to fix this?

**Comment by walkawayy** [comment]
Would you be willing to post the level file?

**Comment by Rapora9** [comment]
Little test level with darts and swinging blade. Let me know if you need more.

[LEVEL1.zip](https://github.com/LostArtefacts/Tomb1Main/files/11023771/LEVEL1.zip)

**Comment by walkawayy** [comment]
Thanks. Darts reactivate on load in TombATI too.
