### ISSUE TITLE
T1M bug: FPS counter overlaps with health bar and inventory arrow

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#787]
**T1M:**

![1 2](https://user-images.githubusercontent.com/94776985/227785383-de37d116-a26f-4f44-9606-731f07058795.jpg)
![2 2](https://user-images.githubusercontent.com/94776985/227785387-100fa4bc-09b5-40eb-b975-b6932371823c.jpg)

**TombATI, for comparison:**

![1 1](https://user-images.githubusercontent.com/94776985/227785362-d6c6bccb-419e-4075-9e5c-9cb270c0a3da.png)
![2 1](https://user-images.githubusercontent.com/94776985/227785366-9be8d156-8a23-4016-979e-21ac28f28fd6.png)

**Comment by rr-** [comment]
Let's tackle this as part of 2.14, as it updates the bars anyway.

**Comment by walkawayy** [comment]
Also happens with the healthbar when viewing a medipack.

![image](https://user-images.githubusercontent.com/81546780/229201529-02efdc57-634f-4129-b764-3bb8394d76fb.png)


Same behavior on TombATI.

![image](https://user-images.githubusercontent.com/81546780/229201439-35a227f8-2f10-4677-898b-853229e09064.png)
