### ISSUE TITLE
Feature request: Changing framerate 

### ISSUE THREAD

**Issue by Pia86** [LostArtefacts/TRX#812]
I grew up with the PAL version on Playstation and would love the option to reduce the framerate to 50 hz in order to play the game as I remember it from my childhood.

**Comment by rr-** [comment]
I don't think it's possible to fully emulate this experience on PC as it's comprised not only of FPS but also several other factors that are infeasible to implement (TV scanlines, CRT distortion, degauss, ...).  You'd be better off playing on original hardware.

On the other hand, there's certainly value to be seen in ability to freely control the framerate. The game runs at 30 FPS (including the animations), not smoother like it was contested in the opening post. Sadly, getting it to run at arbitrary FPS would require some fundamental changes and decoupling game logic from drawing, a process we're not currently ready for and we're not considering at the moment.

There used to be a patch to get the game to run at 60 FPS, which involved rendering twice as often, while updating the logic on every other frame - and we might reach a point in the future where we're ready to merge it, but anything more than that is currently not in the plans.
