### ISSUE TITLE
Rendering issue with some statics and pushable blocks

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#819]
Hello, I've noticed a few rendering issues in Tomb1Main (& TombATI) that isn't present in the dos version.  I don't have the technical knowledge to explain this bug in more detail but I thought it might be helpful to create an issue for it.

**Left: DOS | Right: T1M**

GYM - Room 7
![4](https://user-images.githubusercontent.com/94776985/235345185-157271fc-b2b5-42a4-b4ef-a9d46cf3fe97.png)
LEVEL8B - Room 16
![5](https://user-images.githubusercontent.com/94776985/235345189-88533e75-6378-48a9-b659-93cd5efc84a7.png)
LEVEL10A - Room 64
![6](https://user-images.githubusercontent.com/94776985/235345193-cc8b88b1-6db8-4d42-8965-629c717eb71c.png)
LEVEL10C - Room 18
![1](https://user-images.githubusercontent.com/94776985/235346000-ad75c7b4-f05a-42a7-8c04-e3e78a06cad8.png)

**Comment by Richard-L** [comment]
How did you upscale Dosbox like that? Looks impressive.

These rendering issues are present on the PS1 version too, even with some added culling issues (from what I understand).

Think we'd spoken about the items in Khamoon years ago when we addressed the bats in Folly, but didn't have a solution.

**Comment by aredfan** [comment]
> How did you upscale Dosbox like that? Looks impressive.
> 
I changed the resolution in the dosboxTR.conf file (included on Steam) like this: `fullresolution=1920x1080`

Also it might be worth checking if `aspect=true` for the best experience.

**Comment by aredfan** [comment]
I was watching Footi doing a speedrun earlier and I've spotted another rendering issue in Sanctuary of the Scion:

Left: DOS | Right: T1M
LEVEL8C - Room 35
![1](https://github.com/LostArtefacts/Tomb1Main/assets/94776985/d631a3f4-5a17-47b8-961f-847ba03d5adc)

**Comment by oziphantom** [comment]
What happens if you put T1M into a 4:3 graphics mode?

**Comment by aredfan** [comment]
> What happens if you put T1M into a 4:3 graphics mode?

Same outcome, here's the save files for each of the locations shown above (except the gym) which are compatible with 2.15.2.

[save_tr1_00.dat.txt](https://github.com/LostArtefacts/Tomb1Main/files/12259405/save_tr1_00.dat.txt)
[save_tr1_01.dat.txt](https://github.com/LostArtefacts/Tomb1Main/files/12259406/save_tr1_01.dat.txt)
[save_tr1_02.dat.txt](https://github.com/LostArtefacts/Tomb1Main/files/12259407/save_tr1_02.dat.txt)
[save_tr1_03.dat.txt](https://github.com/LostArtefacts/Tomb1Main/files/12259408/save_tr1_03.dat.txt)
(Note to remove the .txt extension)
