### ISSUE TITLE
OG bug: room mesh oversights

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#826]
This follows from discussion #736.

Implement injection functionality to fix each of the following room mesh issues.

1. Incorrect texture on a face
2. Misaligned vertices on a face leading to gaps
3. Missing face
4. Wrongly rotated face

See https://github.com/LostArtefacts/Tomb1Main/discussions/736#discussioncomment-5853608 for the complete list of issues identified. This should be used to generate the necessary injection files.

**Comment by Richard-L** [comment]
So epic. Thank you Lahm.

**Comment by lahm86** [comment]
HI @ajtudela - would you be able to translate the following new config option please?
```
"Title": "Fix texture issues",
"Description": "Fixes original issues with missing or incorrect textures."
```

**Comment by ajtudela** [comment]
Of course!
```
"Title": "Solucionar problemas de textura",
"Description": "Soluciona problemas originales con texturas faltantes o incorrectas."
```
