### ISSUE TITLE
Detect a new controller connection during runtime

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#850]
Currently, a controller must be connected before Tomb1Main launches. It would be nice to recognize a newly connected controller while running.

**Comment by walkawayy** [comment]
Sounds like we should wait for SDL3.

https://github.com/cemu-project/Cemu/issues/821

**Comment by rr-** [comment]
Linking to SDL rather than an offspring project: https://github.com/libsdl-org/SDL/issues/3468

**Comment by rr-** [comment]
@walkawayy they mention using polling to mitigate this and as far as I'm concerned we do polling ourselves too. In which case – why isn't it working for us?

**Comment by walkawayy** [comment]
I don't think we ever did any polling? Controller is only checked for on startup.

https://github.com/LostArtefacts/Tomb1Main/blob/4c9ae7415b81535b973dacc9ead14d891a9b493e/src/specific/s_input.c#L865

I read some about polling, and there were some complaints about it being slow. I guess we could check it once every second depending on FPS since every frame would be major overkill? Seems like the slow polling was fixed.

https://github.com/libsdl-org/SDL/issues/3717

**Comment by rr-** [comment]
I mean, we do query the status of each controller button on every frame, rather than receiving events from SDL in an event loop that such and such button was pressed.

**Comment by walkawayy** [comment]
`m_Controller` is initialized to `NULL`. It only gets set if a game controller is found during startup in `S_Input_Init` I linked:
```
            if (!m_Controller && is_game_controller) {
                m_Controller = SDL_GameControllerOpen(i);
                if (!m_Controller) {
                    LOG_ERROR("Could not open controller: %s", SDL_GetError());
                }
            }
```

The buttons are not being checked in `S_Input_GetCurrentState` if it's `NULL`:
```
    if (m_Controller) {
        linput = S_Input_GetControllerState(linput, cntlr_layout_num);
    }
```

**Comment by rr-** [comment]
Could we reopen the device every ${fps} frames if it's no longer valid? Is checking whether the device handle is still valid expensive?

**Comment by walkawayy** [comment]
Ya probably that was my idea. I'm not sure the performance cost of it.
