### ISSUE TITLE
Restart level text error in Lara's Home

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#851]
If Lara dies in the Home level, you'll get a `New Game` option which in reality restarts the level.  I'm guessing the text is meant say `Restart Level` instead.

![20230527_071305_Laras_Home](https://github.com/LostArtefacts/Tomb1Main/assets/94776985/67524f2c-eea0-4566-8d2a-2ea81758b8f9)

**Comment by Richard-L** [comment]
I seem to remember we had this topic before and walkaway said the PC version somehow can't restart the gym (?)

**Comment by aredfan** [comment]
> I seem to remember we had this topic before and walkaway said the PC version somehow can't restart the gym (?)

I assumed it was related to the Restart Level feature but perhaps it's a different kind of bug. I did some further investigating into this issue and made comparisons with TombATI.

All of the testing below is done in Lara's Home.  Highlighted parts indicate inconsistencies.

**T1M**
-Death (no saves present): Gets `New Game (restarts level)` & Exit to Title options.
-Death: Gets `New Game (restarts level)`, Load Game & Exit to Title options.

**TombATI**
-Death (no saves present): Gets Exit to Title option.
-Death: Gets Load Game & Exit to Title options.

**T1M**
-Quick Save: (no saves present): Gets New Game option which starts Caves level. 
-Quick Save: Gets New Game option which starts Caves level.
-Quick Load (no saves present): Gets New Game option which starts Caves level & `Exit to Title`.
-Quick Load: Gets Load Game option.

**TombATI**
-Quick Save (no saves present): Gets New Game option which starts Caves level.
-Quick Save: Gets New Game option which starts Caves level.
-Quick Load (no saves present): Gets New Game option which starts Caves level.
-Quick Load: Gets Load Game option.

**Comment by walkawayy** [comment]
Going to solve the restart level text error in this issue. The Quick Load bug is due to the same problem as #853, so it will be solved there.
