### ISSUE TITLE
T1M bug: Quick Load + Action creates invalid save file when no saves are present

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#853]
If the saves folder is empty, press Quick Load hotkey during gameplay and you'll get a `Save Game` option.  Press action and you'll see a fade to black then you'll return to gameplay.

![20230530_070121_Caves](https://github.com/LostArtefacts/Tomb1Main/assets/94776985/c779a2ce-edc3-45ca-a981-3991ad91ec19)

In the saves folder a file called `save_tr1_-1.dat` is created but cannot be used.

**Update:** Just to point out the difference with TombATI for when you use Quick Load without saves present:

- **T1M:** Gets Save Game and Exit to Title options.
- **TombATI:** Gets Save Game option.

**Comment by walkawayy** [comment]
@aredfan would you be able to help test the two passport fixes if I provided you a build? I tested with your scenarios listed in the linked issue and it seemed good, but I would appreciate a second pair of eyes if you had time.

[passport-fixes-v1.zip](https://github.com/LostArtefacts/Tomb1Main/files/11620113/passport-fixes-v1.zip)

**Comment by aredfan** [comment]
@walkawayy of course, happy to test your fix.  But with this build, I get returned to the main menu when I try to access Lara's Home, New Game or loading a save file.

**Comment by walkawayy** [comment]
Hm I'm about to go to bed. But my guess is it's something related to new .bin injections that aren't in the master branch yet. I'll see if I can upload them in the morning and see if that fixes.

**Comment by walkawayy** [comment]
Try this. Put everything from the data folder in your data folder. And prob make a backup just in case.

EDIT: Oops do not use the .exe in this zip though. It's the wrong one lol sorry. Use the .exe from v1 with this data folder from v2.

[passport-fixes-v2.zip](https://github.com/LostArtefacts/Tomb1Main/files/11626485/passport-fixes-v2.zip)

**Comment by aredfan** [comment]
Yup it was the new .bin injections that got the game working again. I've tested every scenario from the same list and the v1 fixes LGTM.

Thank you @walkawayy 👍

**Comment by walkawayy** [comment]
> Yup it was the new .bin injections that got the game working again. I've tested every scenario from the same list and the v1 fixes LGTM.
> 
> Thank you @walkawayy 👍

Cool thanks. To confirm, this solves this issue and #851? The exe should include both fixes.

**Comment by aredfan** [comment]
Can confirm both issues are resolved.
