### ISSUE TITLE
Bug: hit effects when climbing up render Lara in weird places

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#857]
When Lara is in the climb-up animation and gets hit by a explosive, she's rendered one tile below for a frame or two. Not sure if this is OG bug as well.

Seeing Eycore play a mod to replace all enemies with Atlanteans has really underlined this issue.

**Comment by aredfan** [comment]
I've checked and this bug happens in TombATI too.  The spaz effects also happen when Lara is floating or underwater too.

**Edit:** This happens when pulling underwater levers too.

https://github.com/LostArtefacts/Tomb1Main/assets/94776985/f414f59a-1217-4385-a8d2-f924807b9d6d
