### ISSUE TITLE
Research: check if a secret trigger is intended

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#858]
In order to trigger the secret near the aqueduct in Midas, you can just jump above its tile in T1M from the aqueduct's top. I'm pretty sure in OG you had to drop to trigger it.
This ticket is to verify if the current behavior is consistent with OG TombATI. If yes, close this ticket; if not, convert this ticket to a regular bug report.

**Comment by walkawayy** [comment]
I just checked TombATI and the secret triggers when you jump over it.
