### ISSUE TITLE
Prevent music trigger if room is closed

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#865]
This occurred to me on a recent PS1 playthrough with a family member (still the only way to get a German dub without replacing audio files), and it's the same in TR1M, and made me think if it's worth adding extra code that prevents music triggers if the intended room (or moment) are still inaccessible.

Consider this case of the Neptune room in Folly (requires audio):

https://github.com/LostArtefacts/Tomb1Main/assets/4934209/a9ad52ef-311a-4776-834d-676f6e5ab4c2

I felt it's unfortunate to "waste" the music because the music trigger should maybe have been on a tile behind the door here. The music is intended to accompany the long dive down. Instead here it plays as you continue through the main room of the folly. I suppose there might be more occurrences of this throughout the game.

I assume this would either mean to inject a changed level file where the music trigger has been moved behind the door, or add code logic that only plays music tracks _if_ a specific door has been opened. Both don't seem overly desirable maybe. Let me know your thoughts.

**Comment by lahm86** [comment]
An injection will be easiest imo - I think it would be too complicated to handle it automatically, especially for this kind of situation as technically you are in the Neptune room at that point.

![image](https://github.com/LostArtefacts/Tomb1Main/assets/33758420/93d2b4d5-54ea-4d45-85aa-a62f141fea63)

Can certainly tackle this as part of #755.

**Comment by aredfan** [comment]
Nice find.  I agree it's a waste for the Neptune music to play prematurely.  The Thor and Damocles rooms have music triggers placed past the doors, so it would be consistent to move back the Neptune music trigger as-well.

Agree with Lahm that floordata injection is the way to tackle this issue.

**Comment by lahm86** [comment]
I'm planning to bundle the fix for the 4-key music trigger into this issue as well, given that it's within scope I feel (a Folly music trigger problem basically).

https://github.com/LostArtefacts/Tomb1Main/discussions/755#discussioncomment-5275212
