### ISSUE TITLE
OG bug: Lara's shadow briefly disappear after pulling block

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#870]
While watching a live steam of T1M on Twitch, I've observed that when Lara completes pulling a block, her shadow briefly disappear from below her feet.

**Update:** Replaced screenshot with video

https://github.com/LostArtefacts/Tomb1Main/assets/94776985/07b6772c-0e68-4245-9781-d34982d771fc

**Comment by walkawayy** [comment]
Potentially relevant: https://github.com/Trxyebeep/tomb3/commit/11ee6dbc9bdf712451586f1c58ea378317e948ac
EDIT: apparently not relevant according to troye.

**Comment by aredfan** [comment]
I just realised that the shadow doesn't disappear entirely, it ends up on top of the block.

![1](https://github.com/LostArtefacts/Tomb1Main/assets/94776985/1898a3ca-33dc-4d45-b1b5-4afa22e12e67)

**Comment by Richard-L** [comment]
Trying to think of occurrences where Lara is not on the ground but can still interact with an object. Does the shadow do this kind of tile jumping also when she's pulling an underwater lever maybe?

**Comment by aredfan** [comment]
> Trying to think of occurrences where Lara is not on the ground but can still interact with an object. Does the shadow do this kind of tile jumping also when she's pulling an underwater lever maybe?

Not as far as I can tell.  The camera is usually fixated on Lara when pulling underwater levers, but I found a decent angle to record in City of Khamoon.

https://github.com/LostArtefacts/Tomb1Main/assets/94776985/82a7790f-9222-4795-917e-a36ac55d1305

**Comment by aredfan** [comment]
Closing as a duplicate of #1576.
