### ISSUE TITLE
Prevent Bacon Lara movement when she is dead

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#875]
Bacon Lara still responds to some of Lara's movement when she is dead - such as:
- Looking
- Drawing weapons/firing
- Entering body-hit animations

Once she has died, her movement should be fully suspended.

**Comment by aredfan** [comment]
This reminds me that after the first time Lara "kills" Natla, her right arm still targets Lara.  Probably not related to this issue though.
