### ISSUE TITLE
Music and Unfinished Business.

### ISSUE THREAD

**Issue by WPstart** [LostArtefacts/TRX#891]
Hi the links to the Music Pack and Unfinished Business seem to be dead so It won't download either of them when installing.
Is there a way around this?

**Comment by aredfan** [comment]
Hey, can you re-check if the links are working for you now?

https://github.com/LostArtefacts/Tomb1Main#installing-advanced--manual

**Comment by WPstart** [comment]
Now working! Thank you for sorting so quickly. :)
