### ISSUE TITLE
Natla not waking up

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#892]
Reported here https://discord.com/channels/1071085441077481544/1071085441656299602/1130098131565019216

Video: https://streamable.com/d8pgwy

Supposedly occuring since v2.15.1

**Comment by aredfan** [comment]
Just to add that Natla's right arm doesn't target Lara after 1st death in this version (see #878), but this wasn't the case in the previous version v2.15.

**Comment by aredfan** [comment]
Been doing some further testing, it seems that this bug occurs only if Natla is on the surface or flying low.  If Natla is flying high then the bug doesn't happen.

**Comment by rr-** [comment]
@walkawayy @lahm86 any idea what might be the reason for this?
I suspect 493287d8e835eefdc3f3a8885561dd20ad68cad9 the change in `creature.c` for apes' vaults:

```diff
diff --git a/src/game/creature.c b/src/game/creature.c
index c96215b1..0e0ddb37 100644
--- a/src/game/creature.c
+++ b/src/game/creature.c
@@ -631,6 +631,10 @@ bool Creature_Animate(int16_t item_num, int16_t angle, int16_t tilt)
             item->pos.x_rot = angle;
         }
     } else {
+        floor = Room_GetFloor(item->pos.x, item->pos.y, item->pos.z, &room_num);
+        item->floor =
+            Room_GetHeight(floor, item->pos.x, item->pos.y, item->pos.z);
+
         if (item->pos.y > item->floor) {
             item->pos.y = item->floor;
         } else if (item->floor - item->pos.y > STEP_L / 4) {
@@ -640,10 +644,6 @@ bool Creature_Animate(int16_t item_num, int16_t angle, int16_t tilt)
         }

         item->pos.x_rot = 0;
-
-        floor = Room_GetFloor(item->pos.x, item->pos.y, item->pos.z, &room_num);
-        item->floor =
-            Room_GetHeight(floor, item->pos.x, item->pos.y, item->pos.z);
     }

     if (item->room_number != room_num) {
```

**Comment by lahm86** [comment]
> @walkawayy @lahm86 any idea what might be the reason for this? I suspect [493287d](https://github.com/LostArtefacts/Tomb1Main/commit/493287d8e835eefdc3f3a8885561dd20ad68cad9) the change in `creature.c` for apes' vaults:
> 
> ```diff
> diff --git a/src/game/creature.c b/src/game/creature.c
> index c96215b1..0e0ddb37 100644
> --- a/src/game/creature.c
> +++ b/src/game/creature.c
> @@ -631,6 +631,10 @@ bool Creature_Animate(int16_t item_num, int16_t angle, int16_t tilt)
>              item->pos.x_rot = angle;
>          }
>      } else {
> +        floor = Room_GetFloor(item->pos.x, item->pos.y, item->pos.z, &room_num);
> +        item->floor =
> +            Room_GetHeight(floor, item->pos.x, item->pos.y, item->pos.z);
> +
>          if (item->pos.y > item->floor) {
>              item->pos.y = item->floor;
>          } else if (item->floor - item->pos.y > STEP_L / 4) {
> @@ -640,10 +644,6 @@ bool Creature_Animate(int16_t item_num, int16_t angle, int16_t tilt)
>          }
> 
>          item->pos.x_rot = 0;
> -
> -        floor = Room_GetFloor(item->pos.x, item->pos.y, item->pos.z, &room_num);
> -        item->floor =
> -            Room_GetHeight(floor, item->pos.x, item->pos.y, item->pos.z);
>      }
> 
>      if (item->room_number != room_num) {
> ```

I have some time today so I will do some investigation.
