### ISSUE TITLE
BUG: Game image freezes after 10 seconds if in Fullscreen mode

### ISSUE THREAD

**Issue by Nickelony** [LostArtefacts/TRX#897]
When I run the game, everything is fine for around 5-10 seconds. After that, no matter whether you are in the menu or in-game, the image of Tomb1Main freezes and never recovers. The sounds are still playing and seemingly the game runs fine, since I can hear Lara's footsteps and all, but the image is frozen, no matter if I ALT+TAB or change to windowed using ALT+ENTER, the image never unfreezes and sometimes even flickers.
The only way to prevent this screen freezing from happening is to force the game into Windowed before the 5-10 seconds pass.

I can replicate this issue on my Win11 (i5 11th Gen. + RTX 3050) laptop, but I can't replicate it on my main PC (Win11 + i7 8th Gen + GTX 1080Ti).
Disabling anti-virus doesn't make a difference.
No extra hardware (e.g. gamepad) was connected.
I have no idea what is happening, nor do I have any extra logs to show, since the screen freezes without any errors.

**Comment by walkawayy** [comment]
Make sure the game is running using your GPU and not Intel graphics. Other than that, this is the first time I've ever heard this. Maybe a GPU driver bug?

https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/

**Comment by Nickelony** [comment]
> Make sure the game is running using your GPU and not Intel graphics. Other than that, this is the first time I've ever heard this. Maybe a GPU driver bug?
> 
> [howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10](https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/)

That fixed it!
I was actually thinking that might've been the issue, but I couldn't tell on which GPU the game was running.
It's a bit odd that it would just freeze the image after a few seconds and nothing else.

**Comment by walkawayy** [comment]
Nice! Gonna close this issue.
