### ISSUE TITLE
T1M bug: Lara stutters when climbing up

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#901]
`notice how her hip is stuttering when climbing up`

**Tomb1Main:** https://streamable.com/jcttu5

There is no stuttering on either TombATI or DOS versions.

**TombATI:** https://discord.com/channels/1071085441077481544/1075372522377322516/1133313741744767016
**DOS:** https://streamable.com/4q2xpq

Reported by Raildex on discord.

**Comment by Raildex** [comment]
This seems to affect other animations, too.
I think it is happening on animations that have a framerate other than 1, i.e. that have interpolated frames between keyframes

**Comment by walkawayy** [comment]
Confirmed to be caused by the interpolated matrix change in #768.
