### ISSUE TITLE
OG bug: Natla rotates uncontrollably when more than one is active

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#906]
Although not an issue in OG Great Pyramid, if more than one Natla is active and one goes into her semi-death state, she can spin on the floor as shown below. In this video there is another active Natla near the beginning of the level in the flying state.

https://github.com/LostArtefacts/Tomb1Main/assets/33758420/2695930b-a247-41f8-b093-55571bb8e132

This also affects her behaviour when she wakes up again, where she doesn't enter the normal standing animation to shoot at Lara and instead spins and moves constantly regardless of Lara's position.

**Comment by walkawayy** [comment]
We could maybe band-aid fix this by turning `int16_t  m_Facing` into `int16_t m_Facing[MAX_ITEMS]`. And then access it with `m_Facing[item_num]`? If we did a more programmatically appropriate fix by removing the `static` var, we'd have to be sure we don't mess with her OG behavior.

**Comment by lahm86** [comment]
A similar idea I had was adding another `int16_t` to `CREATURE_INFO` or even a `void *`, as it doesn't appear to need to be saved. I do prefer it being local to Natla's module though as you suggest. The unfortunate side effect would be `MAX_ITEMS - 1` unnecessary slots in the majority of cases when Natla is present.

**Comment by walkawayy** [comment]
What about using `item->data`? I know Flame Emitters use it to track the FX number. (`item->data = (void *)(fx_num + 1);`)

Creatures do something like `CREATURE_INFO *natla = item->data;` though which I don't totally understand.

**Comment by lahm86** [comment]
It's used here, so there can be at most 8 active enemies at a time. `item->data` will point to whichever slot has been allocated, and will be `null` when the enemy is temporarily deactivated i.e. still alive but too far from Lara.
https://github.com/LostArtefacts/Tomb1Main/blob/develop/src/game/lot.c#L39

**Comment by rr-** [comment]
I think I prefer the `void *` approach. It's' a bummer that this concept was already (ab)used to store AI-related structures – but not quite in all cases, which makes it impossible to simply rename it to something suitable. This pointer reuse technique is also understandable given how memory constraints were much stricter back in the day. Since `data` is already taken, how about `priv` to highlight its purpose that should be local to implementations in ai/?.

**Comment by lahm86** [comment]
`priv` sounds good. Do you think it'd be best in `CREATURE_INFO` or `ITEM_INFO`? I was leaning towards `CREATURE_INFO` as it shouldn't be needed for non-AI things, but maybe it'd be best to make it available for any item for any future cases.

**Comment by rr-** [comment]
Let's go with ITEM_INFO.
