### ISSUE TITLE
Enabling cheats and Lara's braid resets after a tombmain run (or after a reboot anyway)

### ISSUE THREAD

**Issue by edsoftitaly** [LostArtefacts/TRX#920]
Hi, I've had a problem with the tombmain1 game and would like to report it. The problem is with the activation status of the Lara Croft cheats and braid, which resets every time I close the game, even if I don't restart the system. This prevents me from enjoying the game as much as I would like and forces me to re-enable the options every time I start it by running the configuration tool. I would like to know if there is a fix for this bug or if a patch is planned in the future. Thanks for the attention.

Here's my system configuration:

OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22622 N/A Build 22622
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00326-11250-10002-AA784
Original Install Date:     3/17/2023, 3:03:24 PM
System Boot Time:          8/13/2023, 9:11:19 AM
System Manufacturer:       Gigabyte Technology Co., Ltd.
System Model:              AB350M-DS3H V2
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 1 Stepping 1 AuthenticAMD ~3000 Mhz
BIOS Version:              American Megatrends International, LLC. F52h, 2/9/2023
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              it;Italian (Italy)
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     32,690 MB
Available Physical Memory: 24,663 MB
Virtual Memory: Max Size:  34,738 MB
Virtual Memory: Available: 24,597 MB
Virtual Memory: In Use:    10,141 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\RYZENDESKTOP
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5028948
                           [02]: KB5012170
                           [03]: KB5015669
                           [04]: KB5017384
                           [05]: KB5017021
Network Card(s):           3 NIC(s) Installed.
                           [01]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Intel(R) Wireless-AC 9260 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.87
                                 [02]: fe80::48cc:6ff:fe3e:1b1
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

Here's my log file.
[Tomb1Main.log](https://github.com/LostArtefacts/Tomb1Main/files/12329109/Tomb1Main.log)

**Comment by walkawayy** [comment]
What directory is your game installed in? This sounds like the game is not able to write to the config file because of restricted file permissions.

**Comment by edsoftitaly** [comment]
Good afternoon,

I created a folder on C: drive named C:\TOMBMAIN.

This folder has all the needed permissions.

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by walkawayy** [comment]
Can you try copying the folder and running from your desktop just to be sure?

**Comment by edsoftitaly** [comment]
Sure, expect to get a feedback by tomorrow!

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by walkawayy** [comment]
Thanks. Can you also post your `"C:\Tomb1Main\cfg\Tomb1Main.json5"` when you do that?

**Comment by edsoftitaly** [comment]
Hi,

 

It seems like copying the contents to another drive and then back to C drive solved the problem. The issue resided on how Windows handled permissions in this scenario.

 

Thanks for your help!

**Comment by walkawayy** [comment]
Awesome!
