### ISSUE TITLE
"official" texture pack support and braid compatible models

### ISSUE THREAD

**Issue by Bittermens** [LostArtefacts/TRX#922]
Is there any ETA on when tomb1main will receive this official support? tombATI and tomb2main supports it easily, and since T1main is based on tombati, it should support it out of the box.

Plus, i read that you guys were planning to add it on a later date, but i think it would be better if it uses if one of the two above supports it.

Also, the TR community made a Lara Model replacement based on her TR3 Model which features a static bread a long time ago, it would be possible to make that model optional and using the existing animated braid?

And kudos for this project, i hope you guys expand to TR3 and 4.

**Comment by aredfan** [comment]
> i hope you guys expand to TR3 and 4.

Just addressing this part as it's not for me to answer the other questions.  There are already decompilation projects for TR3/4 which are considered equivalent to Tomb1Main and TR2Main, you can check out said projects via the following links:

- https://github.com/Trxyebeep/tomb3
- https://github.com/Trxyebeep/TOMB4

Make sure to read USING.md if you do decide to give these projects a try.

**Comment by rr-** [comment]
This is already tracked here: https://github.com/LostArtefacts/Tomb1Main/issues/347
To answer your question about when: the answer is as usual with ETAs – Soon™
