### ISSUE TITLE
OG bug: dead centaurs explode again after reloading

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#924]
This occurs in TombATI and T1M and can be recreated in Tomb of Tihocan as follows.
* Enter the temple at the end
* Cross the trigger to activate the centaur on the right
* Return outside and kill it
* Save and reload
* Cross the trigger again inside the temple
* Return outside to within the centaur's range

https://github.com/LostArtefacts/Tomb1Main/assets/33758420/1092712c-1e5f-43f9-9aea-3f243660b4d9

**Comment by aredfan** [comment]
@lahm86 Not sure if relevant or fixed already.  I repeated all the steps above with one exception - the second centaur is left alive.  In this scenario the statue breaks apart instead.

https://github.com/LostArtefacts/Tomb1Main/assets/94776985/d6b6c38a-35a2-4b95-92dc-dd10c9d6b47d

(The second centaur is still around, just out of sight in this video.)

**Comment by lahm86** [comment]
Thanks for this @aredfan. The implemented fix also resolves this issue 👍
