### ISSUE TITLE
T1M bug: Centaur statue animation is incorrect when spawning

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#926]
I was checking out @lahm86's discovery in #924 when I've stumbled upon an additional bug.

**T1M:** When spawning, the centaur is galloping.

https://github.com/LostArtefacts/Tomb1Main/assets/94776985/f1cd3637-48de-404c-929f-64fcd0f142e0

**TombATI:** When spawning, the centaur is rearing.

https://github.com/LostArtefacts/Tomb1Main/assets/94776985/3bf1e948-fbc6-4f8c-b47d-5d934a1c5902

**Comment by walkawayy** [comment]
Hm maybe related to the new animation setting function @lahm86 ? I can investigate later if you want. Or since you were already looking at the centaur you could check.

**Comment by lahm86** [comment]
Will check it out, surprised I didn't notice this when looking at the other issue.
