### ISSUE TITLE
My game just randomly deletes itself everytime I load it

### ISSUE THREAD

**Issue by Circe666** [LostArtefacts/TRX#927]
So I had the game installed on my laptop for a while and it was all fine, until one day I loaded on as normal and then the game just stopped and shot me out to my home screen, and the app was no longer on my desktop. So I redownloaded it and the exact same thing happened, I've done this about 5 times and I'm seeing no difference. I would love some help.

**Comment by aredfan** [comment]
I'm guessing the Windows Security is removing your Tomb1Main.exe app.

Try adding Tomb1Main.exe to exclusion.  Here's how: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Edit:** In my case I follow these steps: Settings > Privacy & Security > Windows Security > Virus & threat protection > Manage settings (under Virus & threat protection settings) > Exclusions

**Comment by Circe666** [comment]
Omg thank you so much you are a lifesaver!

**Comment by walkawayy** [comment]
Great! Is the issue fixed @Circe666 ?
