### ISSUE TITLE
T1M bug: UI bar scale setting also affect bars in the controls menu

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#930]
Related to #658 (v2.12) and # #776 (2.14)

For example, when UI bar scale is set to 0.7:

![Title](https://github.com/LostArtefacts/Tomb1Main/assets/94776985/8a84b036-f4c1-4927-9c30-c1179eecacc0)

**Comment by walkawayy** [comment]
I think this was a known bug after #797 I forgot to open an issue for.
