### ISSUE TITLE
Rework new game+ bonus flag to persist

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#966]
Players may start a new game after beating the game and not want new game+ mode on. So, the new game menu should be added after the game is completed once if `enable_game_modes` is false.

A new `bonus_unlock` flag for new game+ should also be added to the savegame. That way, once the player has beaten the game at least once, the game will remember between sessions and allow the user to pick from the new game menu whether to use new game+ or not.

**Comment by Richard-L** [comment]
This makes me think whether saving/loading will remember if the playthrough was NG or NG+? Hope that doesn't introduce too much complexity.

**Comment by walkawayy** [comment]
> This makes me think whether saving/loading will remember if the playthrough was NG or NG+? Hope that doesn't introduce too much complexity.

Ya that already exists. This would be an additional setting to remember if the player has beaten the game before. Like a user settings kinda thing modern games use.
