### ISSUE TITLE
bug: cannot make jump

### ISSUE THREAD

**Issue by khirasier** [LostArtefacts/TRX#977]
you cant make the jump up to the second secret on the first level of the game.

**Comment by lahm86** [comment]
The secret is reached as follows - so just press action and forward on the far left. Does this not work for you?

https://github.com/LostArtefacts/Tomb1Main/assets/33758420/203e1299-a4a0-479a-8304-3f00c6e48bdc

**Comment by rr-** [comment]
Should we fix this? I think it may cause some domino effect on jumps…

**Comment by lahm86** [comment]
My feeling is it shouldn't be fixed - agreed it would likely have in impact on many more jumps across OG and custom levels.

**Comment by aredfan** [comment]
Agreed it shouldn't be fixed.  Besides, there are walkthroughs that explain how to climb this part, for example this [guide](https://tombraiders.net/stella/walks/TR1walk/01caves.html) by Stella.
