### ISSUE TITLE
Game keeps crashing at random, or when I try to remap the controls 

### ISSUE THREAD

**Issue by Yamato5617** [LostArtefacts/TRX#986]

**Comment by walkawayy** [comment]
Can you upload the Tomb1Main log file from the game folder after it crashes?

**Comment by Yamato5617** [comment]
[Tomb1Main.log](https://github.com/LostArtefacts/Tomb1Main/files/12623484/Tomb1Main.log)
is it this one?

**Comment by walkawayy** [comment]
Ya thanks. Looks like you are missing some audio files: S_Audio_StreamSoundInitialiseFromPath Error while opening audio music/track57.flac: No such file or directory

You can try rerunning the installer and making sure to answer yes when it asks to install the music files.

**Comment by Yamato5617** [comment]
It doesn't look like that did anything unfortunately

**Comment by walkawayy** [comment]
Can you post the new log file?

**Comment by Yamato5617** [comment]
[Tomb1Main.log](https://github.com/LostArtefacts/Tomb1Main/files/12623855/Tomb1Main.log)

**Comment by BinhoXT** [comment]
I'm having a similar issue, but the game is not crashing, the screen just freezes. I can still hear the menu sounds.

EDIT: I thought it could be a resolution/fullscreen issue, so after trying different configurations, pressing ALt+ENTER to change from fullscreen to windowed fixed the issue.

EDIT 2: Ok, I remembered I had an issue with the game screen not fitting my whole monitor with the Steam version with other patches. So I had to change my desktop resolution scale to 100% instead of the default 125%. This also fixed the issue here for me.

**Comment by walkawayy** [comment]
> [Tomb1Main.log](https://github.com/LostArtefacts/Tomb1Main/files/12623855/Tomb1Main.log)

Looks like nothing interesting is in there. Can you zip your game directory up and post it here? That will help us debug it.

**Comment by Yamato5617** [comment]
I tried, however it said it was too big to post

**Comment by walkawayy** [comment]
> I tried, however it said it was too big to post

Hm the music isn't necessary but there could be potential issues with the level files. Could you try uploading using this service potentially?

https://send.vis.ee/

**Comment by Yamato5617** [comment]
https://send.vis.ee/download/3369f2e8351820f5/#kJgjsmb493dByUa0vz2YUw
here ya go

**Comment by walkawayy** [comment]
> https://send.vis.ee/download/3369f2e8351820f5/#kJgjsmb493dByUa0vz2YUw here ya go

Ah I'm so sorry. I missed this response and the link is expired. :/ Would you mind sending again? @Yamato5617

**Comment by Yamato5617** [comment]
https://send.vis.ee/download/6d79c677250fd23a/#AQCR84zTqpJ_fkVIzAqCAQ here you go

**Comment by walkawayy** [comment]
I don't see any bugs when using your upload. I asked some other people to test, so we can see if they have a problem.

**Comment by walkawayy** [comment]
Another developer didn't find any issues with the build either. What's your system specs and is it a desktop or laptop?

**Comment by Yamato5617** [comment]
I feel stupid for not noticing this much earlier, however the game was running on my integrated gpu, changing this 1 setting seems to have fixed my problems. Thank you for all your help, and I will update if I notice any more problems with crashing.

**Comment by walkawayy** [comment]
Ah no problem. Glad you figured it out. We've seen this issue before which is why I asked for the specs. It probably should be fine to run on the integrated GPU, but that's another issue ha. Have fun!
