### ISSUE TITLE
OG bug: Bats flicker on death and cause Lara to shoot too rapidly

### ISSUE THREAD

**Issue by fare67t** [LostArtefacts/TRX#992]
When targeting a freshly killed enemy / already dead one (the very first bats, for example), lara fires her guns WAY too fast for a moment.

https://github.com/LostArtefacts/Tomb1Main/assets/145511530/9d7b299e-9cb0-4b32-8d7b-d14223e33819

**Comment by aredfan** [comment]
This is an original bug as it's present on TombATI too.  Correct me if I'm wrong but I think it's just bats that are affected by this bug.

**Comment by Richard-L** [comment]
Good observation @aredfan . Was confused why it's a bat thing, but that would make sense.

**Comment by walkawayy** [comment]
> Good observation @aredfan . Was confused why it's a bat thing, but that would make sense.

@aredfan so does this affect bats only? I think I am misunderstanding @Richard-L 's message.
`I think it's just bats`
`Was confused why it's a bat thing, but that would make sense.`
What would make sense?

**Comment by Richard-L** [comment]
That it seems to only occur with bats :)

**Comment by aredfan** [comment]
> @aredfan so does this affect bats only? 

I think so because I haven't seen this bug affect enemies other than bats.  The faster shooting seem to happen during the bat's drop and bounce animation.

**Comment by EternalCosmos92** [comment]
I'd hazard a guess and say it is because Lara many times loses the bats out of her sight because of the dying and falling down animations the bats have. Lara's shooting animations get skipped and start anew when she loses her target and then finds it again and with the bats that happens very often in a short amount of time

**Comment by fawtytoo** [comment]
I'm sure the original title was correct and this was present in the DOS and PS1 versions. Surely this is a mis-observation and not a bug. The description given by @EternalCosmos92 is correct.

Don't get me wrong when I suggest it's not a bug, but it should depend on whether bats really do that when they land on the ground still dying. The fast shooting is just Lara re-targeting. To me, both those things would probably happen in real life.

Don't forget, Lara is never seen reloading her weapons, so there is some scope for things not being like in real life.

**Comment by lahm86** [comment]
There was a bug whereby the bat's falling speed wasn't being reset when it landed before the bounce. So the animation was shifting its Y position but fall speed was still taken into account when it shouldn't be, hence causing rapid shifts in position and Lara's guns to fire too often/quickly. Details in #1283.
