### ISSUE TITLE
Feature request: TR2 lean forward during standing jump

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#998]
It'd be nice if there was an option to include the subtle mechanic from TR2 jumps which moves Lara slightly forward when she performs a standing upward jump.

(Requested on a reputable Twitch stream)

**Comment by walkawayy** [comment]
I think she already does this? I tested in Caves and holding down jump will slowly move her forward.

**Comment by rr-** [comment]
I think there's a difference between how much  she moves. I might be mistaken tho.

**Comment by Richard-L** [comment]
I would also think it's the same amount.

**Comment by rr-** [comment]
There's a difference if the player happens to be holding the arrow button while jumping which I failed to mention in the opening post.

https://streamable.com/qwzc6u

The same thing is possible with jumping backwards.

https://streamable.com/enml44

**Comment by rr-** [comment]
I think it's ready to be taken now that we have `Lara_State_Stop`, `Lara_Col_Stop`, `Lara_State_UpJump` and `Lara_Col_UpJump` functions decompiled for TR2X.
